### ISSUE TITLE
[1.12] itemKey for nbt items (registered to AllNbt interpreter) doesn't account for meta

### ISSUE THREAD

**Issue by P3pp3rF1y** [mezz/JustEnoughItems#1004]
I saw that some of my items disappeared from JEI and debugging this figured out that the issue was introduced with https://github.com/mezz/JustEnoughItems/commit/251bd0a62883c3a0a3fdf264e163665c719fdf72 
Basically the AllNbt interpreter would previously return null which triggered logic in StackHelper that added metadata to the itemKey, but as it now returns ISubtypeInterpreter.NONE (aka emptry string) the meta logic is no longer triggered and thus subItems with different meta, but same nbt are ignored.

mezz, not sure if this was intentional and actually looking at the logic that I "fixed" in the past it wouldn't work even previously if subitem had the same nbt as another, but meta was different (it would display just the first one it came over). 

I am happy to submit PR, just need to understand if registering to this subtype interpreter should consider meta as well or if in that case mods need to write their own. Or perhaps if there should be another one in JEI (AllMetaNbt).

**Comment by mezz** [comment]
Thanks for the report!
The original intention of the AllNbt interpreter was just to look at nbt and not meta.
This is in contrast to the default behavior, which cares about meta and ignores nbt.

I think I should deprecate and eventually remove the AllNbt interpreter, since interpreters are very easy to implement in a few lines using lambdas, and will have whatever behavior the modder defines without ambiguity.
