### ISSUE TITLE
[Help] Implementing IRecipeTransferHandler

### ISSUE THREAD

**Issue by codetaylor** [mezz/JustEnoughItems#1067]
**My Goal**

I have a custom workbench that has a typical 3x3 crafting grid with an extra slot for a tool (non-stacking). When I shift-click on the recipe transfer button, I would like maxTransfer to apply to the 3x3 crafting grid despite the tool slot not being stackable. For example: 64 wood goes into the 3x3 and 1 axe goes into the tool slot. 

**What I've Tried**

First, I implemented `IRecipeTransferInfo`, which worked as expected when not shift-clicking. When shift-clicking, however, only one of each recipe item appeared in the 3x3 grid due to the limitation of the tool slot holding at most one item.

Next, I implemented `IRecipeTransferHandler`, thinking that I could use that to achieve the control over the transfer process that I needed. After walking through an implementation, specifically the `BasicRecipeTransferHandler`, I have come to the conclusion (now correct me if I'm wrong) that the `IRecipeTransferHandler` just prepares data to send to the server, and that the actual execution of the action takes place on the server, outside of the handler.

This bit seems to be limiting the transfer to one item each because of the non-stacking tool slot:

```java
int maxRemovedSets = maxTransfer ? 64 : 1;
for (Map.Entry<Integer, ItemStack> entry : slotMap.entrySet()) {
  ItemStack stack = entry.getValue();
  if (stack.isStackable()) {
    Integer craftNumber = entry.getKey();
    Integer slotNumber = craftingSlots.get(craftNumber);
    Slot craftSlot = container.getSlot(slotNumber);
    int maxStackSize = Math.min(craftSlot.getItemStackLimit(stack), stack.getMaxStackSize());
    maxRemovedSets = Math.min(maxRemovedSets, maxStackSize);
  } else {
    maxRemovedSets = 1;
  }
}
```

So my question is how can I solve this problem in an elegant way?

I thought of sending two packets from the `IRecipeTransferHandler`, each with different data, but since the server's packet handler clears the crafting grid, I doubt this would work. I also thought of implementing my own packet and packet handler, but I wanted to ask before I did the work.

Thanks for your time.

**Comment by mezz** [comment]
Currently the `IRecipeTransferHandler` has some limitations, mainly because the implementation is complex and sort of badly written. It works well though, which makes it hard to change.
It only fills in slots in complete sets. It will try to fill one complete set for a single click, and it will just repeat that action for a shift-click. It does not properly handle recipes that take multiple items in one slot, or crafting where one slot can have less items than another.

You could implement your own, but I need to warn you that it is very complicated.
A better idea might be to improve the JEI implementation so that it takes a boolean flag that makes it try to put as many items as it can, even if one slot has less.

**Comment by codetaylor** [comment]
> A better idea might be to improve the JEI implementation so that it takes a boolean flag that makes it try to put as many items as it can, even if one slot has less.

This sounds like the best plan of action to me. I will get started on a PR right away! :)
