### ISSUE TITLE
 [1.8.9-2.16.2.78] Crash on browsing items, compatibility issue with Buildcraft (7.2.0-pre6)?

### ISSUE THREAD

**Issue by Xiaminou** [mezz/JustEnoughItems#109]
Crashes whenever I browse any of the buildcraft pipes (I assume).
EDIT: downgrading didn't fix it, which means it might be an issue with Chisel and BC Facades?

Crash Report: http://pastebin.com/3ehjC9D6

**Comment by AEnterprise** [comment]
issue is in the facades, there rendering probably broke for one or more blocks

**Comment by Xiaminou** [comment]
should I report this to Buildcraft or Chisel? or both?

**Comment by AEnterprise** [comment]
try replicating it without JEI, if it crashes you when you scroll throught the BC facades creative tab it's a BC issue

**Comment by mezz** [comment]
Reported to buildcraft.

**Comment by Prospector** [comment]
Might want to leave this open until buildcraft fixes it so you don't get duplicates

**Comment by mezz** [comment]
From #113 it looks like this is most likely a bad interaction between buildcraft facades and chisel blocks.

**Comment by mezz** [comment]
Next release of JEI will handle this better by logging the crash only once per item (so all facades will have just one error with stack trace instead of 3000 of them).

New output looks like: https://gist.github.com/mezz/83709890562447fc5dcd
One crash report, and then
`Couldn't get ItemModel for BC Transport item buildcraft.transport.ItemFacade@11f11e95. Suppressed 3434 similar errors.`
