### ISSUE TITLE
Any plans to add support for custom game modes?

### ISSUE THREAD

**Issue by Vllama87** [mezz/JustEnoughItems#1118]
Just a simple request in theory, though I don't know enough about coding to say whether it would be easier on JEI's end or the mod author's end, but it would be great to be able to cycle through any custom game modes added by other mods (Creative Plus comes to mind). I assume it would depend how they are stored, is there a list of game modes that these mods add to? If so perhaps just pulling that list would be sufficient.

Anyway, great mod, great job, keep up the good work man!

**Comment by mezz** [comment]
Thanks for the request!
I have no plans for that feature, because JEI is very focused on just recipes. I do not want to add extra features that are unrelated, like in NEI, because other mods can do a better job and it opens up some creativity if it's not locked into this mod.

There are other mods that add buttons to change the game mode, like [Just Enough Buttons](https://minecraft.curseforge.com/projects/just-enough-buttons).
I think another mod should implement Creative+, I am a bit surprised that I don't know of any that do it yet.
