### ISSUE TITLE
Option to set an item as main Recipe Category Crafting Item.

### ISSUE THREAD

**Issue by noopynolife** [mezz/JustEnoughItems#1123]
I am making an addon that bridges thaumcraft and projecte (I know, hasn't ever been done before lol), and I gave the philosopher stone the ability to do crucible crafting. (crucible from thaumcraft 6)

I then set the philosophers stone as a Recipe Category Crafting Item, which worked, but now the philosophers stone shows up as main crafting item instead of the crucible. Which looks odd.

Any chance that a feature gets added in that allows one to register one item that stays the 'main' item and is standard displayed on top?

Im on 1.10.2 because Thaumcraft 6 is too, but Im not expecting to see this feature for such an ancient minecraft version. Its just a general suggestion.
![image](https://user-images.githubusercontent.com/36017265/35653260-9b515fc2-06e7-11e8-8e42-6f809d9cc559.png)

**Comment by mezz** [comment]
Hm this is a pretty strange situation, I'm surprised it has never come up before.
As a workaround, you can nicely ask Buuz to set the cauldron's `IRecipeCategory#getIcon` to the cauldron since that always gets used first. https://github.com/Buuz135/Thaumic-JEI/issues
Beyond that I'm not really sure. I think that is the simplest solution for now.

**Comment by noopynolife** [comment]
Ah okay, will do thank you!
