### ISSUE TITLE
Recipe GUI Interface Request

### ISSUE THREAD

**Issue by jredfox** [mezz/JustEnoughItems#1150]
NEI mod claims to have issues that they are unable to override your recipe guis look and feel to the way it use to be so Could you WIP up an interface for them so It can be regular again thanks.

https://github.com/TheCBProject/NotEnoughItems/issues/145

**Comment by covers1624** [comment]
`It will not be added back. Get used to JEI's feel. It would be an absolute nightmare to make it work properly, and JEI's is soo much cleaner and easier to use.` Regardless if mezz actually adds a way for me to override it cleanly, i will NOT be adding it back, end of story.

**Comment by jredfox** [comment]
You are not the sole owner of the mod so you don't have a say in it

**Comment by jredfox** [comment]
Why they would provide the info you would need to do so

**Comment by jredfox** [comment]
No ASM would be required if they gave you the info and interace so....

I also prefer nei's as it's the bottom pages are not at the top and the crafting tabs what happens if there is just more then just smelting and crafting then it becomes overloaded

**Comment by jredfox** [comment]
Please convince him to add it to his own addon it wouldn't be too difficult just a look and feel

**Comment by covers1624** [comment]
"Just a look and feel." Its literally a complete rewrite of the gui.

**Comment by jredfox** [comment]
**option can be disabled by default**.
Crafting/smeleting/other Tab can be described as page index like the old way
Page buttons could move to buttom.
You could replace the gui or wait to see what mezz says and then simply change the width height and texture the worse possibility is that you replace the gui with an forge event.

Please consider it

**Comment by mezz** [comment]
I've been working on making JEI split into a library and a gui so that other mods can add whatever gui they want for it. It's a work in progress and will not happen before 1.13.

I think in this case you're really antagonizing covers for no reason. You're not the project manager, you can't just demand people do things. Please stop.

**Comment by jredfox** [comment]
Well he claimed to be the official NEI the official nei would have replaced or at least reskined jei's recipes gui and moved down the button for recipe page. Also for something as simple as extending your gui and then repos the button and replacing via forge open gui event it wouldn't be too difficult. He was making it harder then it actually was. Since I refuse to do it for him I tried something like opening an issue but, you know what happened.

Maybe rather then an interface I could reskin the gui but, the buttons would still be fixed on top **so could you add a jei config option to move the recipe page index down I could work with that.** Since I could simply reskin the gui to old nei style and move a setting.

**Comment by covers1624** [comment]
`Well he claimed to be the official NEI the official nei would have replaced or at least reskined jei's recipes gui and moved down the button for recipe page` What? Are you fucking serious? You have NO IDEA what ChickenBones would do in this situation because he no longer makes mods for MC, ChickenBones put me in charge of his mods, and he respects my decisions. We are arguing over an arbitrary gui style, you have created a fucking mountain out of a mole hill. I will NOT be doing it because. A, JEI's gui is cleaner, easier to use, and is less confusing to users. B, it would be a logistical nightmare handling all the functionality JEI has with displaying recipes in such a limited gui. For the last time NO. Stop. Just Stop.

**Comment by jredfox** [comment]
moving to suggestion for manual reskining and I think I would know what chicken bones would have done if he merged with jei as an addon
