### ISSUE TITLE
Modded Minecraft 1.12.2 JEI just disappeared

### ISSUE THREAD

**Issue by SablePixelAdventures** [mezz/JustEnoughItems#1173]
I played my 1.12.2 Modded Minecraft series last night and it worked perfectly. I have not updated anything, I have not added any new mods, I changed nothing. 
Then when I booted up my game today, the JEI widget that appears on the right side of the page when I press " E" completely disappeared! No matter what setting I change it won't come back! 

How do I fix this?
Thank you in advance! 

---

Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Thanks for the report!
Have you checked your controls? By default Control+O will toggle the JEI overlay on and off, maybe you pressed it by accident.

**Comment by DefinitelyNotFred** [comment]
I'm having the same issue. Pretty sure I've never hit Ctrl O at any point, especially the five times or whatever that the overlay has disappeared. Problem is that the issue doesn't occur very often. I have no idea whether or not it's a conflict with another mod.

**Comment by DefinitelyNotFred** [comment]
The JEI overlay disappeared for me again. I happened to have only JEI and VanillaTweaks installed for mods when this happened, so that helps narrow it down. VanillaTweaks has been giving me issues with parsing errors when loading built-in advancements (see: strikerrocker/VanillaTweaks#32), so maybe that's part of the issue for me? (Edit: apparently that's intended behavior) I've also tried uninstalling and reinstalling JEI to see if I could reproduce it / fix it but that doesn't do it.

**Comment by DefinitelyNotFred** [comment]
Happened yet again and this time VanillaTweaks wasn't installed, so it definitely seems to be a problem inherent to JEI since I have no idea what I could be doing that would cause it to turn off. The toggle for the overlay is still set to the default ctrl + o (I've checked), and I have no other key combination that requires me to hold ctrl. I suppose I should say that I'm using jei_1.12.2-4.8.5.159.

**Comment by mezz** [comment]
When the issue happens, please please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by hron84** [comment]
Same issue happened after I removed BiomesOPlenty and regenerated a map. Log: https://gist.github.com/hron84/4c21b87c773d412764145ab86ee864b2
MC 1.15.2 Forge 31.2.29 JEI 6.0.2.12

**Comment by realsky41** [comment]
I think I solved it! I happened to have the same problem, but if you press and hold CTRL+O, it should come back after 5 seconds or so.
