### ISSUE TITLE
JEI Building ingredient filter

### ISSUE THREAD

**Issue by WaterXCubic** [mezz/JustEnoughItems#1300]
Hello, I'm having long JEI building ingredient filter time due to the mod Flat Colored Blocks (and it's large number of ids used), it took me about 5-10 minutes to load up only that part. (This doesn't happen in older versions) 

I wonder if there are any workarounds for it. Thanks a lot!

Current version :
jei_1.12.2-4.10.0.201
flatcoloredblocks-mc1.12-6.6
FML 14.23.4.2715

Previous version :
jei_1.12.2-4.8.5.144
flatcoloredblocks-mc1.12-6.6
FML 14.23.1.2587

**Comment by TheSnowyChickens** [comment]
Same here. :)
"Starting JEI took 4.080 min"

**Comment by mezz** [comment]
Thanks for the report!

Hmm that's strange, I wasn't able to see that happen. 

jei_1.12.2-4.11.0.205
flatcoloredblocks-mc1.12-6.6
`Starting JEI took 1.372 s`

Do you have some other mods that might be involved here? Maybe try with just JEI and Flat Colored Blocks and start adding mods from there.

**Comment by WaterXCubic** [comment]
Since I'm currently playing in a mod pack (All The Mods 3) that their own config for flat colored blocks, I copied it out and tested flat colored block alone and it still took a minute.

Then I observed the startup of the mod pack and realized that Chisel and Bits are also taking up a lot of time to start up.

Is it necessary to filter all of those stuff though? I believe the bits aren't supposed to be crafted IIRC :P 

Also, I noticed this in my logs
`[21:22:08] [main/ERROR] [jei]: Could not determine recipe category for recipe: class techreborn.api.recipe.machines.CompressorRecipe
[21:22:08] [main/ERROR] [jei]: Could not determine recipe category for recipe: class techreborn.api.recipe.machines.ExtractorRecipe`
These does not appear only once, but they are being spammed. I wonder if these increases the starting time or not too. 

All The Mods 3 mod list : https://minecraft.curseforge.com/projects/all-the-mods-3/files/2581310
Chisel and BIts : http://algorithmx2.github.io/Chisels-and-Bits/

**Comment by mezz** [comment]
If you delete the config for Flat Colored Blocks from the pack, does the problem still happen?

**Comment by WaterXCubic** [comment]
Yep, sadly..
`Building ingredient filter took 2.145 min`
Flat Colored Blocks also occupies 243 block ids, not sure if this will help :P.

Thank you for following up.

**Comment by mezz** [comment]
Well I took a look at the pack and here's what I found.

It took about 2 minutes for JEI to start for me in total.
 - There are an absurd number of fluids and fluid containers in the pack, and it takes about a minute for Forestry and Thermal Expansion to create the recipes.  
   - About half of that is from the BetweenLands's `canFillFluidType`, which calls a slow method in Forge. I will submit a fix for that in Forge soon. (Edit: done here https://github.com/MinecraftForge/MinecraftForge/commit/5a48ca99b6787c7f811045d1f98b26db6ce073b7)
- 25 seconds is spent by JEI just adding tooltips to the search tree. I think this is extra slow because a lot of the fluids and fluid-holding items have very long names.
- 10 seconds is spent by JEI getting tooltips
   - 2.3 seconds of it is from EnderIO's SpecialTooltipHandler
   - 1.4 seconds of it is from Snowshock's JEIIntegration tooltip handler
- 14 seconds is from cyclops core `onItemStackLoad` https://github.com/CyclopsMC/CyclopsCore/issues/113

Overall JEI is kind of working as expected, but the pack just has way too much stuff in it. Please try reporting this to ATM3 here, if they want to cut down on the pack loading time they might want to remove some fluid containers and other extraneous things from the pack: https://github.com/AllTheMods/ATM-3/issues

I also noticed that the pack takes a ton of ram, and JEI runs last so it gets hit pretty hard when you run out. If JEI is taking 5-10 minutes to load for you, you probably need more RAM. I had to increase it to 8 GB before it ran well, even 6 GB was struggling with garbage collection.

![2018-07-29_19 15 37](https://user-images.githubusercontent.com/916092/43374328-f8772c14-9363-11e8-92e7-842c8e9c293e.png)
![2018-07-29_19 16 08](https://user-images.githubusercontent.com/916092/43374329-f88f6978-9363-11e8-94a3-fea2201803ed.png)
![2018-07-29_19 16 10](https://user-images.githubusercontent.com/916092/43374330-f8a63bf8-9363-11e8-827d-c7421f18ecd7.png)

**Comment by WaterXCubic** [comment]
That's a lot of recipes lol. Thank you for the help, I might try to contact ATM3 devs.

**Comment by WaterXCubic** [comment]
Wait actually, can you please add a function to exclude mods from being into the `Building ingredient filter` part?
Since people may be able to cut down some startup time.
Please take this into consideration. Thanks.

**Comment by TheSnowyChickens** [comment]
I rly hate this Stale bot...
