### ISSUE TITLE
JEI not showing items

### ISSUE THREAD

**Issue by Lordkraai** [mezz/JustEnoughItems#1311]
Hey guys, I'm using JEI for All the mods 3 and I nor anyone else on my server can see recipes for certain items and allot of items not showing up in JEI what so ever (tho they exist in-game) 

For example, I know I can make a tinkers forge using iron, but according to JEI only Electrical steel will work.

Now I've looked in the config for the following line maxSubtypes, in config/jei/jei.cfg  but it dose not exist in that config (nor in any other JEI config) I have on my server, I've looked both server side and client side.

**Comment by mezz** [comment]
Thanks for the report!
I have removed `maxSubtypes` in recent versions because it was causing issues, so you don't need to worry about that.

I tried ATM3 and I was able to see what you're reporting.
I tried creating a mod pack with just JEI and Tinker's and it works fine though, you can see all the types of Tool Forge.

Please report this to ATM3 so they can narrow down the issue. I think it must be caused by some other mod in the pack, or from some config setting somewhere. https://github.com/AllTheMods/ATM-3/issues
