### ISSUE TITLE
Searching Cobblestone, with JEI, EnderIO, and FactoryTech? installed

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [mezz/JustEnoughItems#1318]
Issue Description:
I am the modpack author of Project Sky, i just got an issue about cobblestone, searching it with JEI and it crashing you.

What happens:
You search cobblestone in jei i guess and its a crash, maybe you hit U, but idk what he said because he didnt explain it well

What you expected to happen:
See the cobblestone recipe

Steps to reproduce:
Open JEI
Search Cobblestone
Hit U, or maybe R

Affected Versions:
EnderIO: .30
EnderCore: .37
FactoryTech: 1.5.3
JEI: .206
Minecraft: 1.12.2
Forge: 2739
SpongeForge? no
Optifine? no
Single Player yes

Your most recent log file where the issue was present:
https://paste.dimdev.org/mavuhaluho.mccrash

**Comment by CrankySupertoonArchive** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/4828
https://gitlab.com/dalapo/FactoryTech/issues/26

**Comment by HenryLoenwind** [comment]
```
Ender IO: Hello user, factech has a bug
User: Hello Ender IO developer, Ender IO has a bug
User: Hello JEI developer, JEI has a bug
me: where's the next window, I have a sudden urge to jump...
```

**Comment by mezz** [comment]
Thanks for the report!
This appears to be fixed by FactoryTech already.

@HenryLoenwind please consider adding try/catch to `PaintUtil.isValid` and just treat it as invalid if it crashes. There's always going to be broken stuff. Alternatively I can add a try/catch in JEI around the `RegistryPlugin` stuff but it would have a larger negative effect on your plugin since I'd be catching it fairly high up the chain and wouldn't be able to recover from it as well.
