### ISSUE TITLE
(Shift) clicking moves one extra random item/stack

### ISSUE THREAD

**Issue by MatthiasMann** [mezz/JustEnoughItems#1342]
Like issue #239 this still happens with jei_1.12.2-4.12.0.215

I'm mostly using Tinker's crafting station and next to it is an Actual Additions "Small" Storage crate. I'm often missing items from my inventory (like food, tools etc - things not involved in the crafting - but are nearly always located in the right column of my inventory) which I then find reliable in a storage next to a tinker's crafting station.

I'm nearly always using JEI's '+' button (with and without shift) to move items into the crafting grid. And some times the crafting is blocked because the extra item - but if it's a full 3x3 recipe the extra item seems to move directly into the storage crate.

Not sure if this is an issue with Tinker's or JEI - but I'm assuming that the '+' button logic is implemented in JEI.

Other version:
TConstruct-1.12.2-2.10.1.87
ActuallyAdditions-1.12.2-r140

**Comment by MatthiasMann** [comment]
Ok - got lots of new information!

The item which is "magically" transfered is actually in the inventory slot which is behind the '+' button. You can see this when you hover the mouse over the '+' button and then hit escape to close the JEI window.

When you now (instead of closing the JEI window with escape) use shift click to move as much as possible into the crafting click - you automatically also do a shift click on the item behind the '+' button (either the click goes through the JEI window - or more likely the shift click is still registered when the JEI window is closed).

This is then moving that item either into the crafting grid or into the attached storage (in case of Tinker's crafting station when the 3x3 crafting grid is full).

**Comment by mezz** [comment]
Thanks for the report!
This is an issue/incompatibility with another mod that handles shift-click in inventories.
Please try removing mouse tweaks or inventory tweaks and see if that resolves the issue.

**Comment by HenryLoenwind** [comment]
are you sure that isn't caused by you reacting to the button-down and the button-up being processed after the jei gui has been closed? Just a random thought without looking at the code.

**Comment by mezz** [comment]
There are two issues together that create this problem.

1. When JEI displays, it changes the current GUI screen, but not the player's open container. Unfortunately, I have to do it that way because I want to be able to go back to the previous GUI when JEI's screen closes, and there is not a good way to restore the previous container on both the client and server.

2. Mouse Tweaks is listening to the mouse events without using Forge's `GuiScreenEvent` for mouse and keyboard. JEI cancels any mouse or key events that it uses, but Mouse Tweaks is not listening for that because it is not that interested in Forge events (it can run without Forge).

I think what's happening is that when you shift-click, JEI gets the click event, moves things and changes the gui back. At about the same time, Mouse Tweaks sees you shift-clicked a container and moves things.

Let me know if you see a good solution here. I think the best solution might be to PR Mouse Tweaks so that it uses Forge's `GuiScreenEvent`s when available, but I haven't really had time to dig into that.

**Comment by mezz** [comment]
The related scrolling issue might be a purely Mouse Tweaks issue if this PR is correct: https://github.com/YaLTeR/MouseTweaks/pull/6

**Comment by mezz** [comment]
I have submitted a fix for this to MouseTweaks here: https://github.com/YaLTeR/MouseTweaks/pull/20/
