### ISSUE TITLE
messed up inventory tabs, only one page of items

### ISSUE THREAD

**Issue by InterruptingOctopus** [mezz/JustEnoughItems#1354]
![1536196579650](https://user-images.githubusercontent.com/23324666/45186650-34c4fc80-b1fc-11e8-85db-4ecaa2159911.png)
as you can see in this image, inventory tabs are crunched into eachother and jei only displays one page of items which even in a vanilla plus game is unrealistic. the page has invisible items representing Heat and Climate... climates, mekanism gases, and thaumcraft aspects, both from the base and addon mods.
i cant find the crash log for it but trying to press R and U for crafting information causes a crash as well.

**Comment by Ommina** [comment]
I'm struggling to see how JEI can be the cause here, but I've been demonstrated wrong more than once.

You'll find the crash logs in a folder named "crash-reports", probably one ore two folders below your 'config' folder (assuming you're sorting them alphabetically, of course).  I have hopes that a gist / pastbin of the actual crash will provide some insight.

**Comment by mezz** [comment]
Thanks for the report!
This is probably caused by another mod doing something terrible, I've never seen something like this before.
Try removing some of the mods that normally add tabs to the player gui and see if that helps.
