### ISSUE TITLE
Game crashes when looking at recipes in JEI

### ISSUE THREAD

**Issue by john01dav** [mezz/JustEnoughItems#1367]
Hello,

I am currently playing the All The Mods 3 Remix pack version 0.0.3 (or, rather, trying to, this bug is making it almost not worth it), and when I look at recipes, my entire client occasionally crashes. This is a *very* big deal with this particular pack, because the extreme inefficiencies in starting up the client with a lot of mods make it take 15 minutes.). This has happened 3 times so far, all today, and all 3 crash reports are attached. It tends to be caused by items that are makable with some sort of alloy smelting mechanic, but I have successfully looked at many allow smelting recipes without issue. So far, I have crashed when looking at the recipe for steel and conductive iron.

[crash-2018-09-23_00.14.36-client.txt](https://github.com/mezz/JustEnoughItems/files/2409891/crash-2018-09-23_00.14.36-client.txt)
[crash-2018-09-23_17.28.18-client.txt](https://github.com/mezz/JustEnoughItems/files/2409892/crash-2018-09-23_17.28.18-client.txt)
[crash-2018-09-23_23.53.23-client.txt](https://github.com/mezz/JustEnoughItems/files/2409893/crash-2018-09-23_23.53.23-client.txt)

**Comment by Ommina** [comment]
This looks pretty similar (well, identical to) #1353 -- I'm reasonably certain it has since been fixed in EnderIO.  I did look up the same items locally without problem, and there appears to be a commit on Aug25 that did some fussing with slot counts.

If you're on a server, this won't be much of a consolation.  But if you're single player, you can probably update EnderIO and get on with your day.
