### ISSUE TITLE
Add a favorite recipe button

### ISSUE THREAD

**Issue by GTMoogle** [mezz/JustEnoughItems#137]
Add a star button to a corner of recipe pages that adds them to a new favorites section.

**Comment by mezz** [comment]
~~Can you explain what you would need this for? I don't have a good idea of how it would be used, or how it would be useful. Thanks!~~

Edit: actually I misread what you wrote sorry. This would be similar to the Forestry Worktable. Since JEI is trying to be minimal, I think this would be better handled by something like that.

**Comment by Prospector** [comment]
I guess like frequently crafted item could be stored on a separate filter
so you could see all of them at once without researching? Not terribly
useful but I can see the purpose.

**Comment by GTMoogle** [comment]
I find myself working on several things at once pretty often, and its kind of annoying to type in the same searches back and forth repeatedly.

If it doesn't fit the mod, that's fair.  Feel free to close this then.  Cheers!

**Comment by mezz** [comment]
You can go to a previous search by pressing the up arrow in the search box, that should help!
