### ISSUE TITLE
[Suggestion] Save recipe button

### ISSUE THREAD

**Issue by Brillik** [mezz/JustEnoughItems#1404]
I was thinking it might be really nice to have a {Save} button on the recipe screen to save the recipe to the left side of the window.  Then you could have a list of recipes on the left that you are aiming towards, with the full list on the right. I realize there is a bind-able key to view previous recipe, but often the goal machine I'm aiming to make is 2-7 recipes away from the beginning parts I'm currently making. This would also be very nice in creating a visible to-do list as I am often distracted and forget what I'm working on with so many projects going on at once.

**Comment by johnhargrove** [comment]
This is a great idea, and what I came to the issue tracker looking for. Just a question to the developers -- if this isn't a feature you plan to develop soon, would you accept a PR for it? And if not, do you think this could be modded in as a JEI plugin or addon? I am not familiar with the developer ecosystem around JEI.

**Comment by mezz** [comment]
JEI's latest beta version lets you save ingredients to a list on the left side, that should help you get to your recipes much more quickly.

I am not sure if I should support recipes on the left directly. Maybe it would be better to try to save a "last viewed" recipe for every ingredient so that you get back to what you were looking at when you look up something multiple times.

**Comment by johnhargrove** [comment]
Oh, exciting! I will pull it down and try it out. :)
