### ISSUE TITLE
JEI crashing a modpack

### ISSUE THREAD

**Issue by ColorlotYT** [mezz/JustEnoughItems#1413]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

Hello! I am running JEI in a modpack called "StoneBlock" but whenever I run the pack, it crashes due to JEI, when I removed JEI it was fine and the game launched normally, here is the crash report: https://gist.github.com/ColorlotYT/27365c5a8decc2e104e99c72e33b50c9

**Comment by Ommina** [comment]
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded

You're not giving the pack enough memory to run.  Presently you're giving it 3GB -- and even though the world might start with that, I can't help but feel you'll run into GC issues as the world develops.  (Assuming you're willing to continue playing without JEI.)
