### ISSUE TITLE
JEI too slow searcing and journeymap dont let me quit a world

### ISSUE THREAD

**Issue by BlackHoleTON618** [mezz/JustEnoughItems#1432]
im using 1.12.2 1423 5 2768 forge i have 209 mods installed but even i deleted 100 pages of items in Jei it still too slow it lags when i start searching something if i click all pages lag spikes reduces but i dont have to click 90 pages right  ? and when i want to quit a world it simply cant i use 6GBs of ram 
[Yeni Metin Belgesi (2).txt](https://github.com/mezz/JustEnoughItems/files/2662569/Yeni.Metin.Belgesi.2.txt)

**Comment by mezz** [comment]
Thanks for the report!

It looks like your computer is having DNS issues or something similar, it can't access certain websites used by Journeymap and Minecraft authentication.
If you are using a firewall, make sure to allow java to access the internet, otherwise it might have been a temporary issue with your internet provider.

I do not really see anything in the log there that I think could be caused by JEI.

**Comment by BlackHoleTON618** [comment]
sorry i solved my problem by buying 1300 dollar new gaming pc thank you anyway
