### ISSUE TITLE
items not being shown unless hovered over

### ISSUE THREAD

**Issue by Brainslime1** [mezz/JustEnoughItems#1439]
when using JEI in my modpack not all items are shown as seen in the pic and i dont know why. and i cant find an issue here about it

https://imgur.com/a/ujPp88m

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by Brainslime1** [comment]
https://gist.github.com/Brainslime1/e13f322a3ab819742ed234fee1572468

hope this helps

**Comment by mezz** [comment]
Hmm unfortunately I don't see anything helpful in the log.
Is this your own custom modpack? If so, you should make a backup and try removing some mods to see if it fixes the issue. I think there is an incompatibility caused by another mod, and if you can find out which one then I can help fix the issue.

**Comment by Brainslime1** [comment]
i found out what mod was causing the problem its the Alien vs predator mod

**Comment by mezz** [comment]
Ok cool.
It looks like this issue has been reported to them already but there is no fix yet:
https://github.com/Ri5ux/AliensVsPredator/issues/3
They will need to fix it in their mod.
