### ISSUE TITLE
forestry:crated items causing crashes when looked up in JEI 

### ISSUE THREAD

**Issue by jenrant** [mezz/JustEnoughItems#1462]
Copy of [https://github.com/ForestryMC/ForestryMC/issues/2334](https://github.com/ForestryMC/ForestryMC/issues/2334) to get this resolved.

Crashed every time looking up something starting with "C" or "Co" in Just Enough Items. Disabling "forestry:crated.forestry.bee_combs.0" from showing up in JEI seemed to fix this issue, so I'm doing an issue report here.

Here's a crash report of it happening: [https://gist.github.com/JRantanenn/76417038efdd011851b3be8872a41c32](https://gist.github.com/JRantanenn/76417038efdd011851b3be8872a41c32)

There also appears to be another item that crashes JEI as well, which is "forestry:crated.natura.edibles.0"

Another crash report:
[https://gist.github.com/JRantanenn/caeabcac6304dcd4e5d7511c4d8e613f](https://gist.github.com/JRantanenn/caeabcac6304dcd4e5d7511c4d8e613f)

Edit: Found a couple other items that are causing the same crash in addition to the two above:
	forestry:crated.minecraft.cookie.0
	forestry:crated.minecraft.coal.1
	forestry:crated.minecraft.dye.4

**Comment by mezz** [comment]
Thanks for the report!

With just JEI, Forestry, and Forge there is no issue.
From the crash log, I think something (probably a coremod) has set `ForgeHooksClient#lightGatherer` to null by mistake.

Please make a backup copy of your mod pack and try removing mods to see which one is causing the issue. You can see which coremods you have in the section starting with `Loaded coremods (and transformers)` in your crash report.

**Comment by jenrant** [comment]
It appears that the issue has gone away when I removed Shadowfacts' Forgelin, Tesla Core Lib, Industrial Foregoing and Integration Foregoing.

**Comment by mezz** [comment]
Please try to narrow down which of those is causing the issue, report to them, and link back here.
I do not think this is an issue caused by JEI.

**Comment by micle546** [comment]
Same Issue here 

[crash-2019-01-30_20.19.54-client (1).txt](https://github.com/mezz/JustEnoughItems/files/2815321/crash-2019-01-30_20.19.54-client.1.txt)
[latest (2).log](https://github.com/mezz/JustEnoughItems/files/2815323/latest.2.log)

Happens when searching for "F" or "Fl"

Only happens for some clients on server using All the Mods 3 pack version 5.11.2

related (?) Issue: https://github.com/Chisel-Team/Chisel/issues/600

**Comment by mezz** [comment]
Please try to narrow down which mod is causing the issue.
I do not think this is an issue caused by JEI, something else is involved here.

**Comment by DJGoo** [comment]
Im having the same issue in All The Mods 3 (5.11.2) always with the crated humus. it may be related to optifine, although that usually causes memory errors.

Heres my crash-log
[crash-2019-02-20_18.42.03-client.txt](https://github.com/mezz/JustEnoughItems/files/2883550/crash-2019-02-20_18.42.03-client.txt)

**Comment by Sataana** [comment]
Having the same issue when I tried to look up "clay"
Inset huge crash report [here](https://gist.github.com/Sataana/dd96a1992dbd2593bd0e5221b2933952)
Does anyone know of a known fix?
Optifine not installed.
Did install FoamFix, BetterFPS & Surge

**Comment by corgiblu** [comment]
Got this crash too. Various items.

**Comment by mezz** [comment]
Please try to narrow down which mod is causing the issue.
I do not think this is an issue caused by JEI, something else is involved here.
Unless I can test with just a few mods, I will not be able to figure out where this bug is coming from.

**Comment by corgiblu** [comment]
Hum. I actually just noticed everyone who named actual items causing the crash it was all forestry crates. Could be just a bug with forestry?

**Comment by mezz** [comment]
With just JEI, Forestry, and Forge there is no issue.

**Comment by corgiblu** [comment]
Interesting. I'm still not entirely convinced it's not because of forestry.
Could be one of the add-ons maybe?

**Comment by mezz** [comment]
If someone can narrow down the list of mods (by making a backup of their pack and removing mods until something works) then I can figure out what the issue is from there. Until then, I don't really want to speculate.

**Comment by Sataana** [comment]
[This](https://github.com/ForestryMC/ForestryMC/issues/2395#issuecomment-479234809) was my fix for it
Downgrading JEI

**Comment by spiro9-peef** [comment]
> With just JEI, Forestry, and Forge there is no issue.

I would like to add something to this repeated statement.
As a programmer, I know from experience that it may seem like there is not an issue, however, there clearly is if Forestry and JEI are running into errors consistently like this. Bugs can hide in seemingly bug-free code. My first guess, it's Forestry causing the issue, since I'd presume JEI doesn't mess too much with item IDs and whatnot. Some other mod is likely conflicting with Forestry somehow and it causes a chain reaction that brings JEI, and Minecraft, crashing down. However, the error I get is a Java error caused by what appears to be stack overflow, passing a negative value into an array (type **ArrayIndexOutOfBoundsException** iirc). This is a nasty error and one that I'm uncertain which mod would actually cause, though my gut says it's JEI or Forestry. If it were me, I'd start checking any variable declarations involving byte/short/int and seeing if it could be part of the issue.
This is just my two cents though. I'm running a lot of mods that are interdependent which means I could easily break my modpack, so I won't be much help in finding the culprit mods, though if so many people are encountering it I'd personally presume it's related to Forestry and/or JEI. Though it is speculation, I wouldn't throw this out as a very real possibility. I don't expect you to act on it until you get some solid leads, but perhaps this is something to look at in the meanwhile. Perhaps if you can talk to the dev(s) of Forestry, you might be able to work it out together?

Anyways. TL;DR: "Based off my experiences with programming and modding, it is quite likely either Forestry or JEI causing this problem, and as such, I would still recommend looking into both as suspect until they both prove otherwise, since it could legitimately be any mod causing this - some mods bring out instability in others. Just my two cents, no need to act on it if you don't want to."

**Comment by mezz** [comment]
This is not the first or last bug involving JEI and other mods, but it has been open for an unusually long time because nobody with the issue has been motivated in taking the necessary first step of narrowing down the mod list.

I am happy to do whatever it takes to solve this issue once there is a manageable small space for me to debug in, like I have for numerous other cross-mod bugs  in the past.

**Comment by sireshades** [comment]
Not going to bother posting crash log, just offer a fix. 
Was crashing on typing "D" in the search box. 
Using all the mods 3 ver. 5.12.2
Ingredient render crash with forestry. 
Updated forestry to the latest 1.12.2 beta version,
The problem went away. Always update crashy mods before anything else. Updates happen for a reason.

**Comment by kacperoo29** [comment]
@mezz I have done some testing and it looks like FoamFix is what causes it. I couldn't reproduce it every time, but it seems like the higher "deduplicateModelsMaxRecursion" is set the more frequent this error occurs. Having it set to 9 never produced this error, while values from 18 and higher almost always resulted in crash when searching for "crated". I have tested it with nothing but Forestry and FoamFix in one set and Forestry, TeslaLib and FoamFix in the other and the results were the same in both of them.

**Comment by mezz** [comment]
Thanks @kacperoo29. Please report the issue to FoamFix here: https://github.com/asiekierka/FoamFix/issues

**Comment by RakDuhl** [comment]
When i scroll through JEI, it suddenly crashes and i can't seem to find the cause for this crash in the crashlog or debug.

[debug log](https://pastebin.com/ufbg79Ny) from where it crashes

**Comment by mezz** [comment]
```
Details:
    Mod Name: OpenBlocks
    Registry Name: openblocks:glyph
    Display Name: ' ' Glyph
    String Name: 1xitem.openblocks.glyph@32
```
@RakDuhl I think your issue is this one: https://github.com/sp614x/optifine/issues/2267
Please open a new issue next time instead of replying to an older closed one, I can mark always as duplicate if necessary.
