### ISSUE TITLE
Feature request: Bookmarks ON/OFF

### ISSUE THREAD

**Issue by zISKo666** [mezz/JustEnoughItems#1465]
Hi there,

Would be super duper nice to have a button or a config option for "Show bookmarks ON/OFF".

Have a great day
zISKo

**Comment by mezz** [comment]
Clicking the bookmarks button at the bottom left will turn them on or off.
Do you mean something else or is that what you are looking for?

**Comment by zISKo666** [comment]
Well I meant more like to switch it completely off ... no visible bookmark-button, also.

**Comment by mezz** [comment]
I have decided not to implement this feature, because the bookmark button is very small and I do not think it is an important enough option to put it in the config.

**Comment by Ruchian** [comment]
I have to agree with zISKo666, I find it rather startling to have possibly more bloat clutter in the same menu (inventory) and too was looking for a way to disable the feature in it's whole.

The idea of a list of favorites is a good one for some, but not something at least I asked for. My own opinion on this aside, I wonder why it must be placed on the other side of the default inventory. Can it not just overwrite the rest of the available items and be activated in search with a quick expression, like "!" or something. (what I mean is, using "!" (for example) to find the bookmarked items through search). Currently it looks to me like, it's just something that seems to increase load time and ram usage just when opening the inventory. 

There are mods that add buttons when opening the inventory. Now they argue with the bookmarks menu and the button simply because they're in the same corner.

The button has a nice design to it. The bookmarks menu itself also looks smooth. It's just not something I can recommend. If it weren't for the additional issues it may cause for some, the many other mods in every modpack and already RAM needyness of a modded client, it wouldn't be that big of a deal to have a little bit more clutter in the inventory. 

Just imagine a modpack with refined storage, flatcolored blocks and unlimited chisel works. It adds a lot of items, because of this JEI already lags. An extra window in the inventory with a few pages of bookmarked items just adds more lag in this case. That's why I think it may be better to overwrite search instead of adding a new window.

**Comment by mezz** [comment]
I am looking into ways to have the bookmarks placed optionally on the right side, so you toggle between it and the regular list. That may be delayed though, since I am mainly working on the upcoming 1.13 version right now.

I think you have some misconceptions about what contributes to lag. When items are not being rendered, they are just taking up some memory in JEI's search index and that's about it. The memory required for the bookmark list is very low, it is using existing features to display items. 

If JEI is really hitting your FPS, it is usually because you either have a screen size that shows a lot of items, or you are looking at some complicated items that are heavy to render. There is a config option to limit the max width of JEI so it displays less items, if you need that.

**Comment by Ruchian** [comment]
My screensize indeed shows a lot of items per page. (16x22)
I didn't know the number of them could be limited. That is indeed helpful. And I see. Yes, I didn't realize that of the the many complex items only what is displayed on a page is what truly contribute to the lag I experienced and it is good to know the bookmarks don't add any additional latency experiences.
(Though what I thought of here is that some may add a large number of these complex items to their bookmarks, have the book marks list opened and then scroll through the regular search. I suppose I was wrong to think this could have a impact on performance.)

Thank you for explaining. I'll look into limiting the number of items.

Added information: I found out how. I assumed that the 100 width value had something to do with it, but lowering it to half (50) didn't seem to do much, so I never realized what it was used for. Upon lowering it to 10, I realized that the width was equal to the maximum number of allowed items shown per row. I assume it works the same way with height. It makes me wonder who's computer can handle 100x320 items per page. xD
Never mind I guess. 

I like cleanness. I hope I didn't offend you in anyway. I really like Just Enough Items. I often use it. It's very practical and smooth. I like your designs. I was just sharing my thoughts, I suppose.
