### ISSUE TITLE
Texture Pack Issue w/ 1.12.2-4.14.4.262

### ISSUE THREAD

**Issue by nephatrine** [mezz/JustEnoughItems#1473]
When I updated from 4.14.4.260 to 4.14.4.262, it broke rendering of all the textures using OptiFine's CTM in custom texturepacks (tried multiple and it afftected all of them). Instead of the textures from the pack it just is rendering the entire texture atlas (i.e. lots of tiny random items/blocks) onto them as the texture. May be issue with OptiFine, but since it was caused by update of JEI I am reporting it here. Rolling back to .260 fixes the issue.

**Comment by Zergmazter** [comment]
I dont know if its related to the same bug but I am getting rendering issues of the default minecraft textures. Well Im not using a texture pack but dont know if the color grass is default due to sereneSeasons.

I removed optifine and the issue stopped. I'm thinking its actually the same issue you are having nephatrine, but acting in a different way.

![2019-01-22_16 56 06](https://user-images.githubusercontent.com/17000034/51569712-2d308800-1e6b-11e9-926d-3fb76d7fe2aa.png)

**Comment by ate0ate** [comment]
I am getting the same issue with grass blocks rendering incorrectly when using optifines fancy grass as well. Happened after the 262 update of JEI.

**Comment by mezz** [comment]
Thanks for the report!
I think this is an issue with my custom texture map interacting poorly with Optifine, I'll try to work around it.

**Comment by mezz** [comment]
Please try with version `4.14.4.263` and let me know if you see any issues.

**Comment by Zergmazter** [comment]
Well I dont see it happening on my end anymore. Issue seems to have been fixed. No more transparent blocks for me on ver 4.14.4.263.
