### ISSUE TITLE
Add DescriptionRecipes to 'u'(sages) of an item

### ISSUE THREAD

**Issue by gr8pefish** [mezz/JustEnoughItems#149]
[enhancement]

Currently the player has to use 'r' to see the description of the item (if it is added). Being able to check the usages of an item with 'u' and seeing the description there makes a lot of sense.

Issues:
May get a bit tricky internally with lists of items, may have to show a rotating list. Uncertain of best course of action on this, I will leave it up to you mezz.

**Comment by way2muchnoise** [comment]
Couldn't you just add the item to the `getInputs` and `getOuputs` in the wrapper? That should make them appear on r and u

**Comment by mezz** [comment]
I will do that yes. The issue that stopped me from doing it before is this: Multiple items. If you have a description for all doors and the player looks up "oak door" it should show the oak door instead of all the doors. If it's used as inputs and outputs, well you can only display one of those... so looking up the usage would show a rotating list of all the doors still. 
I think I'm fine with that small issue, it's useful to see the descriptions on U and R.
