### ISSUE TITLE
Multiblock structures placement dynamically align

### ISSUE THREAD

**Issue by WoozyMasta** [mezz/JustEnoughItems#1499]
Can you add support for vertical align for multiblock structures placement window?

![Multiblock tooltip](https://i.imgur.com/jjBrqUH.png)

**Comment by mezz** [comment]
Sorry I am not sure I understand the question. Can you say it another way?
The multiblock recipe is drawn by the mod, it is not done directly by JEI.

**Comment by WoozyMasta** [comment]
Hi, @mezz 

The problem with the overlay of text that overlaps the structure in the preview.

Earlier, I asked this question to the developer GregtechCE, he said that this is the problem of NEI alignment, and he cannot fix it.

I do not know how it works. But I suppose that you should set separate fields for text and preview, set them to the minimum height limit, and for the text field to make a dynamic change in height from filling.

![https://i.imgur.com/VLufvxy.png](https://i.imgur.com/VLufvxy.png)

I tried to explain, I hope you understand me) Sorry for my English

Maybe if you specify a place that is responsible for drawing this window, I will try to fix it myself and send PR

**Comment by WoozyMasta** [comment]
Or it may be easy to make a fill at 100% height for a frame with a template.

![https://i.imgur.com/ABF6bCo.png](https://i.imgur.com/ABF6bCo.png)

**Comment by mezz** [comment]
JEI limits the maximum height of the recipe so that they can fit on all screen sizes.
If I design it so that recipes take up the full height of your screen, then many mods would have recipes designed in a way that doesn't work for everyone by mistake. Mod authors often do not test things on every screen size.

The developer of GregtechCE will need to come up with a good solution to display their recipes in a readable way within those constraints.
