### ISSUE TITLE
JEI Category Removal Scripts No Longer Work

### ISSUE THREAD

**Issue by KAfable** [mezz/JustEnoughItems#1520]
Jared says that nothing changed on his end, as of the mod versions listed below, the script to remove JEI categories no longer works.

https://github.com/CraftTweaker/CraftTweaker/issues/755

**Comment by Saereth** [comment]
So we've been having alot of issue with this and it turns out if you do a jei hide of an invalid category it completely breaks the crafttweaker jei addon and none of your custom machine recipes will show in jei. In this case mekanism changed to deregister their categories when you turn a machine off in the configs, this made the jei hide call in crafttweaker for the infuser a reference to an invalid category and caused the crafttweaker jei addon to fail in the debug log thus causing the rest of our category removes from things like exu/thermal execute.

**Comment by mezz** [comment]
Thanks for the report!
I have replied in the CraftTweaker issue with a potential solution to the issue.

**Comment by mezz** [comment]
Jared has reopened the issue and will fix this in CraftTweaker.
