### ISSUE TITLE
Plus button texture

### ISSUE THREAD

**Issue by lesdmark** [mezz/JustEnoughItems#1523]
I am one of the people working on the JSTR texture pack, and noticed when I redid the button textures, there is a blue area that shows up behind the plus button now that none of the other buttons have. I am guessing it has to do with how it is rendered. I have included a pic to show what I mean. If you could make it not do that, I would appreciate it.
![Capture](https://user-images.githubusercontent.com/7751260/54857250-a108d880-4cd4-11e9-81ef-53ccf9f74dc0.JPG)

**Comment by mezz** [comment]
Thanks for the report!
I was not handling transparency correctly there, it was never noticed because there is usually a recipe background behind it.
Fixed in the next version of JEI 1.12.2, should be up shortly.
![2019-03-24_15 45 57](https://user-images.githubusercontent.com/916092/54887072-1f3bbb00-4e4c-11e9-89e8-97e996456c0a.png)

**Comment by lesdmark** [comment]
Thank you!
