### ISSUE TITLE
Server must have jei installed

### ISSUE THREAD

**Issue by Blazemakara** [mezz/JustEnoughItems#1525]
I have a personal server and have the latest JEI mod installed for both client and server and i am still getting this message popping up on the move items button. please help. I've tried downloading multiple times and i cant get it to work with Galacticraft.

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue. Please start up your server and paste the resulting server log to https://gist.github.com and link it here.

**Comment by sverinn** [comment]
same problem, here's my log:

[latest.log](https://github.com/mezz/JustEnoughItems/files/3017602/latest.log)

looks like forge doesn't recognize the mod file in mods folder sometimes

**Comment by mezz** [comment]
Hmm thanks. Strangely, the server log looks fine and shows the right version of JEI.
Can you also paste your client log the same way? Maybe I can find out more from that. I wasn't able to reproduce the issue myself.

**Comment by sverinn** [comment]
Hello.
The problem has appeared to be the JEI addons (such as JEHC, Just enough resources, etc.) installed on server. Removing them from server side solved the issue. Though, I still have no idea why it works like that.

**Comment by mezz** [comment]
Thanks for the info!
Can you try to narrow down the list of mods so that I can have a way to reproduce the bug in my dev environment? Does it happen with just JEI + JEHC and no other mods?

**Comment by FireGreenPlays** [comment]
**Hello, good morning, good afternoon or good night. It doesn't matter what time you are reading this, I just ask you to help me. I have a personal modpack host minecraft server purchased, I recently added the malisisadvert mod to the server (so I could make my survival prettier with some pictures. I soon realized that the advertblock had no revenue, so I added the CraftTweaker mod, I got it create a recipe for the block without much effort. The problem came soon after, when I tried to build the block in survival with the recipe I had created and... YES!! The recipe worked, but the item didn't appear in the box. I tried to remove them and put them again, restarted the server and still without success. That's when I decided to go research, I searched the internet all and nothing, no arguments about. So if someone can help me solve this and make it work, even if it doesn't, just by having an answer to this problem I would be at peace (of course, after some tests) Please, someone HELP ME!! Modpack is at version 1.12.2, if relevant.

**Comment by mezz** [comment]
Hello, please don’t post in random closed issues.
I’m sorry but this is not the right place to get help with your issue.
