### ISSUE TITLE
Fix or toggle for ingredient filter building.

### ISSUE THREAD

**Issue by pressRtowin** [mezz/JustEnoughItems#1581]
I've seen quite a few reports of loading times being extremely long, or just crashing altogether with JEI, simply due to there being a large number of block IDs present. Considering that the large number of block IDs only cause an issue when JEI is installed, and work fine on their own otherwise, I think this needs to be addressed by JEI.
If optimizing the ingredient filter building stage further is not possible. I suggest either a toggle to disable the ingredient feature entirely, or a blacklist of mods to not apply it to.
Currently JEI is the only obstacle in the way of me loading the game with a high block ID count, so I see "just reduce the number of blocks" as a valid solution.

**Comment by adaster98** [comment]
I second this. I can't even load my modpack. Been sitting for over an hour now on 'Building ingredient filter'. I have searched around and LOADS of people are having the same issue. It's seriously game breaking and needs to be fixed.

**Comment by Ommina** [comment]
I would suggest posting links to some logs, so that Those With Far More Knowledge Than I have something to go on.

Certainly, such long load times are not typical.  But without logs, it is not possible to determine if it really is the fault of JEI code, a large item ID count, memory constraints, a particular plugin, a combination of the above or who knows what else.

**Comment by Anokka** [comment]
Hello!
_I'm not a dev_, but after a lot of testing, i have concluded that having **optifine + vsync + JEI causes the extreme load times**.
Changing `enableVsync:true` to `enableVsync:false` in the options.txt (_inside the minecraft directory_) is an easy fix.
Hope this helps!

**Comment by adaster98** [comment]
> Hello!
> _I'm not a dev_, but after a lot of testing, i have concluded that having **optifine + vsync + JEI causes the extreme load times**.
> Changing `enableVsync:true` to `enableVsync:false` in the options.txt (_inside the minecraft directory_) is an easy fix.
> Hope this helps!

This seemed to help me.

**Comment by pressRtowin** [comment]
I've never once used vsync. I'm referring to another issue that came up a while ago, where the problem was (imo) dismissed with something in the vein of "clean up the mod. Not JEI's problem." When I say a lot of blocks, I quite literally mean a lot of blocks. I have over 5000 with 16 block states each right now. Considering that the mod referred to in the other issue worked fine as-is without JEI, and in my case, I've successfully loaded nearly 20000 blocks without JEI, but can't do so with JEI due to the specific step of the launch process I'm referring to, I'd argue it's very much JEI's problem to address, if even with something as simple as not building the ingredient filters for a set of blacklisted mods.

**Comment by Anokka** [comment]
I realise I must have misunderstood something about your earlier post. Vsync is enabled by default, so that's why I mentioned it.

**Comment by mezz** [comment]
Thanks for the report!

## Previous Related Issues

This vsync has happened before here: https://github.com/mezz/JustEnoughItems/issues/746
It took a collaboration between myself, cpw, and the author of Optifine to figure out what was going on. The fix should be in Forge now, I'm surprised this came up again.

There is also a known issue with 4k displays, which is related: https://github.com/mezz/JustEnoughItems/issues/1442

Another issue people run into is that they run out of memory. If your memory bar on the loading screen is showing red, you need to give more ram to java. JEI doesn't use a crazy amount of ram but it can be the straw that breaks the camel's back because it runs last, after everything else loads.

## Explanation

The vsync and 4k issues are ultimately "caused" by a design flaw in that version of LWJGL for rendering and keyboard handling. JEI checks tooltips, and mods check the keyboard to see if shift is held. Meanwhile, Forge is rendering the progress bars in such a way that LWJGL only allows 1 frame to progress every time the keyboard is checked.

## Next Steps

Please try disabling the Forge loading screen (open the `config/splash.properties` file, set `enabled=false`) and see if that fixes the issue. The result of that will let me know if it is an issue with the loading screen like before, or if it's purely a new JEI issue.

**Comment by pressRtowin** [comment]
To be clear, my issue is not the vsync issue. Disabling the loading screen does not help, neither does the resolution I launch in make a difference. As far as i can tell, JEI has a rather extensive step during setup (this also runs every time to reload chunks, switch shaders, etc., which makes this especially painful) which reads something along the lines of "building ingredient filter" (I'm out at the moment so I don't know the exact message, though I'm sure you know which step I'm referring to). When using a mod such as flat colored blocks, I can easily load into minecraft with 20000 blocks (using JEID). Due to whatever JEI does during this step, it's almost impossible to load into minecraft with this same configuration and JEI (short of leaving it launching overnight or something ridiculous). Even with my current reduced configuration of around 5000 blocks (16 block states each), the game takes 5 minutes longer to launch just because of JEI. I've allocated as much as 48GB of RAM to minecraft and have only observed around 21 being used during launch before it lags out entirely, and I've waited as long as an hour while JEI hangs on this step before force quitting.

**Comment by pressRtowin** [comment]
A recent example of the times I'm seeing with a rather reasonable number of blocks but a 1024x resource pack selected:

![image](https://user-images.githubusercontent.com/25999169/58838756-3acdf980-8625-11e9-9801-0e9e96e86961.png)

**Comment by mezz** [comment]
@pressRtowin do you have "color search" enabled in the config? JEI will spend time reading the pixel data of all your items to figure out what colors they are, maybe that is the cause.

For more context on this issue, I should explain what the ingredient filter is and why JEI uses it.
With NEI, every search would go over every item and check the search text against that item's tooltip. In big packs, that would mean searches could be very slow. 
One of the main design goals with JEI was to make searching instant, so I implemented an optimized search that gets all the item information up-front when the game loads. This is what takes time during "Building ingredient filter". That information is indexed and used for every search to make it fast.
