### ISSUE TITLE
Incompatibility issues with EZ Storage

### ISSUE THREAD

**Issue by squirrelkiller** [mezz/JustEnoughItems#160]
So EZ Storage used to work with JEI, but a recent update broke the compat, I will assume other mods might have this issue so I am going to include the crash log just so you can avoid causing similar issues in the future. Not so much expecting a fix (unless this is an unintended consequence of an update) as informing, I have also contacted the other dev so they can react accordingly.

http://paste.ee/p/eAaz2

This crash happens when trying to do a crafting recipe item transfer in their custom crafting window.

Oh and I expect to see this issue with mods such as AE or other mods that work similarly once they show up more.

Link to EZ Storage so you can test yourself if need be (problematic version is: 1.8.9-1.2.2): http://minecraft.curseforge.com/projects/ezstorage

**Comment by MrGraphic** [comment]
Same thing with [StorageNetwork](http://minecraft.curseforge.com/projects/storage-network). I'm guesing that this is just a matter of updating by other mod authors.
[Log](https://gist.github.com/MrGraphic/5e2c942c27d94d36a1cf) .

https://github.com/MrRiegel/Storage-Network/issues/7

**Comment by squirrelkiller** [comment]
I just want to brag for a moment that I was right about other mods that would have an issue, can I assume it most likely has to do with drawing on items in the inventories?

**Comment by mezz** [comment]
I see this issue has been reported to both mods. They implemented RecipeTransferHandlers very early in JEI's lifetime, and the code has changed since then. Before, it required using some of JEI's internal classes, now it can be done using only the API, so it shouldn't break again.

Link to EZ-Storage issue: http://minecraft.curseforge.com/projects/ezstorage/issues/1459
