### ISSUE TITLE
JEI issues on start-up

### ISSUE THREAD

**Issue by Fusilier72** [mezz/JustEnoughItems#1639]
I am trying to use "The Classic Modpack", however every time on start-up it tells me that Minecraft failed to start, and that JEI is the cause. 
Link to crash report: https://paste.dimdev.org/zogixozave.mccrash
I'm not particularly knowledgeable about modding, so I opted for the Technic pack download, and honestly have no idea how to diagnose what caused the problem. 
p.s sorry if the crash report is in the wrong format, I don't know how to convert it.

**Comment by Ommina** [comment]
The format of the crash report is just fine, and I, for one, wholly appreciate the external paste instead of copying it verbatim into the issue textbox.

As for the cause of the crash itself, you'll find it fairly near the top: **java.lang.OutOfMemoryError: GC overhead limit exceeded**.  It is simply running out of allocated memory.  Looking at the mod count, I'd guess at least 4GB will be required.

Some (ok, _all_) of the mod filenames look pretty darn odd.  If you are downloading your mods from unauthorized third parties, you're rather taking your chances with both stability and security.

**Comment by Fusilier72** [comment]
Thanks for the fix recommendation Ommina! It seems to have worked!
I have no idea about the filenames; I made sure I downloaded the modpack from the technic launcher from the official site, but thanks for the heads up, might be worth a scan.
