### ISSUE TITLE
[Feature Request] Config option for recipe precaching

### ISSUE THREAD

**Issue by DbpGaming** [mezz/JustEnoughItems#1656]
from how it was explained to me (if this is incorrect sorry) JEI precaches all recipes in ram, which seems to be a big ram hog in certain packs (this is probably just due to bad mod integration), but a option to have the recipes precached to stoage or not precached, would be a nice option to have, especially if its possible to not have to regenerate the cache unless recipes changed if its on storage

**Comment by mezz** [comment]
Thanks for the suggestion!
This is really necessary to make searching fast, unfortunately. It is unlikely that I will be able to implement it using less ram without it becoming extremely slow (see NEI's slow searching in the largest 1.7.10 packs... then keep in mind 1.12.2 packs tend to have way way more recipes).
I am not sure if I will get to this, but I will leave it open since it's at least worth a try some time.

**Comment by DbpGaming** [comment]
ah fair enough, yeah i get that it would be slower, just asking as i know for some people can't play modpacks over ram usage atm, and thought this could help, as even if it was slow it beats not being able to run the game in those cases

**Comment by Rensik** [comment]
Actually, can you please do this? This would save a huge neckache when building packs with large amounts of mods. Large packs have long load times as it is, and _not_ precaching recipes would cut that time down by a large margin, at least. Maybe cache the recipes as they load up in-game? The first search is slow, but the second one is faster due to the previous search?

Apologies for the necro-post, I just found this and went "that would save me a huge headache!"

**Comment by mezz** [comment]
The design of JEI in 1.13+ does less caching of recipes.
I have also added a config for a `LowMemorySlowSearchEnabled` option in JEI for Minecraft 1.16.3 
It will make searching slow, but lowers the memory required by JEI.
