### ISSUE TITLE
[1.12.2] java crash generating hs_err_pid error

### ISSUE THREAD

**Issue by mensreaMC** [mezz/JustEnoughItems#1704]
Been getting a weird crash that generates a hs_err_pid files instead of a normal crash report. I couldn't get it to repeat with JEI removed. Here's the pastebin link: https://pastebin.com/5pn0svtn

EDIT: At the time it happened I wasn't doing anything, just standing there.

**Comment by mezz** [comment]
Thanks for the report!

`hs_err_pid` error files are from the JVM itself crashing, which is pretty uncommon. 
This is not caused by JEI (it should not be possible to cause it at all...). Congrats, you found a bug in Java itself 😄.

Try updating your version of Java, that has fixed the issue for me in the past.

**Comment by mensreaMC** [comment]
Thanks for the response, you're the first dev that seemingly took one of these bug reports seriously enough to give me a useful answer. For posterity, I did update my Java but that didn't work. I also updated my display drivers, but I'm not sure if that's going to work or not. 

Regardless, it looks like I should be posting errors like this to a java forum or something, so I'll take it there.

Thanks again.
