### ISSUE TITLE
[1.12.2] Server must have JEI installed

### ISSUE THREAD

**Issue by Bloxy69** [mezz/JustEnoughItems#1737]
Hi,
I am trying to create a server for project ozone 3 so I can play with my friends. Everything works just fine except the feature that moves recipes from JEI into the crafting grid. I was reading the curseforge JEI site to try another version when I was that this feature had been disabled for server. I was wondering if there was any way to re-enable this feature? Also, is there a particular reason that it is disabled that I don't know about?
Thanks!

**Comment by mezz** [comment]
Thanks for the question!

This feature is implemented on the server because it is simple to move all the items around at once on the server.
For the client to do it, JEI has to simulate player clicks very rapidly in order to move the items around. That method is really error-prone and often buggy looking, and so I decided to avoid it.
More recently, vanilla has added this feature for the crafting table so it might be possible to implement it by hijacking their system, but I would not be able to use it for modded crafting and so it would be very limited.

In order to get this feature working on your server, you just need to have an up-to-date version of JEI on the client and on the server. Maybe something else is causing JEI to quietly crash on the server, you could post the log here and we can look.

**Comment by madisonlove21** [comment]
I had the same problem and I finally figured out how to fix it! It seemed no matter what I did JEI wouldn't work (even if it was the ONLY mod). So on the Shockbyte multicraft server go to "Files" then click "Modpack Installer". On the "Template" line click the drop down list and select your version of forge as the modpack installer. Be sure to click Apply and restart the server. Hope this helps!
