### ISSUE TITLE
[Feature Request] ItemZoom

### ISSUE THREAD

**Issue by sepsol** [mezz/JustEnoughItems#1745]
WHAT: Ability to see the blocks that you're pointing at in JEI UI, a little bit larger on the left side of the screen, since there's lots of free space there – just like what the mod '[ItemZoom](https://www.curseforge.com/minecraft/mc-mods/itemzoom)' has to offer, but for 1.14.4 (Forge).

WHY: It would be really useful for creative crafting since you could see each block in detail, especially if you don't use Minecraft's default resource pack and want to discover items in a new resource pack.

PS: ItemZoom is no longer under development, and your mod is the first popular mod in Minecraft as of today. That's why I'm asking this feature here.

**Comment by TehNut** [comment]
1. This is out of scope for JEI. 
2. ItemZoom is created by the same developer as this mod.
3. Why not ask for ItemZoom to be updated on the [ItemZoom tracker](https://github.com/mezz/ItemZoom/issues), rather than asking other developers ([myself included](https://www.curseforge.com/minecraft/mc-mods/hwyla?comment=422)) to add the feature to their own mods?

**Comment by sepsol** [comment]
Done!
