### ISSUE TITLE
Using JEI to give certain OpenComputers items throws away some of their nbt

### ISSUE THREAD

**Issue by MalkContent** [mezz/JustEnoughItems#177]
Not sure this is a JEI issue.
Examples (maybe exhausting all instances) include "EEPROM (Lua Bios)" which reverts to just an EEPROM, and the creative items for Robot, Drone and Microcontroller, which lose all their parts.

Also any non-empty floppies from OCs creative tab are missing from JEI.

**Comment by mezz** [comment]
Thanks for the report!
For the EEPROM issue, it looks like the given item has NBT but it is escaped strangely, resulting in invalid NBT. 
`{oc:data:{oc:readonly:0b,oc:eeprom:[1617 bytes],oc:label:"EEPROM (Lua BIOS)"}}`
becomes
`{oc:"data:{oc:readonly:0b,oc:eeprom:[1617 bytes],oc:label:\"EEPROM (Lua BIOS)\"}"}`
I'm not sure if this is Minecraft, OC, or JEI but I can find out.

The floppies issue may be related, I'll take a look.

**Comment by mezz** [comment]
This issue appears to be closely related to this open PR to Forge:
https://github.com/MinecraftForge/MinecraftForge/pull/2393

NBT -> String conversion is not perfectly compatible with String -> NBT.

**Comment by mezz** [comment]
The floppies are an unrelated issue. Turns out that they are synced from the server to the client, so they are not available when JEI starts. I will contact Sangar to find out a solution. As a workaround in the meantime you can reload JEI by changing any of its config settings (like cheat mode) and then it will show the floppies.
