### ISSUE TITLE
Crafting grid is not being filled in a server

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#1778]
Clicking the + to fill the crafting grid works in single player, but not in a spigot multiplayer server.
version: jei-1.14.4-6.0.0.18

**Comment by mezz** [comment]
Thanks for the report!
JEI must be installed on the server for the + button to work. I tried it on a regular Forge server with JEI installed and things are working correctly.

I did notice that the + button is missing its error tooltip in this case, I will make sure to fix that so that this situation is more clear for players.
