### ISSUE TITLE
[1.14.4] Crash on main loading screen (Sometimes) and while entering world

### ISSUE THREAD

**Issue by MrEAZL** [mezz/JustEnoughItems#1781]
its crashing my minecraft while entering the world and something in main loading screen and its rlly annoying I have SecurityCraft, Optifine, MrCrayfish Furniture Mod, there arent any shaders and I dont know any recipes with my friends btw Im using aternos and cracked launcher

**Comment by mezz** [comment]
I do not support cracked launchers. 
They are sketchy, illegal, and cause unique issues. Try with the normal launcher.

**Comment by 07Babygirl28** [comment]
Mine is also crashing on the loading screen, but I am not using a cracked version, nor am I using anything other than forge. I've been trying to get this mod to work for 1.14.4 since that game version was released, but so far no luck. I even used different versions of forge.
I have never had this problem with JEI with 1.12.2, so I don't know what to do.

What do you suggest?
