### ISSUE TITLE
Cant Play with JEI with Forge above 14.23.5.2768 (1.12.2 Version)

### ISSUE THREAD

**Issue by Rimeyx** [mezz/JustEnoughItems#1786]
https://gist.github.com/Rimeyx/97e19557924fa67cb88724bf12a91a15 
I get this error and can't launch the Game (I get a error screen in the minecraft launcher) if I select a forge version above 2768. If I select say 2816 or Above I get the Error linked above. Yet if  I select 2768 I can't play with JEI since it Requires 2816. Thanks for Listening

**Comment by mezz** [comment]
Thanks for the report!
This error log doesn't seem to involve JEI, do you still get the same crash if JEI is removed?

**Comment by rmoffat** [comment]
I've been working on a similar problem creating a 1.12.2 pack in MultiMC. When I created the instance, MultiMC recommended Forge 14.23.5.2768, so I used that version.

17 mods load fine (Tinkers', Thaumcraft, Applied Energistics, Thermal Foundation among them), but when I add JEI, I get the error message that JEI requires .2816. I upgrade Forge in MultiMC to .2816, but then game crashes while trying to launch.

If I remove JEI from the instance using .2816, the instance loads with no errors. If you want to see any logs from when the game crashes using .2816, tell me the log names/locations and I'll get them for you.

If I update Forge to the very latest version (14.23.5.2847) and put JEI back in the mod folder, the game launches and JEI is available. I just figured that out, and I'm so happy because jesus, modded Minecraft really really needs JEI :) Thanks for a great mod.
