### ISSUE TITLE
Can't Centre Search Bar

### ISSUE THREAD

**Issue by vizthex123** [mezz/JustEnoughItems#1795]
Minor issue, but for the 1.14.4 version I can't center the bar (and I prefer it centered)

According to Quark's Q button, it's becaus eI cna't use in-game configs in 1.14.; but I couldn't even find a regular config file either.

Will this ever be changed/fixed?

**Comment by mezz** [comment]
Thanks for the report!
This is because the configs are not working yet. You can follow this issue for any progress: https://github.com/mezz/JustEnoughItems/issues/1526
They are on my TODO but there is a lot going on in 1.14 that still needs attention, it is far from the only thing broken right now unfortunately.
