### ISSUE TITLE
Interface: Background looks weird

### ISSUE THREAD

**Issue by wantedkeks** [mezz/JustEnoughItems#1796]
Minecraft: 1.14.4
Forge: 28.1.90
JEI: 6.0.0.25

Hya,
after I opened my inventory and looked for a recept of an item, the light gray background of the GUI for using/crafting recepts looks buggy with crazy arrows (picture attached).

It is worth if only Forge and Jei are installed or with other mods. Gamemode and kind of GUI (inventory, chest, ...) is worth, too.

![2019-11-13_22 32 03](https://user-images.githubusercontent.com/43499536/68806619-7a821e00-0666-11ea-9b71-24350b33f86d.png)

**Comment by Tahakk** [comment]
Looks fine on my side with the data u provided. Check if it is happening with only JEI.

![2019-11-14_10 04 55](https://user-images.githubusercontent.com/25863620/68842226-59511a00-06c6-11ea-9a6e-bdb1ad7f817e.png)

**Comment by wantedkeks** [comment]
When I only use Forge and Jei, the interface changes randomly.
 During one session, the background does not change. After I restart Minecraft, the background looks different, other types of those arrows.

**Comment by binomial0** [comment]
I also have this issue, but only when using Optifine. It looks almost the same as in the original post, but the exact type of arrows varies. I tried Optifine 1.14.4 HD U F4 and F5, and they lead to the same problem. Without Optifine, the backgrounds look normal.

Forge 1.14.4-28.1.106, Optifine in mods folder

Ping @sp614x since I have no idea which mod is in the best position to fix this.
