### ISSUE TITLE
1.15.1 and 1.15.2 error

### ISSUE THREAD

**Issue by IITFA** [mezz/JustEnoughItems#1867]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

Trying to run 1.15.1 with jei-1.15.1-6.0.0.1.jar gets the following error.
https://gist.github.com/IITFA/c65f55e4fbf75119ecb1ee8e2c4017ca

This version WAS working fine yesterday. Today I tried 1.15.2, installed forge for it, but didn't like it (and had an error) so went back to 1.15.1 and installed forge-1.15.1-30.0.51-installer.jar.log for it and now this error.

I can't get the error for 1.15.2 because it locked up my system and I had to force a reboot.

EDIT: forge-1.15.1-30.0.36-installer.jar works with the mod on 1.15.1.

**Comment by MeD1aToR** [comment]
Hi
I also have this problem on version 1.15.1 and made a build on forge version 30.0.51 and it works fine! Also I added update to latest mapping 20200217 version by @stragulus
Since there is no separate branch for [1.15.1](/MeD1aToR/JustEnoughItems/tree/1.15.1), I don’t know how to make the pull request.
Perhaps this issue will be noticed and @mezz will add the updated version to a separate branch or upload a updated release on curseforge

med1ator@69d51f6232bb52bf92b647e1364ceff6baae36a1

**Comment by pupnewfster** [comment]
I don't think this is actually an issue, in fact when I was submitting the PR to update to 1.15.2, I asked mezz if I should make it so the version check allows for the final version of 1.15.1 (which had the breaking changes), or just start it at 1.15.2, and he said to just put it at 1.15.2 as forge 1.15 did not have an RB yet so he saw no reason in having it work with the final singular version of 1.15.1.

Though personally I don't see why you would still be trying to use 1.15.1... when 1.15.2 is out, especially now that 1.15.2 has an RB.

**Comment by MeD1aToR** [comment]
Just someone else is playing on 1.15.1 and wants to download a working version of JEI with the latest version of Forge. And I tried to make it possible)
Anyway, now JEI works for me as I want on the latest version of Forge)
