### ISSUE TITLE
server down when i use Just enough items 

### ISSUE THREAD

**Issue by Sarmus12** [mezz/JustEnoughItems#1903]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by MelanX** [comment]
Are you kidding? You just give the issue a title and nothing else? No wait: you are too lazy to delete the template which says what you should do for reporting stuff?
You need to provide a crash log if anything crashes. You should give the versions of Forge, Minecraft and the mod! Otherwise no one will help you.
