### ISSUE TITLE
Cheatmode management

### ISSUE THREAD

**Issue by Elrol** [mezz/JustEnoughItems#1904]
I have been making a mod for a few months that adds permissions, ranks, and lots of stuff to modded mc. Some testers are reporting that they can still enable cheatmode. I'm assuming that enabling hai cheats checks for permision level or something, but I was hoping that there could be a way for it to hooked to a cmd or something. 

Like having the button run a cmd that is like /jeicheats or what not. Then, my mod would be able to disallow that command. 

I'm not sure if there is anyway to give perms to cheatmode as it is currently, but if there is any way for us to get something set up, I would be extremely grateful

**Comment by TechnicianLP** [comment]
As can be seen in https://github.com/mezz/JustEnoughItems/blob/1.15/src/main/java/mezz/jei/util/CommandUtilServer.java#L71
If the user is allowed to use /give (or if /give is not a coomand then if the player is op) or if the player is in creative mode he is allowed to use cheatmode.
If you deny the users the permission to use /give (or creative) you are automatically denying cheat mode, making that logic independent would not prevent the player from cheating in items as they have still permission to use /give or are in creative. 
If you want something more specific, state it

**Comment by Elrol** [comment]
Maybe something like a server config option to disable it. My mod adds a
permission system that, as far as Minecraft is concerned, makes everyone
op. But then denies command usage based on permissions and ranks. So if
they are using my mod everyone can use cheatmode. Atm the only way that I
could fix this is to replace that static class, or intercept the packet
sent to the server and change what it sends back.

**Comment by TechnicianLP** [comment]
Which means you are cancelling CommandEvents instead of doing a proper Permissions implementation - look into using the https://mcforge.readthedocs.io/en/latest/utilities/permissionapi/
in combination with replacing the CommandNode#requirement Predicates of all commands with Permission checks instead of OP-Level Checks (likely removing the need for OP rights as many  mods depend on OP meaning admin)
If the requirement Predicate for the /give CommandNode returns false the Player cannot use cheatmode simple as that (unless they are in creative)
It is (very likely) not in the scope of JEI to directly support fully fledged Permission systems though
Having a config to disable cheatmode seems pointless if cheating via /give and creative is still allowed

**Comment by Elrol** [comment]
From what I gathered on the forge discord the permission API is depreciated
but I think that we will be able to fix it, another dev just offered some
help and is making progress. Sorry for the bother.

**Comment by Elrol** [comment]
Problem fixed.

**Comment by no82133** [comment]
How was this problem fixed? @Elrol
