### ISSUE TITLE
i need help. i tried to play on the mod pack "Project Ozone 3 A New Way Forward" from Curse Forge and when i tried opening it (i tried 4 times times)  it wrote me  "The game crashed whilst there was a severe problem during mod loading that has caused the game to fail Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)" does anyone know how to fix it ?

### ISSUE THREAD

**Issue by EtWizard** [mezz/JustEnoughItems#1951]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by Hinara** [comment]
Please reduce your title it makes it unreadable.
your description can be something like `Crash  on startup with a JEI exception`
And USE the description part to DESCRIBE your problem, instead of letting the issues default template asking you to check some points.

Sorry, for caps lock but it's really, totally unreadable. Your title take 8 LINES on my screen !!
If you want more help try to provide the error with the stacktrace part, to get a bit more context,
Also can you give the version of JEI that your current version of the modpack is running.
