### ISSUE TITLE
Repeat events disabled in creative tabs.

### ISSUE THREAD

**Issue by Darkhax** [mezz/JustEnoughItems#199]
When JEI is installed, repeat events seem to be disabled in the creative tabs. For example, you can't hold down the back space key to delete all text in the search bar.

**Comment by BlayTheNinth** [comment]
It's not only on the creative tab, it happens to any GuiContainer. I have a large textbox in one of my mods and enable repeat events in initGui, like it's normally done in Vanilla code. However, on mouse click JEI's event handler goes 'nope' and disables them again just because its own textbox isn't focused.

https://github.com/mezz/JustEnoughItems/blob/1.10/src/main/java/mezz/jei/input/GuiTextFieldFilter.java#L99

As a workaround I now have to listen to mouse clicks myself and re-enable it right after. JEI should probably store the initial state of key repeat from the InitGuiEvent and only disable them if they weren't enabled to begin with.
