### ISSUE TITLE
API Request: A way to provide dynamic recipes based on item being searched for

### ISSUE THREAD

**Issue by bdew** [mezz/JustEnoughItems#203]
Maybe i'm missing something but it looks like currently all recipes need to be registered with actual itemstacks on startup.

There are many things that are not feasible to create a recipe instance for every possible variation because it would either spam the user with repetitive information or simply not possible due to combinatorial explosion of variations (e.g. genetic template + sample recipes in Gendustry would probably take more space than the observable universe).

My suggestion would be to have some kind of recipe provider interface that mods can register, and will provide getRecipeCategoriesWithInput/Output and getRecipesWithInput/Output implementations that generate recipes based on the queried item at runtime. 

RecipeRegistry will call those providers when it's queried and merge any recipes they return with the static list it gets from RecipeMap.

**Comment by way2muchnoise** [comment]
There actually is a `IRecipeWrapper` to do all the magic. I do a lot of magic things with in [JustEnoughResources](https://github.com/way2muchnoise/JustEnoughResources/tree/master/src/main/java/jeresources/jei). Unless I completely misunderstood what you wanted to do.

**Comment by bdew** [comment]
I want to generate a list of recipes to show when a user looks up recipes/usages for specific item.

For example in my Simple Covers i have >100 materials and 15 different shapes of microblocks.

When a user wants to see how to use a saw i want to show him some example recipes with a single material type, not all possible combinations (which would be in the thousands).

But when a user wants to know how to get some specific - i want to show the exact recipe that produces it.

As i said, maybe i'm missing something but i don't see how to get that with the current API.

**Comment by way2muchnoise** [comment]
I see where you want to go.

The thing that comes to mind is to make a dummy recipe or wrapper where the saw is the input and there is no output. That recipe will show on requesting usage of the saw. Although that would require to have it setup so that in the other recipes there is no input for the saw.
I think this would work with the current implementation of the API and wouldn't require that much work on your end.

**Comment by mezz** [comment]
I think the solution to this is for me to pass the "focused" input and output item to the `IRecipeCategory.setRecipe`. Then the recipe can display differently depending on context.
I'm against adding a recipe provider interface because it would kill search performance like in NEI.

**Comment by bdew** [comment]
I could live with that, but it think it's pretty backwards. 

I guess i would need to register all my NBT tags to be ignored so the recipe gets picked up to begin with.

I would also not be able to use the default categories which is annoying as those recipes are for normal crafting tables.

And there will probably need to some kind of isRecipeValidForInput/Output check before setRecipe so that recipes can be skipped if they are not applicable.

To be honest i'm not sure why performance is an issue. It's all client side and gets called once in a blue moon. Even if going through all the providers takes a second or two - which it shouldn't if they are well written - it's not really an issue worth such loss of functionality compared to NEI. IMHO.

Edit: You could also make providers register for specific items, so you wouldn't have to go through them only when recipe/usage is looked up for that item.

**Comment by HenryLoenwind** [comment]
I'm not sure what eats more performance, registering a recipe that has every single item that is in the game in its input list, or asking a handler if it can handle an item it runtime.

I can say the the first one take so long that people cannot connect to servers anymore because they time out. Already tried it for Ender IO's Painting Machine.

I haven't tried the third option of registering one recipe for each item. That'd be simpler (for once I wouldn't need to fish the focused item out if JEI's internals) but the recipe page for the painting machine would be so completely unhelpful---no longer one recipe for each paintable item but multiply that with the number of items ingame...

**Comment by mezz** [comment]
> I'm not sure what eats more performance, registering a recipe that has every single item that is in the game in its input list, or asking a handler if it can handle an item it runtime.

The former is a memory hog, but it's much faster since I'm looking up items with a giant map instead of asking each handler. NEI would often have a delay when looking up recipes in big packs and I want JEI to feel instant, less than 20ms ideally.

I'm going to start working on this in earnest today and see what works the best. I'm testing against Forestry since its "fireproofing" recipes seem like a good candidate for this feature.

**Comment by HenryLoenwind** [comment]
It may be faster at runtime, but that won't help those people that get kicked off servers at connect for timeouts. You can try it with Ender IO, there's a config switch to enable this.

**Comment by AEnterprise** [comment]
for preventing timeouts can't this just be done an a different thread?

**Comment by mezz** [comment]
I understand the current workarounds are not good or performant, I'm working on a solution.

**Comment by HenryLoenwind** [comment]
TBH, I don't know those fireproofing recipes, but I expect them to be "anything(flammable==true) + X = fireproof_anything". In that case, that's exactly the use case I have, too. "anything(solid=true) + anything(block instanceof ISolidBlockPaintable) = painted_anything" "anything(solid=false) + anything(block instanceof INonSolidBlockPaintable) = painted_anything" "anything(particleTexture=yes) + anything(block instanceof ITexturePaintable) = painted_anything" ... (~30 recipes if I remember correctly)

**Comment by AEnterprise** [comment]
maybe a new recipe category type seperate from what we have now? all recipes in that category accept all items or all blocks or all blocks and items (3 variants) with a handler that gives the output based on the itemstack?

**Comment by HenryLoenwind** [comment]
I don't think it really matters which way it is implemented. The problem is how much time those handlers take to do their job. It only takes one mod that registers a handler that does Thread.sleep(1*second) to bring JEI down to an unusable speed. And other than putting a hard and short timeout on those calls (no alarm() in Java, is there? ;) ), I have no idea how to enforce them being fast.

One thing that might help would be to split the isInput(item)/isOutput(item) from the createRecipe(). That may encourage people to not actually do expensive stuff inside the checker methods...

**Comment by AEnterprise** [comment]
enforcing is impossible but maybe a config option that makes JEI time the handlers and log it so the cullputs can be found?

**Comment by HenryLoenwind** [comment]
just time them anyway and put big angry red text over their recipe telling the user to contact the mod author about their slow mod? **veg**

**Comment by mezz** [comment]
Please just let me implement it -_-
This issue has been open for months and I'm going to take my time to get it correct based on actual implementation.
I mean clearly I will thread it and spend billions of cycles detecting slow mods and delete your computer and nuke Australia and rename it ForgeRecipes, it's the only way.

**Comment by HenryLoenwind** [comment]
And while you're at it, make it capability-based, will you ;)

**Comment by AEnterprise** [comment]
alright sorry @mezz just trying to help, i'll shut up now

**Comment by bdew** [comment]
Any news on this?

I started porting NEI addons and the NEI stuff in gendustry to JEI and i see no way to make it work with the current system...

**Comment by mezz** [comment]
The `IGuiItemStackGroup` passed to the recipe category now has `getFocus()` so you can see what's looked up. It's a workaround but it should make what you want to do possible now.

NBT is now ignored by default, if it has meaning for subtypes you can register an interpreter with the `ISubtypeRegistry`.

**Comment by bdew** [comment]
ISubtypeRegistry is not useful in my case because it's not context aware. For example in bees in some recipes i care about the species allele while in others i care about speed or whatever. Maybe if it had some kind of wildcard matching it would be useful but there's nothing like that.

getFocus doesn't really gives what's needed either.

Example use cases:
1. User presses R on a common drone. I want to show a mutation recipe for each combinations that produce a common drone.
2. User presses R on a sample of a "fast" speed allele: I want to show a sampler recipe for each species that has that allele in it's default template.
3. User presses U on a common drone. I want to show a sampler recipe for each allele. I also want to show a mutation recipe for every combination of common+whatever.

**Comment by mezz** [comment]
Status report:
I finally finished the giant refactor for #282, so I'm ready to tackle this one. I didn't want to do this and then rewrite it to support the generalized ingredients. Sorry for the long wait so far.

**Comment by mezz** [comment]
Alright this gives complete control (the same that JEI has) over looking up recipes.
Let me know if you need me to expose any internal utilities to make things easier to implement.

Anyone reading this who will implement one of these: be performant, the UI needs to be instantly responsive. NEI got pretty slow in its later days with big packs. If you write especially slow plugins it will log to the console.

**Comment by bdew** [comment]
Just wanted to say thanks for this. Just rewrote JEI integration in simple covers to use the plugin system and it's so much better. Now to port NEI stuff from gendustry...

A small idea for performance: Add another method to IRecipeRegistryPlugin for a plugin to decide if it has anything useful to do with a request based on the Focus. Such a check can usually be pretty fast and if it returns false you can ignore that plugin for the rest of the handling. I imagine for most requests the number of plugins that have anything to do will be 1-2.
