### ISSUE TITLE
Large FPS Drops on Inventory Screen

### ISSUE THREAD

**Issue by aditk3** [mezz/JustEnoughItems#2030]
I am suffering from severe frame drops when I open my inventory (becomes almost impossible to use). I have my GUI scale set to Normal on a 32" monitor as that's what suits me. I feel like the number of items on my inventory screen (due to JEI added many more items to my inventory page) is causing these issues, but I can't figure out how to fix it. If there's a toggle button for the JEI overlay, I wasn't able to find it as that would be the ideal solution for me.
![2020-08-08_23 22 12](https://user-images.githubusercontent.com/55118440/89716897-92f15000-d9ce-11ea-8950-382ccdd1b4b8.png)

**Comment by mezz** [comment]
Ctrl-O is the default hotkey to toggle the JEI overlay, you can check in the Minecraft controls menu.

The rendering is optimized compared to a regular inventory, but with this many items you're definitely going to see slowdowns.
There is also a config option to reduce the max width of JEI, so that it displays fewer items.

**Comment by Pytness** [comment]
It seems like the 2d item renderer provided by forge takes around ~0.035ms per item rendered, while the 3d render takes ~0.015ms per item (somehow faster than the 2d renderer). So rendering 37*30=1110 items is going to take ~0.03s per frame, lowering your fps down to ~30.

Keeping the number of displayed items below 550 may be enough to give you around 60fps.

Maybe this could be fixed by creating a custom renderer for the items... or just hope that forge fixes it.

**Comment by zayaraq** [comment]
I recently updated to MC1.16.5 and I am experiencing the same issue. However it becomes literally unusable with 8 fps or so and I get the same prboblem to a lesser extent when just filling a chest with enchanted items even when not using JEI. This did not happen in 1.12. There you opened your inventory, the game froze for a few seconds and after that it was smooth even with a lot of items on display with JEI. This is just a weird and annoying bug and I hope it'll be fixed soon, by whoever has the power to do so :)

**Comment by mezz** [comment]
Please try setting the JEI config to display fewer columns of items at once.
in `jei-client.toml`:
```
	#Max number of columns shown
	#Range: 4 ~ 100
	MaxColumns = 9
```
