### ISSUE TITLE
JEI has been hacked (there is a Go Vote Screen)

### ISSUE THREAD

**Issue by BaccarWozat** [mezz/JustEnoughItems#2093]
Some idiot has hacked the mod and put political spam in it. I would be more careful accepting pull requests in future.

![2020-09-20_07 09 20](https://user-images.githubusercontent.com/8357501/93711085-eba92200-fb10-11ea-8c21-4c59b32daf31.png)

**Comment by l-Luna** [comment]
do you understand how git works

**Comment by ChloeDawn** [comment]
This is an intentional addition, JEI has not been hacked. Go and vote ❤️

**Comment by Vazkii** [comment]
![image](https://user-images.githubusercontent.com/1794735/93711420-21b4c900-fb46-11ea-856f-c440c69c4e0d.png)

**Comment by tomdodd4598** [comment]
I've been trying to do the calculations, but I'm running out of paper and my pencil grows blunt. Gonna have to go to W H Smiths to get some more, but so far a mixture of lemmas and half-proofs suggests tentatively that one can buy a keyboard, or indeed plug one in if you already have one lying around somewhere, and hit the little 'Esc' button to move onto the game.

Again, this is early results, don't go to the media about it yet and keep all evidence for and against this ongoing work objective as best you can. Thanks for your patience!

**Comment by cerovest** [comment]
just vote

**Comment by DoomSquirter** [comment]
how bout we do both?  we all go vote, AND we keep the political bullshit out of minecraft, hmm?

**Comment by ghost** [comment]
as an american, here's a fun thing i suggest doing;

don't remove messages telling my people to vote :V

**Comment by CammiePone** [comment]
as an American, someone who hates going places, and someone who dislikes the whole political system:

just go vote if you're old enough. Like, geez my dude, it's a one-time screen, just get over it if you don't want to see it. The only people complaining about politics in games always seems to be the ones who don't constantly live in fear of their rights being stripped from them due to centuries old bigotry. If that's not you, then you should be advocating for this stuff. If that is you, then you should still be advocating for this stuff. It doesn't end at politics, it encompasses people's lives and livelihoods, and it doesn't matter who you are, you should care about protecting those.

**Comment by DaMatrix** [comment]
i don't understand the point of these things. every single time, 99% of the reactions are either people being triggered about it being there, or people insisting it's not a big deal.

of the remaining 1%, how many are going to be starting up their minecraft modpack, see this popup and go "oh yeah, i need to vote! nobody has reminded me to do that yet, and this reminder from my block game mod has totally motivated me to get off my lazy ass and go do that" vs "i wasn't planning on voting before, and this reminder just interrupted me while i was about to start playing with my virtual legos, so i'm still not gonna vote. lol"?

how many people (who wouldn't have voted otherwise) are really going to see this and go vote? probably nobody. how many people are going to be triggered about it? a lot. how many people are going to see the people getting triggered about it and get triggered back at them? also a lot. what is the outcome that is in all circumstances, practically 100% guaranteed? the result of the vote doesn't change at all, but you managed to get a bunch of people yelling at each other.

real-world politics do not belong in a video game. period.

**Comment by DoomSquirter** [comment]
it's the literal definition of an advertisement, regardless of any good intentions or not.  I don't want my minority report in my minecraft tyvm.  I wanna build a house out of blocks, feed my pet cat blocky fish, ride a blocky horse and fuck a blocky pig.  and I don't wanna be interupted doing any of those things by any ads.

**Comment by ConnieCommie** [comment]
unless you vote in the pedophile the other pedophile will win

**Comment by adrwa** [comment]
While I find the go vote screen obnoxious & pointless, I believe overall it is fine, however, I'd say that doing 
https://github.com/mezz/JustEnoughItems/blob/713f6776479e4fda633ed324388c10174ca1f5bb/src/main/java/mezz/jei/vote/GoVotePlugin.java#L28-L36 where it tells you to vote for a specific candidate, is beyond stupid

**Comment by l-Luna** [comment]
> unless you vote in the pedophile the other pedophile will win, besides, everyone knows that the constitution can never be overruled just ask the folks at gitmo  

one pedo who's halfway through breaking your democracy vs another who hasn't started, and also has somewhat better policies

> it's the literal definition of an advertisement, regardless of any good intentions or not. I don't want my minority report in my minecraft tyvm. I wanna build a house out of blocks, feed my pet cat blocky fish, ride a blocky horse and fuck a blocky pig. and I don't wanna be interupted doing any of those things by any ads.  

you can do that without JEI if you like.  you're the one choosing to use this, and you are entitled to nothing. this mod was not made for you to be able to it ore the world around you like this.

> real-world politics do not belong in a video game. period.

wait until you hear about basically every other video game  
or even just Minecraft china

**Comment by ConnieCommie** [comment]
if you think trump's breaking the democracy you are legit fucking braindead. it's working as intended, a rich white pedophile is in charge

do you like rapists? are you supporting biden because you support rape? you support having sex with children, no?

**Comment by lineargraph** [comment]
> the pedo with the better politics

at least you are admitting you're a retard.

**Comment by DaMatrix** [comment]
> wait until you hear about basically every other video game

did i say that it was acceptable in any other video game? it's just as bad anywhere else, but we aren't talking about other video games. we're talking about minecraft - or rather a specific minecraft mod.<

> if you think trump's breaking the democracy you are...

can we stay on-topic pls, this issue is related to a vote reminder popup, not a comparison of the various presidential candidates

**Comment by ConnieCommie** [comment]
no, it's acceptable in video games and can be done very well: see disco elysium. my main problem is a popup telling you to vote in an election that literally does not matter

**Comment by lineargraph** [comment]
>can we stay on-topic pls, this issue is related to a vote reminder popup, not a comparison of the various presidential candidates 

well it was until there is actually code in here supporting one of the two candidate explicitely

**Comment by ConnieCommie** [comment]
also, "minecraft china" - trump and biden both have rape accusations. Xi doesn't.

**Comment by lineargraph** [comment]
Btw is this regional or do i also get this as EU citizen?

Edit: yes it is. Thanks :)

**Comment by DaMatrix** [comment]
it's based on the default system locale. you'll only get it if your system language is set to `*_US`

or more specifically, one of:
- `en_US`
- `es_US`
- `zh_US`
- `tl_US`
- `vi_US`
- `fr_US`

**Comment by quat1024** [comment]
Hoes mad

**Comment by ConnieCommie** [comment]
are the 8 woman who accused biden also hoes who are mad
i know you wouldn't say that about the women who accused trump

**Comment by shedaniel** [comment]
You telling us to vote is **fine**, however, the following is **not**.

![image](https://user-images.githubusercontent.com/34910653/93713973-096a9b80-fb92-11ea-8274-4b6082785748.png)

__________________________________
The code responsible for this is at: 
https://github.com/mezz/JustEnoughItems/blob/713f6776479e4fda633ed324388c10174ca1f5bb/src/main/java/mezz/jei/vote/GoVotePlugin.java#L30-L33

**Comment by ConnieCommie** [comment]
oh that's my main problem too. having an advertisement for a **rapist** in your mod isn't fine - biden or trump

**Comment by mezz** [comment]
Thanks for the report!
You can rest assured that JEI has not been hacked. The commit to add the "Go Vote" message is from me and intentional. I cryptographically sign all my commits so that you can verify it's actually from me by viewing the commit here on GitHub:
<img width="261" alt="Screen Shot 2020-09-20 at 10 43 16 AM" src="https://user-images.githubusercontent.com/916092/93718016-39805300-fb2e-11ea-8ee5-202c7979376c.png">

I hid the disturbing conspiracy-probably-chinese-nationalist-propoganda comments in the thread from ConnieCommie, that was weird and not welcome.

If you would like to talk about the political support for [Joe Biden](https://joebiden.com/), keep in mind that's *much* less visible and more of an easter-egg. I think that's a bit off topic for this thread and Github isn't the best place for it. We can take the discussion to the best platform ever created for political debate (as endorsed by our current president and leader of the free world): Twitter.
https://twitter.com/mezz_mc/status/1307503088245202944

**Comment by CammiePone** [comment]
I'm just going to leave this here

![image](https://user-images.githubusercontent.com/16853086/93718348-8aea0b80-fb49-11ea-9353-f54086ca6979.png)

**Comment by Martmists-GH** [comment]
> it's based on the default system locale. you'll only get it if your system language is set to `*_US`
> 
> or more specifically, one of:
> 
> * `en_US`
> * `es_US`
> * `zh_US`
> * `tl_US`
> * `vi_US`
> * `fr_US`

This is such a stupid idea. Putting aside that telling people to vote for a specific person is generally a bad idea or even that politics ideally shouldn't be discussed in games, many users that prefer to have their language set to english use en_US, because this also avoids contracting special characters. Locale should not be an indicator of what country someone resides in. Instead, something as simple as a geoip check or similar could be used, with the caveat that people using a VPN are caught in this too, but that is something users with a VPN often expect. 

I'd also like to note that claiming Twitter is a good platform for discussion is an awful statement looking at the history of people simply shouting at each other with zero interest of listening. (Case in point being the current POTUS)

**Comment by mezz** [comment]
This is based on the system locale, not the game locale.
I can add a geoip check to make it more accurate.
If someone is caught by this with a VPN they can hit ESC as easily as anyone else, sorry if you see it by accident.

Twitter is an awful platform but if people want to shout then that's the place.
Actual issues and improvements like you've highlighted are welcome here.

**Comment by Martmists-GH** [comment]
A decent reference for IP-based checks can be found in Patchouli's source code, from a quick search: [Patchouli](https://github.com/Vazkii/Patchouli/blob/master/src/main/java/vazkii/patchouli/client/gui/GoVoteHandler.java)

**Comment by mezz** [comment]
I have implemented the geo-ip check to bring this more in-line with the other mods.

**Comment by Skizzles** [comment]
@mezz Honestly keep politics out of the mod community and mc community as a whole. People like you are the problem, and you even used it to put support for Joe Biden. Consider your mod uninstalled.

**Comment by mDiyo** [comment]
This message constitutes a full-screen advertisement and spam in a game that has none of those things. Regardless of the message, this is the worst way to communicate with your users. I can tell you from personal experience that you do NOT want this in your mod.

**Comment by mezz** [comment]
Thanks for the advice but I’m not sure I agree with the premise.

**Comment by mDiyo** [comment]
How can we trust you not to put other advertisements in the game? What's stopping you from throwing up banner ads for Raid: Shadow Legends, or putting in a litecoin miner somewhere?

The issue here is trust. You do not want to burn what inherent trust you have with your users. Take it out before anyone who doesn't want the real world in their block game drops Just Enough Items like a rock.

**Comment by mezz** [comment]
I posted some more context here:

https://github.com/mezz/JustEnoughItems/commit/3fb4b9aea9e4b958b1a2f70202713df1e4b412c4#r42521557

These are truly exceptional circumstances and based on how I have run the mod for years, I hope I have built up enough of your trust that you will look for the reasoning and ask for justification in good faith instead of assuming the worst of my judgement.

**Comment by mDiyo** [comment]
Before today I didn't know anything about you other than that you wrote this mod, and that the mod is useful. Now I know one more thing: I do not trust you to keep your mod clean of the outside world, ads, or other scummy practices.

Consider this final notice that JEI will not be supported by me. Real life does not belong in a game where we get to build cool things out of floating blocks.

**Comment by TelepathicGrunt** [comment]
@mDiyo Final notice? You do understand no one really cares about a single user not using a mod? That's like going to a store and shouting "I won't shop here anymore!" despite the fact that literally nothing will change if that customer never comes back. Zero impact.

Please stop dramatizing yourself.  Please go vote or take off JEI. No one is forcing you to do anything and you have no influence over what modders do in their FREE mod in their free time.

**Comment by Mysticpasta1** [comment]
So will this go vote thing be removed after the election if so I think we can put up with it for 2 months. If not then there is a problem seeing it after the election is over and someone has won!

**Comment by CursedFlames** [comment]
`!isAfterElectionDay()`
@Mysticpasta1 looks like there's a check for it.

**Comment by Vazkii** [comment]
@mDiyo bye no one will miss you

**Comment by jamierocks** [comment]
![Screenshot_20200921_113526](https://user-images.githubusercontent.com/5103549/93757440-ad8a2c00-fbfe-11ea-82c4-6dd6a9a31f7c.png)

Would it be possible to not create the marker file in countries that aren't the USA?

**Comment by zabi94** [comment]
> How can we trust you not to put other advertisements in the game? What's stopping you from throwing up banner ads for Raid: Shadow Legends, or putting in a litecoin miner somewhere?

Ah yes the good ol' [slippery slope](https://en.m.wikipedia.org/wiki/Slippery_slope), lovely.

**Comment by Ueaj-Kerman** [comment]
> How can we trust you not to put other advertisements in the game? What's stopping you from throwing up banner ads for Raid: Shadow Legends, or putting in a litecoin miner somewhere?

hey what's wrong with that

**Comment by Vazkii** [comment]
> ![Screenshot_20200921_113526](https://user-images.githubusercontent.com/5103549/93757440-ad8a2c00-fbfe-11ea-82c4-6dd6a9a31f7c.png)
> 
> Would it be possible to not create the marker file in countries that aren't the USA?

Hi, this was my decision. 

Creating the marker file expedites the process of loading the screen. Since the file is there we don't have to actually run the check of whether you're in the US or not. Considering many mods have this code, it's a lot faster to check the file existence than have each mod spin their own thread to check your location.

**Comment by jamierocks** [comment]
> Since the file is there we don't have to actually run the check of whether you're in the US or not.

That isn't the case with [JEI](https://github.com/mezz/JustEnoughItems/blob/4f83a971e91beb97547bb3fab58a7fa2a7d42f6e/src/main/java/mezz/jei/vote/GoVoteHandler.java#L94), though it does seem that [Patchouli short-circuits](https://github.com/Vazkii/Patchouli/blob/bdbd2b1706a9e716980b892105521ce2bdc99a7c/src/main/java/vazkii/patchouli/client/gui/GoVoteHandler.java#L90) - that change should be made here.

**Comment by Vazkii** [comment]
I recommend you open that as a separate issue.

**Comment by Waisse** [comment]
Adding a reminder to vote is one thing, but chilling your candidate of choice is another. Remove the Biden item.

**Comment by jamierocks** [comment]
> Adding a reminder to vote is one thing, but chilling your candidate of choice is another. Remove the Biden item.

See https://github.com/mezz/JustEnoughItems/commit/3fb4b9aea9e4b958b1a2f70202713df1e4b412c4#r42522566 for some context on this. I would still rather go the route of educating players than pushing a single candidate on them, allow people to come to their own (educated) decision - but this is mezz's mod, and I figure he is from the USofA.

**Comment by Waisse** [comment]
> 
> 
> > Adding a reminder to vote is one thing, but chilling your candidate of choice is another. Remove the Biden item.
> 
> See [3fb4b9a#r42522566](https://github.com/mezz/JustEnoughItems/commit/3fb4b9aea9e4b958b1a2f70202713df1e4b412c4#r42522566) for some context on this. I would still rather go the route of educating players than pushing a single candidate on them, allow people to come to their own (educated) decision - but this is mezz's mod, and I figure he is from the USofA.

I don't want context, I want impartiality.

**Comment by Wazubaba** [comment]
You know, it's funny. If I wasn't so poor I'd be willing to bet money that if a Trump-supporting mod author did this the same people in this thread defending this nonsense here would be there screaming foul there with a complete lack of self-awareness, and yet likely most of the people screaming foul here currently would still be screaming foul there as well. Note the difference.

**Comment by CammiePone** [comment]
> 
> 
> You know, it's funny. If I wasn't so poor I'd be willing to bet money that if a Trump-supporting mod author did this the same people in this thread defending this nonsense here would be there screaming foul there with a complete lack of self-awareness, and yet likely most of the people screaming foul here currently would still be screaming foul there as well. Note the difference.

The difference is Trump wants, and has been, stripping rights away from people. While Biden still sucks, at least we'll survive him. Trump? Good chance more people will be rounded up into concentration camps. Complaining about "uh muh escape from reality" when there are people that don't have that luxury just shows how priviliged you are.

**Comment by Wazubaba** [comment]
No. This has nothing to do with Trump. This has nothing to do with Biden. Nobody wants to deal with all of you folks who have to inject politics into every fathomable thing you touch - regardless of which side of the same coin you guys are on.

We want to enjoy minecraft and forget about our worries for just a few hours before having to clock in to our jobs that are driving us to an early grave, or schools that aren't teaching us anything that can actually help us as adults.

**Comment by CammiePone** [comment]
> Complaining about "uh muh escape from reality" when there are people that don't have that luxury just shows how priviliged you are.

Thank you for literally proving my point.

**Comment by Wazubaba** [comment]
And thank you for proving mine.

**Comment by Thaums** [comment]
I don't normally vote but seeing this convinced me to vote Trump. Thanks mezz!!!

**Comment by mezz** [comment]
For every bad faith argument in here I’ll donate another $1 to Jamie Harrison’s campaign in South Carolina lol
![C4108F9A-3E9E-4327-A32A-8D4A84B57746](https://user-images.githubusercontent.com/916092/95819708-7548ab80-0cdb-11eb-9c85-b68eb988a368.jpeg)

**Comment by Wazubaba** [comment]
I mean you can call reasonable points of view and pleas for what used to pass as common sense back when the Earth was still cooling whatever you please, it doesn't make this creepy push to inject politics everywhere any less cultish. You folks are no better than Trump supporters. In fact in some ways you are actually slightly worse, as I don't see Trump supports shoving their political nonsense into every fathomable facet of life they can touch. Sure they have a **lot** of bad eggs, but you guys do too. Please chip in another $50 for this comment. In fact, how much money do you have? Let's get all of it donated to this person I have neither heard nor understand the relevance of! At the end of the day, you guys are still in a yin-yang relationship with the Trump folks - constantly playing off one another in an endless spiral of pure foolishness.

**Comment by mezz** [comment]
If you are disconnected from this issue and want to understand why I’d make an annoying vote screen, please read my explanation here, https://github.com/mezz/JustEnoughItems/commit/3fb4b9aea9e4b958b1a2f70202713df1e4b412c4#r42522566

**Comment by Wazubaba** [comment]
I don't care about the talking points you've had handed to you any more than I care about the talking points the Trump folk's have had handed to them - your politics are irrelevant to me and the rest of the world. Why can't you understand this? (Make it another $50 please :D)

You are still the ones at the end of the day injecting your nonsense into mods for minecraft, three relatively common ones at that. I have yet to see a Trump supporter that has done it (If you can direct me to one's repo I will personally ask them to remove it there as well!)

**Comment by mezz** [comment]
If you don’t want to read my explanation, what good is it replying to you? Your point of view is clear and defensible but you’re not the only person to make that point, I considered it and replied in the link. What else is there for me to do? Should I copy paste it here?

**Comment by Wazubaba** [comment]
I did read it. I said I don't care about your talking points that are entirely drenched in political bias. Nor do most reasonable people, in fact. You are free to believe Trump is Mega Hitler Satan till the cows come home, and I'm sure they think the same of Biden. The point is that real-world politics don't belong in a video game.

**Comment by mezz** [comment]
![DFCA54C3-9247-464A-A5EC-6C7A017237C6](https://user-images.githubusercontent.com/916092/95823005-c065bd00-0ce1-11eb-99b1-45d6c53e68b4.jpeg)

**Comment by mezz** [comment]
I’ll humor you on the donation but you aren’t making a good case by ignoring my response, so I’m not interested in continuing this conversation.

**Comment by Wazubaba** [comment]
I'm not ignoring your response, I'm saying that just as you have all kinds of little barbs of varying amounts of truth towards random nonsense Trump has said/done so to do they against Biden and that slowly corrupting what should be a peaceful place we can all put our real world problems and disagreements aside in and get along with one another for a little while over it is a terrible thing. You and others doing this are bringing all of the parts of life that have driven each of us to the act of escapism that is playing Minecraft in the first place into it, and then trying to act like you have the moral high-ground. Do you see why I and so many others are starting to get disturbed by this? To call you and others out on this? All you are doing is creating a wedge in a community where there was none prior - sewing division where once was unity. It's sick, shameful, and paints a rather dark picture of the future. If you want to continue, it's your choice. If you want to jam your fingers in your ears because I refuse to accept either side's equivalent of a He Said She Said argument as a reason why more things have to be corrupted by politics then that's also your choice. It's your mod and freedom to do so with. I just hope one day you see reason.

**Comment by mezz** [comment]
Raising awareness of voting to do our part to counteract voter suppression takes precedence over the fuzzy feeling you get when playing modded Minecraft, sorry.
You can argue red vs blue but this is about our democratic system, the fact is that it’s broken and being exploited. If someone is telling the truth and backed by evidence, it’s not somehow equal to someone spinning a pile of inconsistent lies out of nowhere. We’re pretty screwed because people can’t seem to tell the difference. At least vote

**Comment by Wazubaba** [comment]
So you are going to go with the tired "You are entitled for wanting to do X" argument? Look, if voter suppression is really happening, then what good would voting do in the first place? What will your activism accomplish? All you are doing is pissing off people who have no control over these matters and who have never once wronged you, which last I checked would be trolling if it weren't so insidious in nature given this starting to become a trend. I mean this argument is literally on par with telling people to turn on an electric light to fight against the power being out.

On top of this, a large quantity of the player-base of Minecraft are children, so that's an even bigger example of why your current attempt at activism is greatly flawed, as they cannot vote and should not have to be forced into this nightmare world you and your opponents seem to be trapped in and radicalizing yourselves ever closer towards straight-up war with one another over.

You also add an item to the game that advertises your specific candidate. It's not just the splash screen. You are not making a message to raise awareness here - you are trying to shove your politics into player's faces and deflect it as being just "raising awareness".


If you **really** do believe the world is in peril and that you are capable of doing something to combat the government as a whole, then all I can advise is that rather than this weak-handed and pointless activism just for the sake of feeling good about yourself, you should cancel that $100 you just gave to someone far richer than you and instead use it to actually try to do some local activism away from the computer to raise awareness about voting and whichever brand of hysteria you choose to subscribe to that day. That would accomplish far more than this. In fact, consider also helping out at a local food pantry or shelter. I promise that by doing these things you will have more effect on the world around you than by whatever it is you think you are doing here.

**Comment by mezz** [comment]
I'm not asking for your unsolicited advice, maybe instead of lecturing me you could do something good as well.

Voter suppression is unfortunately a real thing, and there's a long history of it in the United States. You can learn more here, https://en.m.wikipedia.org/wiki/Voter_suppression_in_the_United_States

I am aiming to encourage disheartened people to vote. Many people can't, and those who can should.

**Comment by Thaums** [comment]
Honestly you are free to do so but do not expect to be taken seriously by making minecraft mods your target of political activism
Also ironically you are arguing in bad faith

**Comment by Walaryne** [comment]
I was surprised to see this crossing my eyes today, but as a passerby on the internet... While I see why you'd want to encourage voting, shoving a specific candidate is really not okay. While I was taken aback by seeing the voting screen at all, the tipping point was seeing something that's _specifically_ encouraging one candidate or the other. Personally, I don't like either candidate, and one that would truly unify everyone is a unicorn... And even if that candidate did exist, they'd never reach the primaries. Anyway that was my two cents. Back to block game I go.

**Comment by mezz** [comment]
I think my intentions here are pretty clear but let me spell it out in case there's some confusion.

I believe most voters are mostly already motivated to vote. The right is much more motivated though, and they have mobilized strongly because of fear and anger driven by propaganda backed by distorted facts and lies. It's a lot harder to motivate people if you stick to the truth. The same well-funded propaganda machines target the left, but it is aimed at getting them to stop voting, to give up or to protest by not voting. There are many people who would vote left but have been convinced it's too much effort or not worth it.

This claim doesn't come from thin air. You can read a lot more about one company that has successfully moved voters with targeted ads that aim to sway people's votes with no respect for the truth.  Cambridge Analytica was essentially a modern propaganda machine, and part of the SCL group, which specializes in psychological warfare (not my words). Their actions directly affected the results of the last US election and several others. https://en.m.wikipedia.org/wiki/Cambridge_Analytica

I'm not going to be able to reach the voters who have been eating up fake news and targeted ads for the last four years, but I can at least do my part to help convince unmotivated voters that it is important for them to vote.

**Comment by Thaums** [comment]
There is a time and a place

**Comment by mezz** [comment]
K

**Comment by Waisse** [comment]
Why don't you stop developing mods and dedicate all your free time to political activism elsewhere ? Only a fool would politicize a children's block game.

**Comment by Walaryne** [comment]
I'm unmotivated because, as I said... I like neither of them. To me, one is just as bad as the other. I might be pessimistic but that's simply how I see it. I'm registered, and this is my first year I can vote. Trust me I wanted to. But after seeing my options I would rather not. I'll save my piece of mind on a candidate in the future that I truly feel in my heart will enact change for the betterment of everyone in the country. From what I've seen of both, those two definitely aren't the ones.

**Comment by mezz** [comment]
You are on the right path towards making good decisions by sticking to your standards, that's very important, but I think you will miss the vast difference in the candidates by keeping your head in the sand and not learning more about the current system. It is a lot of work to learn more and the lazy option is to just be apathetic and say you're above it all, without fully understanding. This is far from my first election and I'm honestly not too keen on either candidate, but it is extremely extremely important to vote this time.

**Comment by Walaryne** [comment]
My head is not "in the sand". In fact the action of popping my head out of the sand is what made me not want to vote. You seem to have my reasoning backwards there. I will not simply "vote" for one or the other, as voting implies my acceptance of the candidate. I would accept neither. In fact the biggest statement the entire country could make is the action of everyone protesting the vote. I would see that as the penultimate show of "we are not satisfied with the actions of our government or our voting system".

**Comment by mezz** [comment]
I think you are being idealistic (not necessarily bad) but are missing some key issues. I'll try to organize some of the main issues here to avoid making a mess of a discussion.

1. The right is passing legislation and paying large amounts of money to stop people from voting, because they know that this will keep them in power even with the minority of the people supporting them. Your protest vote is absolutely lost in a sea of votes that are simply being thrown out or never cast because of voter suppression efforts from the right.

2. Voter suppression will get worse if the republicans stay in power. Your vote may be one of the last times you have a chance to prevent that. You are not guaranteed to be able to vote in the future, many people already can't.

3. Our voting system ensures that you will probably never get a chance to vote for someone you like. We need reforms of the way we vote so that the popular vote matters, with ranked voting, or else we'll stay locked in to two bad parties forever. In this election, a vote for the left may not do much to fix this, but a vote for the right will help ensure it can never happen.

4. Voting is not about waiting for a clone of ourselves to run. Voting is about pushing things in the direction that is best for our country, and preventing things from sliding in the direction you dislike. When there is a very large threat coming from one side to push things in a terrible direction, so it is our duty as citizens to vote against it no matter what, regardless of how we feel about the candidates.

5. This presidency has extremely negative effects on many people today, right now. It may not affect you, but I hope you can see and acknowledge what is happening.

**Comment by Wazubaba** [comment]
The scary thing is that you can write that and not see how biased and radicalized you are. I'm not going to bother further because clearly you are far too brainwashed into this artificial nightmare world to see reason, but I truly hope you can one day rejoin us here in reality. It isn't just the republicans, you democrats are exactly as evil and harmful as they are. As I said prior - you are both two sides of the exact same coin. Two extremes which always lead to ruinous consequences.

**Comment by mezz** [comment]
That's simply not true, and I'm not sure how you can reach that conclusion.
If you'd like to question something specific, I can offer evidence or resources, but I suspect you are not really interested in learning about what's happening.

Also I would not say I'm a democrat. Given the choice here, I'll easily pick them though.

**Comment by mezz** [comment]
If you are looking to be informed without being radicalized, look to third-party rankings of factual accuracy and bias in news. This chart's pretty good: https://www.adfontesmedia.com/interactive-media-bias-chart-2/

Actively avoid partisan news, don't just jump on twitter or reddit or 4chan and bandwagon into some doom cult.

Fact still exist, seek out the news sources with a reputation for factual accuracy and a record to back them up and start there.

**Comment by Walaryne** [comment]
Clone of myself? Excuse the outburst but HELL NO. I wouldn't be suited for such a job, and I certainly wouldn't have the mind to run an entire country responsibly. As for point three, voting Biden ensures nothing. Keep in mind the whole prerogative of a politician is to get you to vote for them, and to reap the benefits of said office, and to want you to vote for them, and their party again (including feeding their campaign to line their pockets further). Point five, it has effected me negatively. Mainly with net neutrality being thrown out. I can be informed without being radicalized by observing the actions of whomever is running, without needing someone's "interpretation" of it. I can come to my own mind well enough as is. I'm not above reading the public information put out by the White House to draw my own conclusions.

**Comment by Wazubaba** [comment]
I know I said I would cease attempting to reason with you due to your lack of, well, reason, but I would like to clarify something: I am well aware of whats going on in the world without having a bunch of talking heads from either side inject as much misinformation as they can fit in that segment to point the finger of damnation at the other side. You are also reversing our positions right now - I'm the one trying to reason **you** out of a doom cult and back here into objective reality where sure everything sucks right now but that's normal when you have two cults trying to start a war with one another for ideological supremacy. I don't care if you have the last word in our own discussion just don't use it to try to reverse our positions here.

Edit ~18m after posting: I made a mistake and it's a bit too large to simply edit so I'm correcting it here as an addendum instead: They aren't *trying to start a war* they are merely continuing this forever war of theirs with a fresh wave of new victims by pushing towards yet another hot one.

**Comment by mezz** [comment]
This is the conclusion I've reached from unbiased sources.
The chance of the republicans taking over and destroying voting seems low, but the reality is that it has already started. We cannot stand for that, the vote that matters is one to protect our rights to be able to vote in more fair elections in the future.

**Comment by lineargraph** [comment]
@mezz : Avoid biased media, make your own conclusion, here is evidence.
Also @mezz: VOTE FOR BIDEN; NO TRUMP ALLOWED

Do you see why people might have a problem with that?

**Comment by mezz** [comment]
The tiny tiny fraction of a percent of people who actually avoid biased media and still conclude that the current extremist Republican Party is an acceptable option are not even worth considering, and I'm definitely not trying to reach them or discuss with them. That theoretical person is perfectly aware of the atrocities, as reported by unbiased media, but still embraces it.

**Comment by lineargraph** [comment]
But what makes you think that you are the arbiter of truth, that person that is wise enough to make that decision for others. Someone else might look at the same reportings, same data and see a different result. Demonizing your opposition is not the position of a reasonable person, and someone claiming ultimate truth as their own, especially in politics, is rather infantilizing. I'd prefer if you didn't belittle me, and in fact all users of your mod, as incapable of making their own decisions. My problem is not strictly the decision you've come to, but also that you don't think anyone else should be able to come to their own decisions.


Of course this is overly dramatic, but I urge you to reconsider whether you want the responsibility of a self-proclaimed arbiter of truth.

**Comment by mezz** [comment]
Of course people can come to their own conclusions. 
I urge people to vote, I recommend they vote for Biden.
Hopefully some people will throw that into their pile of data points and come to a good conclusion.

**Comment by samsh0** [comment]
Well I guess I'm removing JEI from my server and modpack until after this election passes. I made that server as a way for people to escape the madness not bombard them with more garbage.

We could all do without your zealous arrogance while we're here. You clearly think you're better than everyone because you think you've got the right of it when you clearly don't. You're unironically pushing Biden for God's sake and telling everyone not to fall for partisan media narratives. How do you even come to that conclusion if you even did the most cursory vetting of the man? 
Honestly I think you're the partisan.

I realize in the end it doesn't matter, you have no reason to care about your audience and what they think. Just would be nice if you had an actual conscience and not this flowery SJW nonsense.

**Comment by FireController1847** [comment]
The most disappointing thing out of all of this isn't the fact that there's a vote screen, or even a fact that Mezz is pushing for Biden. That's his opinion, this is his mod, he has the right to do so. No, the most disappointing thing is that something like this is enough to break a community apart, rip them to pieces and instead of working together to find a comparable solution, everyone is so fixed on their own point of view they can't seem to even acknowledge the other side.

The one side is saying that they are fine with the first message, but pushing for a specific candidate is stupid. I agree with this side, personally. But that's not what I'm arguing about. Yet now that I've said that, my point is moot, right? Because from this point on, I'm not saying anything that you agree with, or anything that you want to be a part of. The other side is saying that it's important to remind the people who may be on the edge that they need to vote. I also agree with this side. Now is that so hard to agree with parts and disagree with others? Apparently, it is.

So what's the point of all of this? It's lost in translation. There are so many points being made in this thread that any ounce of progress that could've been made has been shredded, pulverized and smashed until it's become nothing but a grain of dust.

Americans, vote, it's your duty. Mezz, step up and set a better example for the modding community. You're making us look like a disgrace and idiots. Non-Americans, put up with our messages until the election is over. It only happens once every four years anyways.

It would be a dream to get everyone to cooperate, but you all are countering your own points simply by arguing this way and fighting over the issue. Acknowledge that everyone has their own points, and move on.

**Comment by mezz** [comment]
This is a very dramatic take, the community isn’t really torn apart unless you’re judging by this GitHub issue that attracts the strongest negative opinions. The feedback I’ve received is overwhelmingly positive. I’m very thankful to the people who shared their stories about mustering the motivation to go vote, even when things felt hopeless for them before!

There isn’t really progress to be made in this thread IMO, GitHub is the wrong forum for long discussions and a lot of people want to jump in to here just concern troll or vent. I’ll reply here because I’m sure some people reading might actually want to learn about the motivation to create this, but I realize it’s not a very productive discussion.

I also want to note a small correction here: this should only show for Americans. Issues about seeing the screen from other countries were opened early on and resolved right away.

**Comment by Maxwelljones** [comment]
Absolutely. GitHub is the wrong forum for long discussions.
Videogames targeting kids averaging 9-13 is the wrong place for political propaganda. Keep it in your social media please.

**This not only show to US kids, but this shows worldwide.** Not sure how you thought your targeting but the way is unfortunately not working. Most players are playing in the default minecraft language which is EN_US, if that's the way you target, I would like you to think again. Check IP, country chosen in windows or ask the question "Are you US citizen?" in game before showing your screen?

**Comment by lineargraph** [comment]
Yep same for me. i have german as my system language, my proxy is routed to the netherlands and i still get this with every new instance. 


Also @mezz can we please ESC while the text is starting to show? Its the third time this week im sitting through this banner and that is starting to bother me 😅. I dont really get why [that check](https://github.com/mezz/JustEnoughItems/blob/1ebc566d63f22fcbd65e35e2525e37e1690303d8/src/main/java/mezz/jei/vote/GoVoteHandler.java#L251-L253) is there, its just makes this whole thing even more annoying, (as if that was possible).

**Comment by mezz** [comment]
There is an IP check, not a locale check. It calls this url and only shows if the countryCode is US:
http://ip-api.com/json/?fields=status,message,countryCode

You can see the response in your browser by clicking it.
For example, for me it shows `{"status":"success","countryCode":"US"}`

**Comment by Maxwelljones** [comment]
Site is down. Checking locale as a fallback is not fine imho. Fallback could maybe show nothing?

![image](https://user-images.githubusercontent.com/3750700/96804976-c742ad00-1410-11eb-878d-e231ca66810b.png)

**Comment by Ommina** [comment]
It's www.ip-api.com -- if the www is excluded, it won't resolve.  No idea what JEI uses internally, nor if it would default to showing the notice, or not.

**Comment by mezz** [comment]
If the website is not resolved by JEI, the vote screen doesn't show. The only case that will display the screen is if JEI gets a successful "US" response, it doesn't fall back on locale and the default is to not show it.
