### ISSUE TITLE
Removal of political propaganda?

### ISSUE THREAD

**Issue by jakey1995abc** [mezz/JustEnoughItems#2097]
I would like to include this mod in my modpack but I've noticed that it is currently being used for political propaganda (something I disagree with being forced on my users). Is it possible to disable this "feature" using config tweaks, install an alternative version without it, or can you recommend the latest version that does not have this content within the mod? I'd also like to note that by users adding this mod in it's current state to their modpack, it could violate laws relating to political censorship in some countries without them even knowing.

**Comment by Tahakk** [comment]
it won't show in countries outside of US

**Comment by jakey1995abc** [comment]
> it won't show in countries outside of US

Not true. It's showing for me and I definitely am not US (may be because I am using Twitch version of Minecraft?)

**Comment by mezz** [comment]
Thanks for the report!
This shouldn't be showing for you if you're outside the US.
Can you go to this URL and see which country code (or error message) it returns?
http://ip-api.com/json/?fields=status,message,countryCode

The result for me, for example, is `{"status":"success","countryCode":"US"}`

**Comment by dancojocaru2000** [comment]
Querying an external API dealing with IP addresses without user knowledge seems very untrustworthy and possibly breaking privacy regulations.

**Comment by mezz** [comment]
This external API is a database which already knows where each IP is located. By querying it, you get information from them so that the client code can learn if you are in the US, you are not giving private information to them or anyone else.

**Comment by dancojocaru2000** [comment]
I just installed JEI for my brother and would you look at that:

![WhatsApp Image 2020-09-24 at 20 39 58](https://user-images.githubusercontent.com/9626761/94180231-60c87e80-fea6-11ea-8d9a-c0118812a5ca.jpeg)

And no, I am certainly NOT in USA.

Furthermore, I find it disgusting to suggest donating to one candidate only. Perhaps it's different customs, but encouraging people to vote is one thing, telling people to donate to one specific candidate is another. At this point this is just shameful. 

![InkedWhatsApp Image 2020-09-24 at 20 40 18_LI](https://user-images.githubusercontent.com/9626761/94180551-db919980-fea6-11ea-99ef-b59108d984cb.jpg)

---

Disclosure, just in case: I've been looking at the situation here and there when news shows up and overall Trump being in the office for another 4 years seems like a bad idea. That said, "go donate to Biden" still is a very shameful thing to do. Imagine buying a phone with a "Vote Trump" wallpaper that you can't change until election is over.

**Comment by mezz** [comment]
@dancojocaru2000 Can you go to this URL and see which country code (or error message) it returns?
I want to make sure that this is not displayed outside the US, and your response may help me fix the issue.
http://ip-api.com/json/?fields=status,message,countryCode

**Comment by jakey1995abc** [comment]
@mezz {"status":"success","countryCode":"GB"}

**Comment by dancojocaru2000** [comment]
@mezz `{"status":"success","countryCode":"RO"}`

**Comment by mezz** [comment]
Looks like that is working, thanks.
Maybe there was a moment where the response didn't come back to the client. I'll make sure the code doesn't show the screen unless it definitely gets a "US" response.

**Comment by dancojocaru2000** [comment]
Here's a little of outsider feedback:

People who would donate to Biden would donate without that reminder.

People who would donate to Trump would certainly not donate even with the reminder.

People who aren't sure what to vote for could be aliented from Biden and gravitate towards Trump when they see that such a thing appears in a mod for a game that is often played by children too.

Ultimately, it's your choice. But you got some feedback on here from multiple people that they find this not okay. 

USA is going through hard times right now. Do you really want to be the person who breaks someone's mood when they try to escape from the stress of society and instead play some game only to be yet again greeted with neverending politics?

**Comment by mezz** [comment]
Thanks, I am sorry that this screen is annoying but I'm not really looking for outsider feedback.

The Biden item is pretty hidden away and not meant to sway people, I think it is almost literally the least I can do right now considering what's happening in my country. 

It is not just hard times right now, my people are dying because of the mismanagement of the coronavirus response, and there is an open threat that our democratic system may be dismantled and become fully authoritarian. If you are interested to learn more I can offer some outside links that explain in a much longer format, but in short please understand that these circumstances are far from the regular annoying left-vs-right politics that we are all used to getting battered with online every 4 years when the US holds an election.

**Comment by dancojocaru2000** [comment]
Thank you for your response.

Thank you as well for clarifying that this is not yet another "Americans annoying the entire internet with their elections because when something happens in USA the whole world must know" that generally happens.

In the light of your explanation, I understand and respect your reasoning for putting those things in.

I hope things will go well.

**Comment by playpolticalgameswinpolticalprizes** [comment]
I mean... his people are dying
I wonder who he is talking about? 
Other spoiled rich kids that went to Berkeley? (Educated morons?)
Which never rented a house or lived anywhere besides in his mommies (Jollen's aka Jo) home.
That are 39(40 soon) year old  virgins that has never had a girlfriend/boyfriend/ pet cat.
Which works from home at Discord?

Those people?

Average 650,000 people in United States die from Heart Disease EVERY YEAR
Average 600,000 people in United States die from Cancer EVERY YEAR
Average 150,000 people in United States die from Car accidents EVERY YEAR
Average 140,000 people in United States die from Stroke EVERY YEAR
.... lets add this one too ON AVERAGE 50,000 people die from THE FLU EVERY YEAR
don't forget people killing themselves from depression from things like lockdowns..
AVERAGE 40,000 people in United States KILL THEMSELVES EVERY YEAR.

202,329 (AS THIS MOMENT ON CDC) people in united states have died from COVID-19

Majority of those deaths were in New York and majority of deaths in New York happen in Nursing homes.
Followed by New Jersey.

So if want to continue to play dumb games
You too can win dumb prizes.

So some advice from a real adult not one suffering peter pan syndrome.
Go outside take a deep breath of those fires fuming in Cali cause protesters starting fires.

And think... "Damn my life is over half way over and all I got to show for it was making a mod for a game and getting mocked"
https://www.youtube.com/watch?v=d3FZdGaSUXw

Like when Joe Biden tells his story of how he met his wife on blind date... i am sorry his wife had affair with her ex husband.

Truth something you don't know virgin.

**Comment by dancojocaru2000** [comment]
@playpolticalgameswinpolticalprizes: There are so many things wrong with your message.

I'll tackle only one: unwarranted, uninvited insults generally show a severe lack of intelligence.

There are also factual things that are wrong with your message but that I won't bother to point out because, after the unwarranted insults, you are not a person worthy of having a discussion with.

@mezz: I suggest hiding that comment as off topic if possible. And also, perhaps a little wellness advice is to simply ignore such messages and not bother interacting with them since there is no benefit to it.

**Comment by playpolticalgameswinpolticalprizes** [comment]
Hide it fast cause it factual gov numbers it hurts your lies

**Comment by dancojocaru2000** [comment]
> cause it factual gov numbers it hurts your lies

Grammar.

> Most people are immune to covid-19 because of cross immunity of T-Cells... 

A quick Google search show _"that 20–50% of people who hadn’t been exposed to SARS-CoV-2 showed T cell responses against different parts of the SARS-CoV-2 virus"_. That's certainly not "most", and just having a reaction doesn't mean being immune against it.

> The testing to see if anyone been infected is nonscience cause it is checking for presence of antibodies which just show immunity.

Antibodies aren't always effective at curing the sickness. Especially with COVID-19, one of the cases of death, especially in younger people, is the immune system having an overreaction and starting to destroy not only the virus but also the internal system of their own body.

> ORANGE MAN AND SCIENCE BAD

Coming and throwing some random numbers doesn't show much, especially when not even the science is entirely sure what to do. Next, [the science will say we need to wear party hats](https://youtu.be/1ygWxYanTO0?t=548).

However, coming and throwing insults shows that you are an asshole. Despite all the "Ben Shapiro DESTROYS liberal student with FACTS and LOGIC" videos floating around, in which conservative speakers bravely take on students with not too much knowledge compared to taking on people experienced on the matter, real life isn't really quite like that. Instead, if you come with insults and you are an asshole, that will be your branding. What you say afterwards is irrelevant. If you are an asshole who needlessly insults people, you are no longer welcome.

**Comment by playpolticalgameswinpolticalprizes** [comment]
> Grammar.
Cause that is what matters right low intellectual space waster?
 
> > A quick Google search show _"that 20–50% of people who hadn’t been exposed to SARS-CoV-2 showed T cell responses against different parts of the SARS-CoV-2 virus"_. That's certainly not "most", and just having a reaction doesn't mean being immune against it.
"Different parts" what are we playing with legos? You barely understand English I see.
FROM DIFFERENT "STRAINS" there is more than one strain of covid and cross immunity is real

> Antibodies aren't always effective at curing the sickness. Especially with COVID-19, one of the cases of death, especially in younger people, is the immune system having an overreaction and starting to destroy not only the virus but also the internal system of their own body.

Shakes head again you are talking not about T-Cells which is very different thing. 
 
> Coming and throwing some random numbers doesn't show much, especially when not even the science is entirely sure what to do. Next, [the science will say we need to wear party hats](https://youtu.be/1ygWxYanTO0?t=548).

Coming up more googling and not understanding english so saying "strain" as "different parts"
Dr. Google.

**Comment by dancojocaru2000** [comment]
> Cause that is what matters right low intellectual space waster?
 
Once again, insults.

**Comment by playpolticalgameswinpolticalprizes** [comment]
> 
> 
> > Cause that is what matters right low intellectual space waster?
> 
> Once again, I need safe space and squeezy bear I going to cry mommy!!111

Says kid trying to pretend to be adult crying "GRRAAmaammmER"

**Comment by Leitoha** [comment]
>@playpolticalgameswinpolticalprizes: There are so many things wrong with your message.
I'll tackle only one: unwarranted, uninvited insults generally show a severe lack of intelligence.

"There are so many things wrong but I'll pick the weakest one because I can't address any of the factual information you put out."
Real strong argument you got there buddy.
Also, insults are not a sign of lower intelligence at all. What you're doing is called a logical fallacy in an attempt to undermine the rest of the response because you are uneducated.

>There are also factual things that are wrong with your message but that I won't bother to point out because, after the unwarranted insults, you are not a person worthy of having a discussion with.

"I can't disprove your factual information so I'll just say the insults are enough to dismiss you with"
Uh huh. Tell us more about how big your brain is buddy.

>@mezz: I suggest hiding that comment as off topic if possible. And also, perhaps a little wellness advice is to simply ignore such messages and not bother interacting with them since there is no benefit to it.

Except he promotes factual information while you cry about grammar and insults.

>Grammar.

Not an argument.

>A quick Google search show "that 20–50% of people who hadn’t been exposed to SARS-CoV-2 showed T cell responses against different parts of the SARS-CoV-2 virus". That's certainly not "most", and just having a reaction doesn't mean being immune against it.

So this is the article you're referencing.
https://science.sciencemag.org/content/early/2020/08/04/science.abd3871
All you did was take the abstract and butcher it to make your argument. When in reality, what it actually said was 20-50% of people have "Pre-existing cross-reactive T cell memory". So that's 1 factual lie you've told, out of 1. 

>Antibodies aren't always effective at curing the sickness. Especially with COVID-19, one of the cases of death, especially in younger people, is the immune system having an overreaction and starting to destroy not only the virus but also the internal system of their own body.

Oh my god. Do not talk about the immune system you incompetent fool. Just no.
https://www.newscientist.com/term/antibodies/#:~:text=Antibodies%20work%20by%20recognising%20and,associated%20with%20that%20particular%20microbe.

We literally look for antibodies to see if someone has had it and has gotten over it.
https://www.nature.com/articles/d41586-020-02400-7
The immune response to Covid-19 has been predictable. Because it's essentially just a bad flu.

https://jamanetwork.com/journals/jamainternalmedicine/fullarticle/2767939
Also, a Cytokine storm is not truly relevant for Covid-19. 
"For these reasons, the term cytokine storm may be misleading in COVID-19 ARDS. Incorporating a poorly defined pathophysiological entity lacking a firm biological diagnosis may only further increase uncertainty about how best to manage this heterogeneous population of patients."

>Coming and throwing some random numbers doesn't show much, especially when not even the science is entirely sure what to do. Next, the science will say we need to wear party hats.

Except when you look at the science and real world example. Sweden and other countries and even states in the US that didn't lock down, have done better than states and countries that have. South Dakota for example. The only state to see an increase in their economy.
The lockdowns are predicted to have more of a negative impact on the world than Covid-19 itself has.
https://thefederalist.com/2020/06/16/research-finds-lockdowns-are-far-worse-for-health-and-lives-than-coronavirus/
https://www.rt.com/op-ed/485876-covid-lockdown-kills-150000/

>However, coming and throwing insults shows that you are an asshole. Despite all the "Ben Shapiro DESTROYS liberal student with FACTS and LOGIC" videos floating around, in which conservative speakers bravely take on students with not too much knowledge compared to taking on people experienced on the matter, real life isn't really quite like that. Instead, if you come with insults and you are an asshole, that will be your branding. What you say afterwards is irrelevant. If you are an asshole who needlessly insults people, you are no longer welcome.

Except Shapiro has and does take on professors and other experts.
https://www.youtube.com/watch?v=_QBDgwtO_Xk
So another lie.

Oh no. He's a big meanie. And yet he's still more factually right than you are. As you've told multiple lies here today.

>Once again, insults.

Once again. P-p-pussy.

**Comment by Leitoha** [comment]
>Thanks, I am sorry that this screen is annoying but I'm not really looking for outsider feedback.

Of course you aren't, because if you were that'd open you up for criticism.

> The Biden item is pretty hidden away and not meant to sway people, I think it is almost literally the least I can do right now considering what's happening in my country.

"It's not meant to sway people, I'm just doing it for no reason at all."
Not very convincing there.

> It is not just hard times right now, my people are dying because of the mismanagement of the coronavirus response,

So what should Trump have done differently? Give me 1 example. Just 1.
Also, the fact Covid-19 has a 0.3% death rate.
https://www.forbes.com/sites/brucelee/2020/09/26/what-is-the-death-rate-for-covid-19-coronavirus-what-this-study-found/#6334719c5c46
Not to mention the fact that over 90% of deaths include comorbidities. Specifically 2.6 on average.

>and there is an open threat that our democratic system may be dismantled and become fully authoritarian. 

LOL? Except you know, the Democrats have come out and said that Joe Biden should not concede under ANY circumstance.
The fact the Democrats held up Covid relief bills specifically to rework signature verification for mail in ballots. The fact they are even pushing mail in ballots when we know it's rife with issues and the top 2 leading doctors in the country have come out and said in person voting is safe. You have lost your mind.

>If you are interested to learn more I can offer some outside links that explain in a much longer format, but in short please understand that these circumstances are far from the regular annoying left-vs-right politics that we are all used to getting battered with online every 4 years when the US holds an election.

Oh please. Please give me your sources. Because I know for a fact you can't source any of the shit you're spewing.

**Comment by mezz** [comment]
I'm not here to debate people who are coming from an alternate reality where they think it's OK to be threatening to someone and then continue on the conversation like it's normal. This is way out of line.
