### ISSUE TITLE
Why is there a register to vote message? This is not place for this.

### ISSUE THREAD

**Issue by BurnN8or101** [mezz/JustEnoughItems#2099]
I was so happy to see a 1.16.3 version of JEI. I instantly downloaded and went to single player to mess around with it and other mods I install and then it takes me to a red and blue screen. I was so confused, but then I read it and realized "oh, they're doing THIS now!?"
When I download a mod to use in minecraft (or any mod for that matter), I DO NOT want to be told about polarization and needing to register to vote! I just want to play modded minecraft. This is the last place I want to be hearing about politics. Not to mention the fact that only a third of people are probably eligible to vote anyways, not to mention half probably not being in the US. So please do us a favor and get rid of the message now. I don't care if it only plays once because it shouldn't be there in the first place.

Please remove ASAP (you'll have to remove it after the election anyways, so just do us a favor and do it now)

**Comment by TelepathicGrunt** [comment]
The message only shows for americans, is skippable with a single key, and will never show up again as long as you don't delete the vote marker file. 

Furthermore, people who think that video games is free from politics is pretty naive as politics affects every single part of our lives. Including video games.

Now mezz, he decided to add this please vote screen into his personal project mod which anyone can download for free. In fact, he isn't being paid or anything unlike obtrusive and unskippable commercials we see all the time that want our money. His screen is for a cause he believes in while also trying to minimize how intrusive the screen is.

**Comment by Caff3in3d** [comment]
I'm all for encouraging people to go vote, but above all I would encourage you to vote for something you believe in. Adding a "Go support Joe Biden" tab in the item list in-game is not just annoying because its bringing real life problems into a game where I just want to dig for diamonds and make cool things, it's discouraging others from thinking for themselves and making their own decision based on what they think is right. Calling someone naive for wanting to have some escapism from the political banter that's constantly being shoved down our throats all day is just dumb. If it's not obvious, I also don't enjoy this addition to the mod and would also like to see it removed, or at least an option to turn it off. The creator can do what they want, but I'm guessing I'm gonna have to wait until after Biden gets cancelled for inevitably saying something the democratic party doesn't agree with to re-download this mod.

**Comment by playpolticalgameswinpolticalprizes** [comment]
Reminds me when forestry was closed source and code was added to delete files if MultiMC or Technic launchers were used.

Wasn't accident either it was hidden in function call to grab image to display.

**Comment by mezz** [comment]
Sorry for the annoying screen.
If you want some more context, you can catch up and participate in the bigger thread here: https://github.com/mezz/JustEnoughItems/issues/2093
