### ISSUE TITLE
Crash with bungeecord

### ISSUE THREAD

**Issue by ProsperCraft** [mezz/JustEnoughItems#214]
http://pastebin.com/y3h2QVV1

Client crash when switching from hub to server in a bungeecord environment.

**Comment by mezz** [comment]
Thanks for the report!
Sorry I don't know what the `bungeecord environment` is. Is there somewhere to report this to them? I don't think this issue can come up under normal conditions.

**Comment by Prospector** [comment]
IIRC bungeecord is a server software that can "connect" different servers together to form a network of servers. 

Here's their github: https://github.com/SpigotMC/BungeeCord/ and their wiki page: https://www.spigotmc.org/wiki/bungeecord/

**Comment by mezz** [comment]
Hey @md-5, 

It seems that bungeecord might be setting things up differently than expected, so that when JEI is restarted it's finding that `GameData.getItemRegistry().getNameForObject` returns null [here](https://github.com/mezz/JustEnoughItems/blob/1.8.9/src/main/java/mezz/jei/util/ModList.java#L32) (shown in the crash log).

JEI starts when `EntityJoinWorldEvent` is called and `Minecraft.thePlayer` is not null. [See here for code snippet.](https://github.com/mezz/JustEnoughItems/blob/1.8.9/src/main/java/mezz/jei/ProxyCommonClient.java#L126-L135) Normally that's pretty late into client startup (jei is client-side) and everything is ready and enabled.

Any idea why this might happen?

**Comment by md-5** [comment]
Bungee has to pretend to be a forge server:
https://github.com/SpigotMC/BungeeCord/tree/master/proxy/src/main/java/net/md_5/bungee/forge

It's possible it doesn't emulate all aspects fully or correctly. In particular based on a 10 second look at your code, it's probably acting upon events that happen when logged into Bungee rather than actually connected to the server - Bungee hasn't yet had time to forward Forge data from the server.
I'm not sure of specifically when EntityJoinWorldEvent is fired in Forge, but it's probably too early in the login process.

**Comment by ProsperCraft** [comment]
I am no programmer but would it be possible to catch this and have it try a second and third time before it finally fails?

**Comment by magerooster** [comment]
I am getting the exact same stack trace crash he is, but without Bungee involved.

https://gist.github.com/magerooster/321b1e8f0fadaeb2b027

It crashed out while I was puttering around my base moving items around and continues to crash each time I try to reconnect to the server. The server log just shows a normal client closed connection suddenly message.

**Comment by mezz** [comment]
@magerooster that's actually not the same, can you please make a new issue?

**Comment by magerooster** [comment]
Sure.

**Comment by mezz** [comment]
A lot has changed in JEI over the last few months.  
I am no longer depending on the Item registry, because the items on the client do not always match what's on the server.

@ProsperCraft can you confirm that this is still an issue, or that is has been resolved?

**Comment by ProsperCraft** [comment]
We don't see this anymore, thank you.
