### ISSUE TITLE
Armor Duplicating

### ISSUE THREAD

**Issue by Elithelion** [mezz/JustEnoughItems#218]
If you are in admin mode and you die and return to your death point, the armor you are wearing gets duplicated. This happens if cheat items is on or off. I removed JEI from my mods folder just to test and the problem goes away. Server is Spigot 1.9, Client is Forge 1.9, JEI latest version other mods are Xaero's minimap and Xray-7 (which has its own bugs)

**Comment by mezz** [comment]
Thanks for the report!
JEI doesn't do anything to the player inventory, except for moving recipe items into the crafting area when you click the [+] button.
It's not like NEI where it saves your inventory or anything like that. Are you sure it's not from something else? I think it could be, since 1.9 has lots of crazy bugs like this still.

**Comment by Prospector** [comment]
@Elithelion were you able to replicate this behaviour more than once? It might've just so happened that it stopped glitching when you rebooted your client, it might be unrelated to the uninstall of JEI.

**Comment by Elithelion** [comment]
Well...this morning it was doing it, Just now I removed JEI, restarted the game, tested, problem was gone. Reinstalled JEI and now the problem appears to be cleared up. Can't explain it, I do have 2 chests of duplicated items now....I don't get it.

**Comment by Elithelion** [comment]
Well...after much more testing it appears to be a serverside issue - thanks for the quick replies :)
