### ISSUE TITLE
Jei multiplayer server problems.

### ISSUE THREAD

**Issue by Havoc1001** [mezz/JustEnoughItems#2190]
I am having a problem with 1.16.4 version of jei where I cannot see the gui for jei,  but every other player on the server can. I have already tried the control+o....no luck. I have used it for over a week with no problems, then I had a server crash for unrelated reasons, ever sense that time jei wont show items on the right side of the screen when pressing "e" key for inventory.

**Comment by Coraline77447** [comment]
I'm having a similar issue for my modded multiplayer server but I can't see the pages in jei while in my inventory at all when I started my server (Btw I'm currently the only one on my server tho since I need more java friends to play minecraft with, so I don't know if jei works for anyone else since there's nobody else who would like to join my server... But this isn't important, what's important is that I'm having the same issue as you or similar issue as you, ok). Also I too tried control+o and same result as yours. I think that the only way to make it work on the server is to go to jei's world settings in it's config file and find the server's world and change something to it (if you're the host of the server like how I'm the host of my server) but if that doesn't work then the last resort is to delete jei's config (for both the client and server possibly) but that may not work cause someone who made a issue on here said that even deleting jei's config didn't solve this issue...

**Comment by ghost** [comment]
Im having the same issue

**Comment by Coraline77447** [comment]
My reply may be irrelevant now since I'm considering about getting rid of my server since nobody is gonna join my server and that I'm literally hosting it on my laptop which doesn't have the right specs to be running a server and the game at the same time... My server would've been struggling with more than just 3 people and even with only 3 people (myself and two other people) on the server....

**Comment by ghost** [comment]
Well remove apotheosis and supermultidrills if you have them and it may work friend

**Comment by Coraline77447** [comment]
Speaking of Apotheosis, I'm experiencing problems with that mod that I can't play with it now till the problem that I ran into gets fixed first before the fix for the fletching table that Apotheosis modifies
