### ISSUE TITLE
Cannot unfocus search bar.

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#2321]
https://user-images.githubusercontent.com/42738314/115296386-934c0880-a163-11eb-832f-402f10898c28.mp4

Only 'Esc' works.

Version: Latest.

**Comment by DaniloNocete** [comment]
can confirm the bug
jei-1.16.5-7.6.4.88.jar
forge 36.1.0

**Comment by moon-st0ne** [comment]
same issue here, jei 7.6.4.88 on forge 36.1.4

**Comment by Peca21** [comment]
Same here, I edited this to my issue also. #2320

**Comment by mezz** [comment]
Thanks for the report!
I have archived JEI version 7.6.4.88 until I can create a proper fix for it. Please use an older version for now.

**Comment by pupnewfster** [comment]
To add on to this just as it is another issue that was introduced in JEI 7.6.4.88 and is probably at least somewhat related to this because of the changes to click handling... It is no longer possible to drag ghost items from JEI (presumably due to the introduction of [this else branch](https://github.com/mezz/JustEnoughItems/commit/5097e3df0cc15dbc9d45195cf2bf3fde44c2a0ee#diff-97d250c1774cbd40866e5eea4195b6bd8444330be26b5e44a5f796da25392561R146).
