### ISSUE TITLE
JEI won't recognize my ftb gui library installation

### ISSUE THREAD

**Issue by Noahfrechette** [mezz/JustEnoughItems#2415]
so i have ftb gui library and it keeps on saying it needs it but i do have it
![image](https://user-images.githubusercontent.com/73401157/125196882-29eb0b80-e221-11eb-864a-0a59c22c467b.png)
![image](https://user-images.githubusercontent.com/73401157/125196917-3bccae80-e221-11eb-9801-117f23fdb570.png)

**Comment by Novocastrian** [comment]
Also experiencing this issue in the latest Direwolf20 1.16 modpack on the FTB app. I assume it is because of this? https://github.com/FTBTeam/FTB-Library/issues/28#issue-897472650. I've seen this reported elsewhere too: https://github.com/NillerMedDild/Enigmatica6/issues/2209

**Comment by officialjrem** [comment]
I found a fix for this. Go to ftb library on curse website instead of curse launcher and download the jar for 1.16.5 that they put out on July 2nd. It’s not showing up on curseforge launcher for some reason and the one that is, is what’s causing that can’t access config glitch. Replace the old jar with the new one and you’ll be able to access your config again.

**Comment by MaxNeedsSnacks** [comment]
This issue should no longer be valid now as we've released the previously "unstable" versions of the FTB Mods (see jrem's comment) since then; just update your mods to fix this ^^

**Comment by mezz** [comment]
Thanks for the report!
It seems like FTB Library hasn't been very dependable, I have removed support for it and now recommend installing the Configured mod to configure mods in-game. Sorry, I wish this was built into Forge like in previous versions.
