### ISSUE TITLE
Jei doesn't load into dev environment using FG3 on 1.12.2

### ISSUE THREAD

**Issue by IStrikeboomI** [mezz/JustEnoughItems#2446]
Forge Version: 1.12.2-14.23.5.2855
Jei Version: 1.12.2:4.16.1.302

I get a game crash every time I try to open: https://gist.github.com/IStrikeboomI/9e969854dc7956a4e8fd297d9e3c7603

I can't use FG2 because the link to that is dead

**Comment by mezz** [comment]
I wasn't able to get JEI working reliably with FG3 on 1.12 unfortunately.
I ran into resource issues in local dev, and problems with ATs when mods depended on JEI. There was no support for ATs in FML with FG3 at that time, so I reverted my changes and left it alone: https://github.com/mezz/JustEnoughItems/commit/1fa2459ee701590950c2f6a90f535fba2b662022

Please let me know if those problems have been fixed since then (almost exactly 1 year ago). It may be worth updating JEI 1.12 to FG3 if everything is working now.
