### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#245]
https://gist.github.com/zoezi7/38e453925070ffdc09407532039fb3b4#file-gistfile1-txt

My Mods Folder:

http://imgur.com/a/zPOPM

Whilst opening a singleplayer world it opens, then displays "Shutting down internal server" and Minecraft forces close

Using forge version: 1.8.9-forge1.8.9-11.5.1.1808

**Comment by ghost** [comment]
I get the same problems with forge 1855

**Comment by ghost** [comment]
Have you tried updating to the most recent Forge? And it doesn't seem like a JEI issue when reading through the error log that was posted.

**Comment by Prospector** [comment]
> I get the same problems with forge 1855

**Comment by mezz** [comment]
Thanks for the report!
Can you paste your client log to gist? It should have the information I need to solve this issue.

**Comment by mezz** [comment]
I updated JEI (2.28.16), it should give a better error message. Please try it out and report back.

**Comment by ghost** [comment]
Forge 1808:
https://gist.github.com/zoezi7/192e841508f35a9acdcfdc5cec08bbbe#file-gistfile1-txt
Forge 1855:
https://gist.github.com/zoezi7/a42e81044ae5f13382db4e64b666487b#file-gistfile1-txt

**Comment by Jiraiyah** [comment]
mezz it looks like your keybinding will cause error in forge 59 mc 1.9, crash --> Caused by: java.lang.NoSuchMethodError: net.minecraft.client.settings.KeyBinding.setAllowsKeyModifiers()V

i think you need to upgrade the forge version in your project : 

https://github.com/mezz/JustEnoughItems/commit/4feff50edfec187ccde7f51f28f8aa40e18dd52d#diff-2944f76e56326aefcd7e8d9786dc8231R28

mine would show the bindings of my mod without need of these few lines !

**Comment by TehNut** [comment]
@Jiraiyah That is completely unrelated to this crash. Also, it was fixed in 18aa30904e575c0c25f36103c0607a4b16d237b2

**Comment by mezz** [comment]
Thank you @zoezi7. 
This is a stack overflow error from DummyCore, please report your Forge 1855 log here: https://github.com/Modbder/DummyCore/issues
