### ISSUE TITLE
JEI just simply will not show up! I am in 1.16.5, and no matetr what I do, Its like I didn't even download the mod...

### ISSUE THREAD

**Issue by Draglorr** [mezz/JustEnoughItems#2456]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by wicked9090** [comment]
Just adding that I am having the same issue when using a large pack of mods, I have been unsuccessful in finding the cause after hours of testing. Please see my latest log which I am unsure if it will help. It all worked fine a week ago, then I load up since and JEI doesn't show anymore, even after using the show/hide JEI keybind

https://gist.github.com/wicked9090/b49af7fe3b870c6e6ec4f4b60625b628

Let me know if there is anything extra I con provide that may assist.

**Comment by Ommina** [comment]
@wicked9090 It's better to create your own issue instead of jumping onto somebody else's.  Your symptoms (as it were) may be similar, but the cause and solution are unlikely to be the same.

Ping me from there and I'll take a closer look.
