### ISSUE TITLE
[Feature Request] Add custom items to list by datapack

### ISSUE THREAD

**Issue by zlyfire** [mezz/JustEnoughItems#2485]
I'm adding some custom potion variants to my personal server/pack, with their own display name and crafting recipe, via datapack. However, as expected JEI is not automatically displaying these items; but I am also not seeing any way to add a tag or otherwise add a custom item to the JEI item list.  

I can see this being potentially useful to packmakers who have a few basic items they have added via datapacks to ensure those customized items are shown to players.   

Below is a snippet from in game showing a custom recipe to make a customized NBT-based item, which I'm wanting to show on the right-hand list (which is filtered to "dand")
![image](https://user-images.githubusercontent.com/7097319/132145003-e84fcd11-9d15-4f25-9c05-cda330783763.png)

**Comment by mezz** [comment]
Thanks for the request!
JEI differentiates potions by their effects, so that potions with different NBT can still be displayed or used in recipes that require the regular version.
Unfortunately I do not believe I can support this in a general way that works for all cases, it would require a tiny mod to tell JEI how to understand the difference between these special NBT items and the regular versions.

**Comment by zlyfire** [comment]
I wasn't thinking of a programmatic method for JEI to understand these, just a data pack entry to add an item to JEI search, as a manual entry, like how there is a data/information tab when you look at recipes/uses for some items.
