### ISSUE TITLE
Failed to register mod plugin plus few other problems found in the log

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#260]
I believe JEI has a problem with FEI. I have found an entry in the log file after I have FEI installed with your mod together. the Games is not crashing
Log: http://paste.ee/p/jG5Vx (while the game is running)

**Comment by mezz** [comment]
Thanks for the report!

`Failed to register mod plugin: class jeresources.jei.JEIConfig` 
That issue is here: https://github.com/way2muchnoise/JustEnoughResources/issues/55
I think you just need to update JustEnoughResources.

The recipe errors you see are from all different mods and should be reported to whoever made them. They will not crash JEI, they're just being reported and then ignored.

FEI compatibility is up to them, you can report any FEI issues you have here: https://github.com/elix-x/Forever-Enough-Items/issues?q=is%3Aopen+is%3Aissue

**Comment by Prospector** [comment]
Well, can't really blame @jokish63 here because on the FEI curse page, it says to report issues to both you and him

> WARNING 2: If issues concerning JEI and JEI pluggins appear, report them to me and to mezz. FEI might be causing them.

**Comment by TehNut** [comment]
That's... no he shouldn't be doing that...
