### ISSUE TITLE
 java.lang.IllegalStateException: Already building!

### ISSUE THREAD

**Issue by HoNGamer** [mezz/JustEnoughItems#261]
This crash occured when entering certain strings to the search bar in this case I wanted to search for tinker stuff and it happened at @tin but there are many other combinations that wont work either

https://gist.github.com/mezz/d4cec800c904c96032764ba9a24e3763

**Comment by mezz** [comment]
Thanks for the report!
Can you post the full client log to https://gist.github.com and link it here?

**Comment by HoNGamer** [comment]
You're welcome! This is a reproduced version https://gist.github.com/HoNGamer/2f8d4f28e7313b87c094e34a3a968190 
I'm trying to figure out what combination of mods is causing it

Got it. 
CraftingTableIV-1.8.9-1.2.84 in combination caused the problem

**Comment by mezz** [comment]
Thanks, confirmed. 
It's the same as this issue here: https://github.com/Elecs-Mods/CraftingTable-IV/issues/28
I'm calling the normal vanilla render method, so I suspect that the item would still crash in an inventory without JEI involved.
Edit: it does crash without JEI: https://github.com/Elecs-Mods/CraftingTable-IV/issues/29
