### ISSUE TITLE
New JEI control options

### ISSUE THREAD

**Issue by BigAl607** [mezz/JustEnoughItems#2620]
Was just wondering if there was a way to revert JEI back to the old set up in the Minecraft "Controls" section. Sorry if this isn't the place for this, but I wasn't sure where else to put it

**Comment by mezz** [comment]
Thanks for the report!
Sorry, is there an issue with the new controls sections? I added more controls and wanted to make sure they were clear.

**Comment by BigAl607** [comment]
They're clear. Personally I didn't think they needed to be separated in that way. It just seems to jumble up the controls section. I can see how some people would find it useful however. I was just curious if there was a way to revert them back to they way they used to be. (Also, I hate change, so that may be part of it as well.)

**Comment by mezz** [comment]
Ah ok. I wish there was a better way to display these but Minecraft's control options are pretty limited.
I had to add support for controls with key modifiers (shift, ctrl, cmd, etc) in Forge myself, for example.

Unfortunately I think the improvements in accessibility and discoverability weight a bit more here than a desire for things to stay the same, sorry. I hope you're not spending a lot of time configuring JEI's controls so that it's not a big hassle all the time.
