### ISSUE TITLE
Version Number Mixup

### ISSUE THREAD

**Issue by willtarax** [mezz/JustEnoughItems#2673]
Thank you for reporting!

Latest version is jei-1.18.1-9.1.2.68.jar

This is leading to issues with mods that are looking for 1.9.2+

**Comment by Ommina** [comment]
Can you expand somewhat on the problem?  There is no JEI 1.9.2 - the closest I see is 1.9.0.100 for MC 1.8.

If it is simply "the numbers look similar at first glance", that's fair I suppose.  I've caught myself reading "1.17.1" as "1.7.10" more than once.  But I'm not sure that justifies abandoning the version numbering that has been in use since day one.

Or is there something else going on that I'm just not seeing?

**Comment by willtarax** [comment]
Sure, sorry, it might make more sense with an image. In the attached image you will see the latest two releases, and you will see that two of the numbers in the version ID are swapped. This is causing issues with other mods that are looking for a version number that is higher then v9.1 when the -- goddamnit. Nevermind. Sorry about that. I must've misunderstood and error I was getting on my server, I will close this ticket, thank you.
![JEI](https://user-images.githubusercontent.com/76260755/148859487-6a559601-4c6c-4718-92a1-a68d48b6bd16.PNG)

**Comment by Ommina** [comment]
:grinning:  I feel like I just watched an "oh crap" moment unfold in real time.  You were not, perchance, reading the "1" at the end of "1.18.1" as the starting character of "1.9.2", instead of "1-9.2", were you?

Either way, I'm glad you got it worked out.

**Comment by mezz** [comment]
Sadly version numbers are pretty unfriendly to humans... we just have to trust that the computers are getting it right somehow :D
