### ISSUE TITLE
Recipe & Uses bound to mouse buttons fail on real items

### ISSUE THREAD

**Issue by DocterDum** [mezz/JustEnoughItems#2719]
Hi,

When using the recipe/uses keys as r/u, everything works fine, however when I rebind these to Button 4/5 (Buttons on side of mouse), the recipe/uses only works on the JEI display, and not on items that are physically in an inventory (e.g. my inventory or a chest).

This issue was not occurring in any 1.12 modpacks, and occurs in all 1.16 modpacks I've played (Valhelsia3 , DW20 1.16, and a custom pack).

Forge Versions Tested: 36.2.22, 36.2.24, 36.2.26
JEI Versions Tested: 7.7.1.139, 7.7.1.145

I have tested this with only Forge and JEI installed, no other mods and it still occurs.

**Comment by ghost** [comment]
I have also been having this problem, in Enigmatica 6. I did discover that if I use my mouse software to rebind a side button to 'u', it works as expected. Trying to bind the button directly, as per the OP, doesn't work.

**Comment by mezz** [comment]
Thanks for the report! This has been fixed in the latest version `9.4.1.99`, which should be available shortly.
I'll work on backporting this to 1.16.

Please note that you will still not be able to use left-click, right-click, or middle-click because these keys conflict with the vanilla gui's normal behavior. Other buttons should work now.
