### ISSUE TITLE
Color search gets Pink and Black for items with no particle texture

### ISSUE THREAD

**Issue by dblsaiko** [mezz/JustEnoughItems#283]
I have the Charset mod installed and the redstone wires (maybe all multiparts?) show up in color search as "HotPink, Black", (the missing texture). 
Picture: http://i.imgur.com/mYLQNaC.png
Using Minecraft 1.9.4

**Comment by mezz** [comment]
Thanks for the report!
Custom models don't have a standard texture to grab, so I use the "particle" texture for items like that. It looks like these wires have no breaking particles, when I break some it doesn't show any.

First: please ask Charset about the lack of particles and link to this issue. It may be overlooked, or it may be intentional.

Second: I should find a better way to get item colors, like drawing them to a buffer and then reading that. This change will probably not happen soon though.

**Comment by dblsaiko** [comment]
Thank you, I will ask the dev of Charset about it

**Comment by asiekierka** [comment]
It's a bug.
