### ISSUE TITLE
[Crash]: Securitycraft JEI crash

### ISSUE THREAD

**Issue by xBlackPoison357x** [mezz/JustEnoughItems#2849]
### Steps to Reproduce the Crash

Attempting to craft securitycraft items crashes the game.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/all-the-mods-7

### Mod Pack Version (Optional)

All the Mods 7 0.4.10

### Crash Report

https://pastebin.com/QnHDaUZE

**Comment by awbuckst11181999** [comment]
I also have this problem!

**Comment by mezz** [comment]
Thanks for the report!
I have submitted a fix here: https://github.com/mezz/JustEnoughItems/commit/17dbee8cd6ae06279b2269ef1c75a265e95bbdc5
Please try using JEI `1.18.2-9.7.0.209`

Unfortunately this crash was caused by another mod's JEI plugin crashing. JEI was supposed to write a log about the crash, but ended up crashing itself :(
The new JEI version should log the other mod's crash correctly, please report it to them.
