### ISSUE TITLE
[Bug]: Ghost ingredient handler never completes

### ISSUE THREAD

**Issue by raoulvdberge** [mezz/JustEnoughItems#2873]
### Steps to Reproduce the Bug

I've written a ghost ingredient handler for RS2 (on both Fabric and Forge, it uses the same code).

I'm noticing that on Forge, Target#accept is called sucessfully.
On Fabric, Target#accept is never called, even though I did drag it successfully onto the target.

### Expected Behavior

Target#accept needs to be called properly on Fabric.

### Actual Behavior

Target#accept isn't being called.

### Extra Notes (Optional)

**JEI v11.0.0.206, only on Fabric.**

**Comment by mezz** [comment]
Thanks for reporting!
This has been fixed in the latest version, please let me know if you run into any other issues.

**Comment by raoulvdberge** [comment]
Is it fixed in version jei-1.19-fabric-11.0.0.222?
The ghost ingredient handler still never calls #accept.

https://github.com/refinedmods/refinedstorage2/blob/fix/177/ghost-ingredients/refinedstorage2-platform-fabric/src/main/java/com/refinedmods/refinedstorage2/platform/fabric/integration/jei/GhostIngredientHandler.java

I can see the blue placeholders, but as soon as I drag it onto it, nothing happens.

**Comment by mezz** [comment]
Oops, thanks for letting me know. 
I checked that the ghost ingredient was treated as completed successfully, but didn't check that the target actually received the item. I was able to reproduce the issue as you described it.

This should be fixed in the next version, I was just calling the wrong method on mouse-up for Fabric.
