### ISSUE TITLE
[Crash]: Upon loading new world or joining an existing one in singleplayer 

### ISSUE THREAD

**Issue by PantsWP** [mezz/JustEnoughItems#2904]
### Steps to Reproduce the Crash

1. Create new or join existing world
2. Crash to desktop

### Extra Notes (Optional)

Running JEI version 1.18.2-9.7.0.229 on Forge version 40.1.68; no crash when JEI was removed

### Crash Report

https://gist.github.com/PantsWP/4396ba03d7ed59ca7437132403a7ad4e

**Comment by mezz** [comment]
Thanks for the report!

`Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [rubidium_extras.mixins.json:JEI.IngredientListOverlayMixin] from phase [DEFAULT] in config [rubidium_extras.mixins.json] FAILED during APPLY`

This crash is caused by Rubidium Extras, I have reported this issue to them here: https://github.com/TeamDeusVult/MagnesiumExtras/issues/26
