### ISSUE TITLE
API: Add method for getting the hovered ItemStack in any context

### ISSUE THREAD

**Issue by squeek502** [mezz/JustEnoughItems#292]
For AppleCore, I am currently doing some ugly hackery to retrieve the currently hovered stack from JEI. It'd be nice to have a single API method that would return the hovered ItemStack from any of the currently applicable JEI Gui elements (ItemListOverlay, GuiRecipes, etc). From what I can tell, InputHandler currently has some methods similar to this, but none are available through the API.

Barring that, adding a `getStackUnderMouse` method to `IRecipesGui` (a la `IItemListOverlay`) would also make getting the ItemStack fairly easy. Then I'd be able to do something like:

``` java
GuiScreen curScreen = Minecraft.getMinecraft().currentScreen;
ItemStack hoveredStack = null;

if (curScreen instanceof IRecipesGui)
{
    hoveredStack = ((IRecipesGui) curScreen).getStackUnderMouse()
}
if (hoveredStack == null)
{
    IItemListOverlay overlay = runtime.getItemListOverlay();
    hoveredStack = overlay.getStackUnderMouse();
}
```

Let me know if I'm missing something that makes this already possible.

**Comment by mezz** [comment]
I think you should PR Forge to add utility method for drawing itemstack tooltips. See what I did with adding `GuiUtils.drawHoveringText` [in this PR](https://github.com/MinecraftForge/MinecraftForge/pull/2650/files). Basically I just rerouted the vanilla method to a public `GuiUtils` call and then add functionality there.

I think you should add `GuiUtils.renderToolTip` that has proper event hooks for what you need.
Then you can direct mods like JEI to use it, instead of needing specific support for each mod.

**Comment by squeek502** [comment]
That's fair (and especially relevant for a separate very specific request I was going to make), although I think this request would be a decent addition to the JEI API regardless. Any reasons for `IItemListOverlay` having a `getStackUnderMouse` method should apply to `IRecipesGui` as well, right?

**Comment by mezz** [comment]
I will add it if someone really needs it, but I'm pretty convinced that this PR is the way to go. I think it will make your life easier in the long run as well since it wouldn't break across Minecraft versions.
I'm much more likely to accidentally break a hook I don't use myself. I've already done it a few times so I'm reluctant to add more things like that.

**Comment by squeek502** [comment]
Fair enough. Note that the only internal usage of `IItemListOverlay.getStackUnderMouse` is [in the debug recipe handler](https://github.com/mezz/JustEnoughItems/blob/c94fb63a40283c486624dee010955a567da72fb8/src/main/java/mezz/jei/plugins/jei/debug/DebugRecipeCategory.java#L67).

Appreciate the quick responses. :+1:

**Comment by mezz** [comment]
Should be solved by https://github.com/MinecraftForge/MinecraftForge/pull/3034

**Comment by mezz** [comment]
Leaving this open actually, since I will need to use the new GuiUtils method with itemstacks for it work properly.

**Comment by mezz** [comment]
Fixed in https://github.com/mezz/JustEnoughItems/issues/388
