### ISSUE TITLE
[Crash]: Ingredient Rendering with OptiFine + AA/AF on (1.12.2)

### ISSUE THREAD

**Issue by jakey1995abc** [mezz/JustEnoughItems#2931]
### Steps to Reproduce the Crash

1. Install any modpack containing JEI (I use RAD) and add Optifine
2. Enable antialiasing and anisotropic filtering in OptiFine options
3. Press E and browse through recipe pages (typing "SM" in search makes it crash)
4. Enjoy crashing when any one of many specific modded items are rendered in the menu

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons

### Mod Pack Version (Optional)

R.A.D. - 1.51

### Extra Notes (Optional)

This issue has been around for years now and is still not fixed in OptiFine for Minecraft 1.12.2, despite being reported as a major bug many times. Our last hope is that you are able to fix this game breaking bug.

### Crash Report

https://gist.github.com/jakey1995abc/4baae3d19f34e9c721758a3d7c1af3a4

**Comment by mezz** [comment]
Thanks for the report!
```
-- Ingredient being rendered --
Details:
	Mod Name: OpenBlocks
	Registry Name: openblocks:glyph
	Display Name: 'a' Glyph
	String Name: 1xitem.openblocks.glyph@97
```
This is an old bug in Optifine, reported here: https://github.com/sp614x/optifine/issues/2267
Unfortunately it is still not fixed, as you said.

JEI is not really involved in this crash. One workaround might be to add `openblocks:glyph` to the blacklist in JEI so that it doesn't show up.
