### ISSUE TITLE
[Solved]: Typing E in the search closing inventory. (Debugyfy Conflict)

### ISSUE THREAD

**Issue by murao-kun** [mezz/JustEnoughItems#2942]
### Steps to Reproduce the Bug

1. Click JEI search.
2. Type E.

### Expected Behavior

To type letter E.

### Actual Behavior

UI closing.

### Extra Notes (Optional)

Actual for forge 43.0.0 and jei [11.2.0.243](https://www.curseforge.com/minecraft/mc-mods/jei/files/3920263)

**Comment by crcabanillas** [comment]
Thought I was taking crazy pills. Having the same issue with 10.1.3.240 and Forge 40.1.51

edit: this is caused by Debugify's fix for MC-147605. Disabling that "fix" will solve this issue as per issue #2927 discussion. Incidentally this also fixes not being able to click out of a text field which was affecting mods like Controlling.

**Comment by murao-kun** [comment]
Thank you, that really helps!

**Comment by mezz** [comment]
It looks like this has been fixed in the latest version of Debugify https://github.com/isXander/Debugify/issues/74

**Comment by murao-kun** [comment]
> It looks like this has been fixed in the latest version of Debugify [isXander/Debugify#74](https://github.com/isXander/Debugify/issues/74)

They do not support forge anymore.. I am stuck on old version.
