### ISSUE TITLE
Jei wont work when i try to launch it, even with the max amount of RAM (12288MB) on curseforge. 

### ISSUE THREAD

**Issue by KristinaUndCookie** [mezz/JustEnoughItems#2990]
### Steps to Reproduce the Crash

put JEI in 1.12.2, get a ton of other mods with it and start up minecraft normal. wait 100 years and it will crash and give you the error

### Extra Notes (Optional)

i use a lot of mods where i already had to do stuff to get it working, but now the problem is jei? it always worked before on 1.12.2 with many mods, im not sure why now. ive tried removing mods, too.

### Crash Report

https://gist.github.com/KristinaUndCookie/5257a35a0962c722ca87773e73710a58

**Comment by mezz** [comment]
Thanks for the report!

Yeah it's taking forever because it's running out of memory and struggles for a while before it finally gives up and crashes.
`Caused by: java.lang.OutOfMemoryError: Java heap space`

your memory settings are visible here in the log too:
```
	Memory: 57071248 bytes (54 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
```

It looks like it is actually running with only 2 GB ram (2048 MB) despite what you set in the launcher. 
You'll have to do some troubleshooting there to find out how to set the ram amount correctly.

**Comment by KristinaUndCookie** [comment]
thank you, but how would that work? im not very experienced with computers, and only know the basics. are there any tutorials on how to find out?

**Comment by KristinaUndCookie** [comment]
also it works when i start it with curseforge, but when i try it with the normal installed minecraft launcher it crashes. does that have to do with anything?

**Comment by mezz** [comment]
I think you will need to launch from curseforge in order for it to use your memory settings. 
Otherwise you will need to customize your launch profile in the minecraft launcher to take custom arguments for more memory.
