### ISSUE TITLE
Chinese infix

### ISSUE THREAD

**Issue by DRdora** [mezz/JustEnoughItems#300]
Chinese cant be written in JEI，I hope it can be fixed！thx！great honor！

**Comment by mezz** [comment]
Thank you for the report!
I use the same text box as Minecraft. Do they have support for Chinese text?
@3TUSK do you know more about this?

**Comment by 3TUSK** [comment]
IIRC it is a vanilla bug that fixed in 1.9....

Edit: Chicken-Bones/NotEnoughItems#89, also call author of [InputFix](https://github.com/zlainsama/InputFix) @zlainsama, I bet he knows more about it.

Edit: By saying _vanilla bug_ I means this: https://bugs.mojang.com/browse/MC-2781

**Comment by zlainsama** [comment]
I think they adopted the patch in vanilla, It is fixed in vanilla for windows platform.
The problem happened here is that you only pass pressed keys (keys are not characters) into your gui components, which means what sent by InputMethod don't get processed.

The InputMethod send keyEvents with a key of 0 and a character.

**Comment by mezz** [comment]
Thanks, that's just what I needed to know.

**Comment by mezz** [comment]
This should be fixed in 3.6.7, I changed my keyboard to Chinese and was able to type some random characters. Please let me know if something is wrong.

**Comment by 3TUSK** [comment]
theoretically this also provide support to any language that require InputMethod (e.g. Japanese), correct?

**Comment by zlainsama** [comment]
Yes, it should, at least in windows platform.
