### ISSUE TITLE
[Bug]: JEI creates ‘ghost items’ in your inventory

### ISSUE THREAD

**Issue by Nevrai** [mezz/JustEnoughItems#3007]
### Steps to reproduce the bug

1. Set JEI’s cheat mode to give mode and then give yourself items.
2. Move them around in your inventory and/or delete them.
3. Open a chest or other inventory, and they will re-appear.

### Expected behaviour

When I give myself items with JEI’s cheat mode (set to inventory mode rather than mouse pickup) and move them around in my inventory or delete them using JEI, they stay in my inventory. They are invisible, and I can’t see them; however, they’re still there. If I open an inventory like a chest, they re-appear in my inventory. I also notice that when I give myself new items, they don’t go in the first empty slot, which is because that slot is not truly empty. I can also drop these ghost items, or place them if they’re blocks, but I can’t see them in my inventory until I open some form of GUI like a chest. Items are essentially cloned when I move them around in my inventory or delete them, and it happens constantly, with practically every single item I give myself with JEI, so my inventory is constantly full of “ghost” items. It only happens when I give myself items with JEI, not when using the /give command or creative menu. This didn’t use to be the case, so it may be an issue with one of the latest JEI or Forge versions.

[**Here is a video of the bug in action.**](https://i.imgur.com/6br5bVK.mp4)

### Versions
* **Minecraft:** 1.18.2
* **Forge:**  40.1.80 (latest for 1.18.2)
* **JEI:** 9.7.2.264 (latest for 1.18.2)

**Comment by Nevrai** [comment]
After some further testing, I've found that this only happens in creative mode, not in survival mode.

It also happens in an instance with very few mods installed, so whilst it’s still _possible_, it’s unlikely that it’s caused by a different mod. I hope this can be fixed, as it’s quite frustrating.

**Comment by mezz** [comment]
Thanks for the report!
Unfortunately I was not able to reproduce this bug, even with your clear instructions.

Are you playing single-player or on a server? 
If you're on a server, is JEI installed on the server? 
Can you try this out with only JEI installed, without other mods?

**Comment by DeleteMetaInf** [comment]
@mezz I tested this in a completely fresh instance of the game, with no mods other than JEI installed, on the latest version of Forge and with the latest version of JEI for 1.18.2. Also tested it on Forge 40.1.80 on the same instance. It is still happening. I didn’t change any options except changing JEI’s give mode from mouse pick-up to inventory.

[**Here is another video I took, demonstrating the bug.**](https://i.imgur.com/YXOt9Mg.mp4)

As you can see in the video, items you’ve given yourself with JEI are duplicated into “ghost items” by simply giving yourself items with JEI’s cheat mode enabled, in creative mode, and then deleting items by moving them to either side of your inventory. The items aren’t properly deleted, and they re-appear when you interact with a block that has a GUI, such as a chest or crafting table, or use an item that has a GUI. The same happens if you move items inside your inventory rather than deleting them.

This only happens if you’re in creative mode, and it doesn’t happen if you delete the items by moving them into the creative tab, but it does happen if you delete the items by moving them over JEI’s HUD in your inventory or move them around in your inventory.

This issue happens every time I give myself items with JEI and delete or move them.

### Steps to reproduce the bug

1. Give yourself items with JEI, with cheat mode enabled, whilst you’re in creative mode.
2. Delete those items by moving them over JEI’s HUD; or move them around in your inventory.
3. Give yourself more items with JEI, and you’ll notice that they don’t go into the first available slots, as those slots are actually occupied by these invisible items.
4. Open any kind of block or item GUI, such as a chest, and you’ll see the items re-appear in your inventory.

### Versions
* **Minecraft:** 1.18.2
* **JEI:** 9.7.2.266 (latest)
* **Forge:** Tested on 40.1.80 and 40.1.84 (latest)

**Comment by Nevrai** [comment]
@mezz I’m playing in single-player. I tested this in a completely fresh instance of the game, with no mods other than JEI installed, on the latest version of Forge and with the latest version of JEI for 1.18.2. Also tested it on Forge 40.1.80 on the same instance. It is still happening. I didn’t change any options except changing JEI’s give mode from mouse pick-up to inventory.

[**Here is another video I took, demonstrating the bug.**](https://i.imgur.com/YXOt9Mg.mp4)

As you can see in the video, items you’ve given yourself with JEI are duplicated into “ghost items” by simply giving yourself items with JEI’s cheat mode enabled, in creative mode, and then deleting items by moving them to either side of your inventory. The items aren’t properly deleted, and they re-appear when you interact with a block that has a GUI, such as a chest or crafting table, or use an item that has a GUI. The same happens if you move items inside your inventory rather than deleting them.

This only happens if you’re in creative mode, and it doesn’t happen if you delete the items by moving them into the creative tab, but it does happen if you delete the items by moving them over JEI’s HUD in your inventory or move them around in your inventory.

This issue happens every time I give myself items with JEI and delete or move them.

### Steps to reproduce the bug

1. Give yourself items with JEI, with cheat mode enabled, whilst you’re in creative mode.
2. Delete those items by moving them over JEI’s HUD; or move them around in your inventory.
3. Give yourself more items with JEI, and you’ll notice that they don’t go into the first available slots, as those slots are actually occupied by these invisible items.
4. Open any kind of block or item GUI, such as a chest, and you’ll see the items re-appear in your inventory.

### Versions
* **Minecraft:** 1.18.2
* **JEI:** 9.7.2.266 (latest)
* **Forge:** Tested on 40.1.80 and 40.1.84 (latest)

**Comment by mezz** [comment]
There was a race condition bug in the way I was handling packets between the client and server, I think it may have caused this issue. (this also affects single-player, which acts as both client and server together)

I have fixed the packet handling in these commits https://github.com/mezz/JustEnoughItems/commit/5b3318761f964467bf61e40da9c5d8cce11b77f0 https://github.com/mezz/JustEnoughItems/commit/d503a1174a52f15e55c27adb9f1d54acdbfd31d8

The fix will be released in JEI version `9.7.2.281` and version `10.2.1.280`.
Please try out one of these versions and let me know if you still encounter the bug.
