### ISSUE TITLE
[Bug]: jei配置界面打不开，尽管已经安装了FTB及其前置mod

### ISSUE THREAD

**Issue by yjq010709** [mezz/JustEnoughItems#3038]
### Steps to Reproduce the Bug

jei配置界面打不开，尽管已经安装了FTB及其前置mod，我用的是farbic

### Expected Behavior

jei配置界面打不开，尽管已经安装了FTB及其前置mod，我用的是farbic

### Actual Behavior

jei配置界面打不开，尽管已经安装了FTB及其前置mod，我用的是farbic

**Comment by mezz** [comment]
Thanks for the report!
Sorry I can only read English.
You can edit the config file `jei-client.ini`

**Comment by LittleYe233** [comment]
这个 issue 可能与 #155 #2521 #2533 重复。

出现这个问题的一个原因可能是 FTB Library 并不能有效地为 JEI 提供支持。作者已经在这些 issues 中给出了解释，并释出了依赖 [Configured](https://www.curseforge.com/minecraft/mc-mods/configured) mod 的新版本。以 1.16.5 为例，经测试最新版 7.7.1.153 可以正常打开游戏内配置菜单。

This issue may duplicate with #155 #2521 #2533.

Maybe this problem happened because FTB Library mod could not support JEI well. The author has given an explanation in these issues, and released new versions that depend on [Configured](https://www.curseforge.com/minecraft/mc-mods/configured) mod. For instance, 7.7.1.153, the latest version of the mod for Minecraft 1.16.5, allows players to open the in-game config menu.
