### ISSUE TITLE
[Crash]: i cant open JEI in version 1.19.2

### ISSUE THREAD

**Issue by HouttuyniaFPS** [mezz/JustEnoughItems#3080]
### Steps to Reproduce the Crash

1.open  MC 1.19.2
2.because the JEI, i cant open  MC 1.19.2

### Mod Pack Version (Optional)

jei-1.19.2-fabric-11.5.0.297.jar

### Crash Report

https://gist.github.com/HouttuyniaFPS/0cd93877f2865c2c27b6b6bb7c2f3c1a

**Comment by gamenTV** [comment]
Working Version: 11.4.0.290

**Comment by DesertCookie** [comment]
> Working Version: 11.4.0.290

Indeed, I can confirm that rolling back to this version solved my issue.

**Comment by mezz** [comment]
Thanks for the report!
I am not entirely sure what is causing this issue, I am asking Fabric devs to see if I can get more info on it.

**Comment by mezz** [comment]
Unfortunately they have determined that this is caused by `optifabric`. 
Please try removing that mod and see if it resolves the issue for you.

**Comment by DesertCookie** [comment]
If I remember correctly, I didn't have that installed at the time as I had determined it to cause issues with another mod already.

Trying again with the latest 11.6.0.1011 and @HouttuyniaFPS' 11.5.0.297 though, there don't seem to be any issues. Sadly, I don't remember which versions originally had issues for me.

Even if they still were a problem though, since there are newer working versions, I'd consider this fixed.
