### ISSUE TITLE
Too much payload using IRecipeTransferHandler

### ISSUE THREAD

**Issue by KidsDontPlay** [mezz/JustEnoughItems#312]
Can you help me with this?

Original issue: https://github.com/MrRiegel/Storage-Network/issues/49

Code: http://pastebin.com/jzCYS9wM

**Comment by mezz** [comment]
If I'm looking at this correctly, you are sending the entire list of gui ingredients to the server. In your case, I assume this list is super huge.
If you can use the client to eliminate ingredients that you don't have, you can send less data.

If that is not possible, you can try to use the ore dictionary to check if a list of ingredients for a slot is actually just a list of one oreDictionary name. Usually if an ingredient is a huge list, it's because it's an oreDict ingredient. You can send that name instead of the whole list. Here's my code for checking if some list is equal to an ore dictionary name:
https://github.com/mezz/JustEnoughItems/blob/1.9/src/main/java/mezz/jei/util/StackHelper.java#L53-L71

**Comment by KidsDontPlay** [comment]
It works now
Thanks
