### ISSUE TITLE
[Bug]: Developer toml not saving edits after server restart

### ISSUE THREAD

**Issue by AbandonedPlayer** [mezz/JustEnoughItems#3163]
### Steps to Reproduce the Bug

- Open configured.developer.toml
- Edit: "enabled = false" to true 
- Add player UUID between brackets
- OP player UUID in server console
- Restart Server

### Expected Behavior

Editing line: enabled = false to true and adding UUID of player with OP is supposed to give player permissions to edit server configs while in-game.

### Actual Behavior

After completing the steps above, the configured.developer.toml is reset to enabled = false and erasing player UUID from configured.developer.toml.

### Extra Notes (Optional)

This is a problem with the Forge variant version number 11.6.0.1011 and 11.6.0.1013 for minecraft version 1.19.2

### latest.log

https://gist.github.com/AbandonedPlayer/a2ee9a78ecef728c9eadc5320a37252a

**Comment by whitey0409** [comment]
Unsure if my case is the exact same as OP, but I am facing a similar problem with my ATM8 Modded Minecraft Server.  Everytime I start the server after editing configured.developer.toml, a new reverted version of this file is created and the edited version is changed to configured.developer.toml.bak. It appears this file can not be edited, which is inhibiting the ability to modify server mod configs.

I can not find another post about this anywhere, but there have been no changes to any other configs in the server directory, and this behavior is repeatable any time I edit this file. 

The server is also fully closed during edits, ruling out the possibility of the file not being editable due to being loaded into RAM.

**Comment by AbandonedPlayer** [comment]
> Unsure if my case is the exact same as OP, but I am facing a similar problem with my ATM8 Modded Minecraft Server. Everytime I start the server after editing configured.developer.toml, a new reverted version of this file is created and the edited version is changed to configured.developer.toml.bak. It appears this file can not be edited, which is inhibiting the ability to modify server mod configs.
> 

I didn't notice this when I was running the server. I thought it was just from using Notepad++ but it happens after starting the server. This is still an issue for me and I haven't found a fix.
