### ISSUE TITLE
[Crash]: 1.19.4 Opening the inventory while in creative mode crashes the game 

### ISSUE THREAD

**Issue by lmore377** [mezz/JustEnoughItems#3191]
### Steps to Reproduce the Crash

1. Setup a fresh install of Fabric 1.19.4
2. Install the mod, open the game and join a world/server
3. Switch to creative mode and open your inventory

### Crash Report

https://gist.github.com/lmore377/a611848c6c7057973116456a969cfbb8

**Comment by cmar7945** [comment]
Im seeing the same thing in latest forge release

**Comment by NorthernLawOfficial** [comment]
I'm unable to even launch using Prism Launcher with Fabric. Every mod works except for JEI. Getting the error code:
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Fabric Loader' (fabricloader) 0.14.17 with version 0.14.19 or later.
Unmet dependency listing:
	 - Mod 'Just Enough Items' (jei) 13.1.0.6 requires version 0.14.19 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.17!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

**Comment by lmore377** [comment]
> Replace mod 'Fabric Loader' (fabricloader) 0.14.17 with version 0.14.19 or later.

The fix is literally right there in the error. Either update fabric or use an earlier mod version

**Comment by NorthernLawOfficial** [comment]
Well that's the obvious answer but the whole point is to move forward, I know the earlier versions worked, but I'm trying to play on the newest one. Also the error message states "0.14.19 or later" I've tried updating Fabric to no avail, I know it seems like an "obvious" fix but I did try that and it just didn't work. I have the latest version and for some reason it still shows it as "0.14.17" which literally isn't true, looking at what I have downloaded right now and it's the latest one. 
The thing I might be wrong about is if the issue is with JEI or Fabric, I honestly have no idea, because every other mod works fine.
I recognize I could be doing something really stupid here but I just don't see it.

**Comment by lmore377** [comment]
When you click edit instance in the versions tab does it show the latest version of fabric?

![Screenshot_20230421_130838_VNC Viewer.jpg](https://user-images.githubusercontent.com/24685455/233715840-feeb45f0-4599-480a-b183-bd13c3e1d2de.jpg)

**Comment by lmore377** [comment]
When you click edit instance under the versions tab does it show the latest version of fabric?

![Screenshot_20230421_130838_VNC Viewer.jpg](https://user-images.githubusercontent.com/24685455/233715840-feeb45f0-4599-480a-b183-bd13c3e1d2de.jpg)

**Comment by NorthernLawOfficial** [comment]
Same as yours 
![image](https://user-images.githubusercontent.com/92351169/233720217-a44ea7fb-648e-48f1-89c1-96513b6735b5.png)
