### ISSUE TITLE
[Bug]: Late Reload

### ISSUE THREAD

**Issue by FooterManDev** [mezz/JustEnoughItems#3204]
### Steps to Reproduce the Bug

Load the game [1.19.2]
Open a world
Attempt to hide or Unify something with KubeJS or Almost Unified
Run /reload
Check if items are hidden. They should not be
Run /reload again
Check if items are hidden. They should be

Additionally:
Load into a world
Check for hidden items. Nothing should be hidden
Run /reload
Check for items again. They should be hidden.

### Expected Behavior

JEI hides recipes / items hidden by 3rd party.

### Actual Behavior

JEI Reload's it's list late, and required /reload to be cast twice.

### Mod Pack URL (Optional)

https://legacy.curseforge.com/minecraft/modpacks/fun-in-the-sky

### Mod Pack Version (Optional)

Alpha - 0.1.0.1

### latest.log

https://gist.github.com/FooterMan15/cd8a031984897c094a19cfea828f52c7

**Comment by FooterManDev** [comment]
Well I'm still here 🤷

**Comment by FooterManDev** [comment]
I noticed

**Comment by FooterManDev** [comment]
yeah buddy, I noticed

**Comment by mezz** [comment]
Thanks for the report!
Sorry but I am not sure I understand the origin of the bug here completely. 
It is up to these mods to hide items when JEI reloads. Maybe there is a race condition where they apply their changes to JEI differently each time. Can you open a bug with the other mod and link back to this issue?
