### ISSUE TITLE
[Suggestion]: Recipe Tree / Graph

### ISSUE THREAD

**Issue by slava110** [mezz/JustEnoughItems#3279]
### Suggestion

Sometimes it's hard to understand how to craft certain things in complex modpacks. I'd like to suggest recipe tree/graph feature inspired by EMI recipe tree.
![image](https://github.com/mezz/JustEnoughItems/assets/26705162/3fc97c62-fe93-42ad-9d7f-4b62749eb429)

**Comment by slava110** [comment]
.

**Comment by slava110** [comment]
Stale bot is annoying

**Comment by mezz** [comment]
Thanks for the request!
I have worked to provide JEI's recipe plugin support via the API, so that EMI and other mods can use that information when JEI is installed.
The EMI dev is (understandably) not interested in moving the recipe graph feature into JEI though. 
I think it makes sense to use both mods together if you want this feature.

**Comment by slava110** [comment]
Could it be implemented in JEI without EMI though? When I've tried using EMI and JEI in the past but had a lot of issues with this setup :c Would be cool to have something like that in JEI without EMI

**Comment by mezz** [comment]
I think that's something you could request from the dev of EMI, I am unlikely to just clone the feature.
Maybe it could be implemented as a JEI addon mod.
