### ISSUE TITLE
[Crash]: fml.modloading.dupedmod

### ISSUE THREAD

**Issue by AriusDesu** [mezz/JustEnoughItems#3292]
### Steps to Reproduce the Crash

1) Launch Minecraft 2) Wait for the download to the main menu of the game 3) See the error

### Mod Pack Version (Optional)

1.16.5

### Extra Notes (Optional)

The same error appears in the case of the Hwyla mod, but disabling it solves the problem. However, disabling JEI entails 580 new errors in the main menu of the game. The error also appears on later versions of the game. Tested on 1.12.2 and 1.19.4. I'm playing with my mods build.

### Crash Report

<script src="https://gist.github.com/AriusDesu/902c72e49c90ad1c6529e9a8b8177306.js"></script>

**Comment by Beee3po** [comment]
Did you end up figuring out the problem? I have a similar problem but I installed Roughly enough resources (RER) which also installed REI and now disabling JEI or REI and RER crashes my game and having both just says their is a mod dupe....

**Comment by Beee3po** [comment]
> Did you end up figuring out the problem? I have a similar problem but I installed Roughly enough resources (RER) which also installed REI and now disabling JEI or REI and RER crashes my game and having both just says their is a mod dupe....

I figured out my problem, might be helpful if you are still stuck with something similar down the road. By disabling REI and RER I was left with Exit Code: 1 which means I have an out dated mod that was also enabled. So I went through all my mods disabling them by group and then individually until I found the culprit. Project E which I disabled prior got reenabled and was causing the entire launcher to have an break down. 

**Also with Hwyla mod you might already have a mod that does what that mod already does so that's probably why you got a mod dupe.**
