### ISSUE TITLE
What Happened to the Project?

### ISSUE THREAD

**Issue by catzs** [mezz/JustEnoughItems#33]
Title

**Comment by Doty1154** [comment]
I think the guy just gave up and moved to something else. I mean i would have given up this is a major project and no one really wanted to help adopt it..

**Comment by mezz** [comment]
I was blocked for a long time (since last November) by Forge because I needed a PR accepted: #23
Now it's fixed, but only for Minecraft 1.8, and nobody is modding there yet.
In the meantime I've been busy with Forestry.

I'll continue working on this if cpw backports my [Forge PR](https://github.com/MinecraftForge/MinecraftForge/pull/1506) to 1.7.10, or when modding looks like it will finally start to move to 1.8+. I may get going with moving it to 1.8 anyway, just to get a head start.

**Comment by mezz** [comment]
Pushed some updates for 1.8
