### ISSUE TITLE
[Crash]: Create Render Crash

### ISSUE THREAD

**Issue by Pineappleguy03** [mezz/JustEnoughItems#3319]
### Steps to Reproduce the Crash

1: Search for create:wand_of_symmetry
2: Crash

### Crash Report

https://gist.github.com/Pineappleguy03/91868c876088a299bef57a6f86d1d3e4

**Comment by mezz** [comment]
Thanks for the report!
Sorry for the late reply.

When there is only one mod involved in a crash with JEI, please report it to the other mod first.
 * Every mod that has custom recipes creates a plugin for JEI in their mod, and that can be a source of crashes.
 * Another common type of crash comes from rendering items. JEI renders items the same way as the creative menu and is most likely not a direct cause of item-rendering crashes.

If the devs find that the issue is because of JEI, please reopen an issue here and link to the other mod's issue to help with communication.
I am glad to look into suspected JEI issues or help debug trickier problems.
