### ISSUE TITLE
[1.10] Crash looking up recipe

### ISSUE THREAD

**Issue by Morpheus1101** [mezz/JustEnoughItems#332]
http://pastebin.com/sdj8e8HX - with JER

http://pastebin.com/9aFAfwYf - without JER

To me looks exactly the same

**Comment by KnightMiner** [comment]
Try it without FEI, that mod tends to be installed (as opposed to JER which is relatively stable)

**Comment by mezz** [comment]
Please do not report here first if you have FEI installed, here is the FEI issue tracker:
https://github.com/elix-x/Forever-Enough-Items/issues

**Comment by Morpheus1101** [comment]
FEI adds in the functions that JEI dosent, least that is why i use it :)

**Comment by AEnterprise** [comment]
@Morpheus1101 it does but it hooks deep into JEI for that so if JEI crashes with FEI installed, often it's FEI causing the crash

**Comment by Morpheus1101** [comment]
All good, now i know to just report any issues that maybe JEI to FEI first.  I am curious to the decision behind removing the Creative//OP functions NEI had from JEI though

**Comment by KnightMiner** [comment]
NEI was a general utility mod, JEI is just a recipe viewer and item list. The goal is to contain just the required features for that in order to be more lightweight and easier to maintain.

Plus it lets other mods take care of the non-recipe viewing features as everyone is going to install a recipe viewing mod, and no one wants redundant features.
