### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Flame37** [mezz/JustEnoughItems#3379]
### Steps to Reproduce the Bug

Download JEI and try to type

### Expected Behavior

It won't let you type

### Actual Behavior

It wont let me type

### latest.log

https://gist.github.com/Flame37/867e295dc8c036509b90d21e057b72d3

**Comment by ghost** [comment]
![image](https://github.com/mezz/JustEnoughItems/assets/107043954/6d965119-fe67-4d1c-a052-b28d2ea5c7b1)

this is what your latest log shows?

**Comment by Flame37** [comment]
That's what the log was.

**Comment by mezz** [comment]
Thanks for the report!

It seems like another mod is conflicting with JEI or causing an issue here.
Please try to see if this bug happens with JEI alone, and then try removing mods to figure out which one is causing a problem.

If you find that there is only one other mod causing an issue, please report it to them and link back here.
Otherwise if you still can't figure it out, please paste your new crash log and client logs here, and I can help debug or find the right place to report to.
