### ISSUE TITLE
[Crash]: End Remastered Crash

### ISSUE THREAD

**Issue by IamGallito** [mezz/JustEnoughItems#3391]
### Steps to Reproduce the Crash

1 toggle cheat mode in JEI
2 search for End remastered mod
3 cheat in 1 eye from mod

### Crash Report

https://gist.github.com/IamGallito/5c7e7c7ac77ff0d29f51df88122ab54c

**Comment by Xplodin** [comment]
Also getting this error on my own pack

**Comment by IamGallito** [comment]
Resolved, install REI instead for fabric loader

**Comment by mezz** [comment]
Thanks for the report!
This seems to be happening when JEI calls Minecraft to tell it to sync the inventory to the client.
I think there is another mod involved that is causing the underlying issue, can you try removing some mods until this issue goes away, in order to identify which mod is causing the problem?
