### ISSUE TITLE
[Bug]: FPS down

### ISSUE THREAD

**Issue by Krimatoria** [mezz/JustEnoughItems#3393]
### Steps to Reproduce the Bug

FearNightfall + insanity Shader

### Expected Behavior

FPS 60+ please) 

### Actual Behavior

FPS drops when opening inventory from 300 to 65 without shaders. With shaders, the situation is even worse, falling from 130 to 40.

### Mod Pack Version (Optional)

11,5

### Extra Notes (Optional)

Hiding the OU before searching in the Embeddium setting gives an increase of +20, but then you don't see the recipes. Yes, there are many of them, but 40 BASICS is a disaster.  https://pasteboard.co/9a8eJjYdX8TI.png

Tips or suggestions for improvement if possible.

**Comment by mezz** [comment]
Thanks for the report!
You can constrain the size of the JEI Ingredient List in your configs so that it has fewer rows or columns. 
That should let it render fewer items and run with a higher FPS.

JEI isn't doing anything special or terribly slow with the items, it should be the same as the creative menu but it shows more at once. By making it smaller, you can lower the impact.

**Comment by Krimatoria** [comment]
> Спасибо за отчет! Вы можете ограничить размер списка ингредиентов JEI в своих конфигурациях, чтобы в нем было меньше строк или столбцов. Это должно позволить ему отображать меньше предметов и работать с более высоким FPS.
> 
> JEI не делает ничего особенного или ужасно медленно с элементами, оно должно быть таким же, как творческое меню, но сразу показывает больше. Уменьшив его, вы сможете снизить воздействие.

Ok) thanks)
