### ISSUE TITLE
[Bug]: Incompatibility with owo-lib tabbed item groups

### ISSUE THREAD

**Issue by Noaaan** [mezz/JustEnoughItems#3412]
### Steps to Reproduce the Bug

-     Join a world where you have a tabbed owo-itemgroup with custom items
-     Check JEI, as its missing some items
-     Select another tab
-     Rejoin the world to reload JEI, the items are now replaced

### Expected Behavior

It is expected that all the items added into the creative tabs should be shown from the item group. 

### Actual Behavior

Currently when viewing item groups using owo-lib tabbed groups only a subset of the items show up. This subset consists of the items from the currently selected tab. Changing the tab and reloading JEI (for example by leaving and joining the world) refreshes the items displayed. 

### Extra Notes (Optional)

For more information, see related issue: https://github.com/wisp-forest/owo-lib/issues/177

Quote from glisco on this:
"There isn't much (if anything) that can be done on owo's side regarding this problem - the creative tab must necessarily report the items the way it does in order to, well, work. All items of all tabs get reported in the search tab stacks however (`getSearchTabDisplayItems` in Mojmap) - the proper fix here in my opinion is for JEI to query those instead of the normal tab stacks"

**Comment by mezz** [comment]
Thanks for the report!

I don't really understand what the other mod author means when there isn't much to be done. Maybe they could replace the vanilla GUI instead of modifying it in an incompatible way. JEI works with almost all other mods without issues, so this library should strongly consider that they are doing something very unusual and not brush off responsibility for problems too quickly.

It seems fine for JEI to load from the search tab though, I can do that. Maybe it'll be better than what I'm currently doing anyway.
