### ISSUE TITLE
PC locks up for a few seconds when first opening inventory. 

### ISSUE THREAD

**Issue by whatthedrunk** [mezz/JustEnoughItems#344]
FEI is not installed but it could be some mod causing the issue. There isn't a crash it just clocks up Minecraft for a bit. My gaming computer locks up for 1-2 seconds while my slower work PC locks up for 8 seconds. This happens to everyone running my pack ["All the Mods"](http://minecraft.curseforge.com/projects/all-the-mods). 

After the first lockup it works fine the rest of the time.

**Comment by KnightMiner** [comment]
Its a little hard to tell what is freezing your game without game logs, can you paste it onto a site such as pastebin.com or gist.github.com and link it here?

If I had to guess, the issue sounds similar to one caused by downloading game profiles for player skulls, but unless you have headcrumbs installed (which is not in "All the Mods"), there shouldn't be that many in the JEI list.

**Comment by whatthedrunk** [comment]
Let me know if this helps, there is no crash log so not sure what part you need. I just uploaded around the time I pressed E.
http://pastebin.com/ybWKLqAZ

[Here is the full log if needed. Too large for pastebin.](https://drive.google.com/file/d/0ByQjJOciCO7laFRPZUdoV0VKa0k/view?usp=sharing)

**Comment by mezz** [comment]
Thanks for the report!
I think this is related to player heads, see MinecraftForge/MinecraftForge#2835
It may be possible for me to detect slow-rendering items and remove them from the list automatically. I'll look into it.

**Comment by mezz** [comment]
I was able to detect laggy items but it really affected the startup time of JEI, potentially making people lag out when joining a server.
It looks like this really only happens from skulls, I'm going to blacklist them from JEI until this issue is solved: https://bugs.mojang.com/browse/MC-65587
