### ISSUE TITLE
[Bug]: [ATM9] JEI Drag to Delete not working on Server

### ISSUE THREAD

**Issue by westriel** [mezz/JustEnoughItems#3458]
### Steps to Reproduce the Bug

1. Install ATM9 Server and profile from Curseforge (Both downloaded March 7, 2024)
2. Gather an item (in survival in world, spawn an item, etc.)
3. Enable cheat mode
4. Drag item to right panel and left click
5. Close inventory, item reappears in inventory

### Expected Behavior

Items dragged to the right panel should be deleted on both client and server

### Actual Behavior

Item is deleted on client, but server errors out, causing desync that resyncs on inventory close and so item reappears.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/all-the-mods-9

### Mod Pack Version (Optional)

0.2.51

### Extra Notes (Optional)

Modpack has trash slot mod to work around for now. The below gist is the latest.log from the Server, if I need to upload the client log as well I can

### latest.log

https://gist.github.com/westriel/dfe20a909039d5a9f0ec9d8a16480569

**Comment by bcrotty** [comment]
I have the same issue. When JEI is on cheat mode, and I drop an item onto the right pane, the tooltip says Click to Delete, and it looks like it's deleted initially. But when I close my inventory, the item reappears. It doesn't make the sound that picking up an item makes though.

I'm playing on LAN server.

**Comment by jaywmo** [comment]
I am also getting this error with a normal server and modpack ATM9. In my case, the item deletion seems to work when in creative mode, but the error message still shows up in the logs. Otherwise in survival mode the item pops back up in my inventory.

**Comment by mezz** [comment]
Thanks for the report!

Does this happen when only JEI is installed?
Another mod may be conflicting with JEI or causing an issue here.
Please try to see if this bug happens with JEI alone, and then try removing mods to figure out which one is causing a problem.

If you find that there is only one other mod causing an issue, please report it to them and link back here.
Otherwise if you still can't figure it out, please paste your new crash log and client logs here, and I can help debug or find the right place to report to.

**Comment by jaywmo** [comment]
I tried this again with only JEI and forge on my client and server, and couldn't get the ERROR logs anymore. This was from starting with installing ATM9 modpack, then deleting all mods except for JEI. I'll raise an issue in ATM9 since I don't think I'll have time to go through 400 mods and setup my server the same way like this.

**Comment by mezz** [comment]
Thanks, I'll subscribe to the new issue and close this one for now.
Please reply here if it turns out to be an issue with JEI and I can re-open it.
