### ISSUE TITLE
[Suggestion]: jei recipe page modification

### ISSUE THREAD

**Issue by qizri** [mezz/JustEnoughItems#3482]
### Suggestion

    Pressing the U key on the item first shows all synthesizable items, from which we then select to view the item recipe.
    When the game has a large number of recipes, pressing the U key on an item, jei show all the synthesizable items for that item, and there are hundreds of pages or more to find out what it can synthesize. I think before that, it should show all synthesizable items in a slidable page. We look for items to synthesize from this page. 
   This allows you to visualize all synthesizable items and reduces page flipping.

**Comment by mezz** [comment]
Thanks for the suggestion!
I implemented something similar to this, there is a new button on the bottom-left of the Recipes GUI. It will sort the results so that synthesizable recipes are shown first.

https://x.com/mezz_mc/status/1809810314399215729

![image](https://github.com/user-attachments/assets/2d8a0c9f-f2e4-4473-a51c-9b5a9fcc87a5)
