### ISSUE TITLE
[Suggestion]: Hide Wrench and Bookmark Icons Along with Overlay

### ISSUE THREAD

**Issue by jebug29** [mezz/JustEnoughItems#3483]
### Suggestion

It would be helpful to be able to also hide the wrench and bookmarks icons when using the Ctrl-O toggle to hide the JEI overlay. JEI conflicts with another mod that I use to edit armor stands in game (Armor Stands by Roundaround), and while most of the display is fixed by using the shortcut to hide JEI, the remaining two icons get in the way.

Here is an example:
![image](https://github.com/mezz/JustEnoughItems/assets/20387989/e634b6ea-ba33-410c-9832-13acbdc5ac28)

**Comment by mezz** [comment]
Thanks for the report!

There are two solutions for this issue:

1. JEI only draws alongside screens that inherit from `AbstractContainerScreen`
Since you screen has no slots, I think it can be a normal `Screen` and not an `AbstractContainerScreen`. Changing that will mean JEI doesn't try to draw over it at all.

2. Alternatively you can create and register an `IScreenHandler` and make it always return `null`. That will tell JEI not to draw next to your `AbstractContainerScreen` at all.
https://github.com/mezz/JustEnoughItems/blob/dd5177c1657f3a01d930ba0ecbac90d7bcbed882/CommonApi/src/main/java/mezz/jei/api/gui/handlers/IScreenHandler.java
