### ISSUE TITLE
[Crash]: Client crashes when opening inventory

### ISSUE THREAD

**Issue by cdubs808** [mezz/JustEnoughItems#3494]
### Steps to Reproduce the Crash

The game crashes intermittently when I open my inventory. It freezes for a few seconds when it happens.

### Mod Pack URL (Optional)

https://www.feed-the-beast.com/modpacks/103-ftb-skies?tab=about

### Mod Pack Version (Optional)

1.5.0

### Crash Report

https://gist.github.com/cdubs808/bea2e26efcf1555105e4fb1f7fcf1e68

**Comment by duartelourenco** [comment]
Same error, same modpack.

https://pastebin.com/U5r6FmPm

**Comment by bazzcs** [comment]
exact same thing happens to me, but for Better Minecraft 4 (BMC4), and also when i press ESC

https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc4

**Comment by mezz** [comment]
Thanks for the report!
This is coming from `com.blackdragonfire.flowerdoubling`
https://modrinth.com/mod/flower-doubling/version/LrUognnq

It seems like a closed-source mod, and I don't know where to report bugs to them.
I will try catching this type of error in JEI and logging it instead of letting it crash.
