### ISSUE TITLE
[Crash]: Rendering Screen with Sophisticated Backpacked mod

### ISSUE THREAD

**Issue by Maxi90909** [mezz/JustEnoughItems#3534]
### Steps to Reproduce the Crash

I am not really sure, but in my case I added the cold and sweat mod, then removed it after it crashed trying to load my world. Then I started my world, Everything was normal until I opened the backpack inventory of the sophisticated backpacked mod. I first froze the screen then it crashed shortly after.

### Crash Report

https://gist.github.com/Maxi90909/47ef5576c9a6b939727ffc5d7efe92af

**Comment by Maxi90909** [comment]
Hi, I used a backup of my world. Because I thought it was the cold and sweat mod. That caused the issue. But no, it is litterally just the sophisticated backpack inventory and the newest version of Jei. Everytime you open the backpack inventory it crashes shortly after. Please fix this as fast as possible.

**Comment by Maxi90909** [comment]
Sorry I forgot to include I am on the newest version of Jei for 1.20.1. This one: jei-1.20.1-forge-15.3.0.6.jar

**Comment by Maxi90909** [comment]
Here are my logs. Hope that helps to fix the issue. Please fix this as fast as you can. 

[latest.log](https://github.com/user-attachments/files/15788736/latest.log)

**Comment by Maxi90909** [comment]
Only way to fix this was to install version 15.3.0.4 of Jei

**Comment by P3pp3rF1y** [comment]
This one caught my eye because of a comment on SB about the crash. Just tested with SB and JEI in a pack and I am unable to recreate and I definitely tried displaying tooltips which this seems to go to. 
@Maxi90909 have you tried with just SB and JEI to make sure that none of the other mods are source of the issue? From what I can guess from that stack trace some mod is having trouble applying its mixins when tooltip is displayed and even though based on my limited knowledge that does not necessarily rule out JEI it's really hard to say it is JEI with so many other mods in the pack.

**Comment by Maxi90909** [comment]
I haven't tried with just JEI and SB. The weird thing is, it works normaly with the JEI version from February. Not really sure what other mod this could cause since both the crash report and my logs only mention JEI Version 15.3.0.6. I have downgraded JEI to 15.3.0.4 and it works just like before. Considering the fact that there are many other people who have the same issue. I think the interface is broken with Version 15.3.0.6 of JEI. Or what perhaps also could be a reason for the crash. Some mod hasn't updated to the newest JEI Version yet. Since the JEI Update came out today, I would asume there are still issues with it and modders who haven't updated yet. The last update of JEI for 1.20.1 of Minecraft was in February.

**Comment by P3pp3rF1y** [comment]
I will be again speculating here, but to me it sounds likely some mod is modifying jei class with mixins and isn't ready for changes that were introduced in the latest version and because of that it crashes. Especially given the fact that the same issue doesn't happen with just the two mods in the pack.

**Comment by P3pp3rF1y** [comment]
actually it is right there in the log so it's Destroy mod
` Mixin [destroy.mixins.json:TooltipRendererMixin] from phase [DEFAULT] in config [destroy.mixins.json] FAILED during APPLY`

**Comment by Maxi90909** [comment]
Okay, Thats probally because the mod is still in beta. Thanks a lot for informing me.

**Comment by Maxi90909** [comment]
Let me see if I am able to remove it.

**Comment by Maxi90909** [comment]
The mod has some weird JEI intergration. Like actual elements from the periodic table. Thats probally the reason, why it crashes.

**Comment by Maxi90909** [comment]
Was able to remove it and the issue is fixed thank you.
