### ISSUE TITLE
[Bug]: Crash when trying to view certaint items use and how to obtain

### ISSUE THREAD

**Issue by Maxi90909** [mezz/JustEnoughItems#3575]
### Steps to Reproduce the Bug

1. Try to view a items use (In my case the rusted sword from epic knights)
2. Screen goes gray
3. screen is completly gray.
4. after some waiting time it disconects me from my world

### Expected Behavior

Trying to view items use doesn't make the screen of minecraft gray and doesn't disconect me.

### Actual Behavior

Screen goes slightly gray first, then completly, after some time it disconnects me.

### Mod Pack URL (Optional)

I am using a self created modpack

### Mod Pack Version (Optional)

/

### Extra Notes (Optional)

I have a lot of mods. Maybe an compatible issue

### latest.log

https://gist.github.com/Maxi90909/e2cef0443c3b1f755ff7999cf0d8461b

**Comment by Maxi90909** [comment]
This seems to only happen with tools and weapons and other items that have durability.

**Comment by mezz** [comment]
Thanks for the report!
It seems like your client is running very slowly, it may be lagging out in some situations.

The only indication of an issue that I see is here, which looks like what happens when the client is too slow:
> [10:36:27] [Server thread/INFO]: Supermaxi2208 lost connection: Disconnected
[10:36:27] [Server thread/INFO]: Supermaxi2208 left the game
[10:36:28] [Server thread/INFO]: [voicechat] Disconnecting client Supermaxi2208
[10:36:31] [Server thread/INFO]: Stopping singleplayer server as player logged out
