### ISSUE TITLE
[Other]: Items missing/not found in JEI 

### ISSUE THREAD

**Issue by gman3001** [mezz/JustEnoughItems#3604]
### Other

I am playing [Direwolf20 1.20.1 ](https://www.curseforge.com/minecraft/mc-mods/modernfix) mod pack. 
I came across items that can be crafted and used, but do not show in JEI or creative inventory. 
I found this after losing the books that are given on first spawn, trying to craft them again and not finding some of them in JEI. 
More specifically the books missing from JEI are
-industrial forgoings manual
-antcyclopedia(from antsportation mod)
-iron's guidebook(from iron's spells 'n spellbooks mods)
is there any way for a player/non dev. to troubleshoot missing items from JEI?

**Comment by mezz** [comment]
Thanks for the report!
If the item is missing from the creative menu, then I think JEI is not involved in the original problem.
JEI gets items from the creative menu, and it doesn't change the creative menu at all or hide items.

To troubleshoot, please try installing the Direwolf20 1.20.1 without any changes. If the issue is still there, please report it to them here so they can help you: https://github.com/FTBTeam/FTB-Modpack-Issues/issues
