### ISSUE TITLE
[Crash]: Crash after clicking a recipe in JEI

### ISSUE THREAD

**Issue by etmclovin** [mezz/JustEnoughItems#3642]
### Steps to Reproduce the Crash

1. click on a recipe in jei sidebar 
2. crash

### Extra Notes (Optional)

im using a custom modpack i made, its still in the early stages and ive just been playtesting it and found this crash i cant seem to fix. any help is appreciated thanks.

Edit: i did see a similar issue to do with a jei plugin, i had the fixed version installed and even after removing it the problem still persists

### Crash Report

https://gist.github.com/StrixTyphoon/02fadcae6741d59129232f833a4e223d

**Comment by mezz** [comment]
Thanks for the report!
This is a bug with `ldlib`, please try updating it to the latest version.

**Comment by etmclovin** [comment]
Thanks for looking into this, i am a little confused as im using the newest version that is on curseforge? https://www.curseforge.com/minecraft/mc-mods/ldlib/files/all?page=1&pageSize=20

**Comment by mezz** [comment]
Oh I see. In that case this is a new bug. Please report it to LDLib here: https://github.com/Low-Drag-MC/LDLib-Architectury/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen

I am currently working to add support for some features for them, so that they don't need to use mixins on JEI for their features.
Until that is finished though, the mod will often break when JEI updates its code.

**Comment by etmclovin** [comment]
Thanks, i will do
