### ISSUE TITLE
[Bug]: JEI inventory doesn't appear. At all.

### ISSUE THREAD

**Issue by JuriGagarian** [mezz/JustEnoughItems#3652]
### Steps to Reproduce the Bug

I honestly have no clue.

### Expected Behavior

JEI gui should appear on the right side of my inventory tab.

### Actual Behavior

Doesn't work. It's just not there - refuses to appear at all, even though it is loaded, and JEI keybinds are showing up in control menu. Yes, i tried ctrl+o (no, i did not rebind that shortcut) and it still doesn't show up. 

### latest.log

https://gist.github.com/JuriGagarian/305473221de5dce5aaf23e5fd3146fe6

**Comment by Orlqk** [comment]
I had the same problem but apparently, rubidium/embeddium extra makes it that the JEI gui does not show up if there is nothing typed in the search bar but that can be fixed in the config of the mod. For me I had to go in to the config of Embeddium++ and change a setting that stated HideJrei=true to false
![Screenshot (6)](https://github.com/user-attachments/assets/08036234-6e85-499e-915c-a55f4a4e4f35)
Hope that helps

**Comment by mezz** [comment]
Thanks for the report!

In the case of the OP, there is a crash in JEI's GUI plugin that causes it to not show up at all:
```
[08:17:11] [Render thread/ERROR]: Caught an error from mod plugin: class mezz.jei.forge.plugins.forge.ForgeGuiPlugin jei:forge_gui
java.lang.IllegalStateException: Item has no registry name: 1 air BlockItem(org.cyclops.evilcraft.block.BlockBloodInfuser)
	at mezz.jei.common.util.StackHelper.lambda$getRegistryNameForStack$0(StackHelper.java:65) ~[jei-1.20.1-forge-15.8.2.25.jar%23307!/:15.8.2.25]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
```
This is an issue with `evilcraft`. I will try to work around it so that JEI doesn't just crash.

**Comment by mezz** [comment]
I have pushed some changes that should protect against this type of crash, it will be available in around 15 minutes.
Please try it out and let me know what happens.
