### ISSUE TITLE
game crashes when i try and use jei 

### ISSUE THREAD

**Issue by Apex9920** [mezz/JustEnoughItems#3656]
### Steps to Reproduce the Crash

game crashes when i load in and open Jei and click on an item to see how to craft it and or sometimes crashes when i type in the bar 
java.lang.NullPointerException: Cannot invoke "String.length()" because "p_14312_" is null 

[crash-2024-08-04_21.57.56-client.txt](https://github.com/user-attachments/files/16490600/crash-2024-08-04_21.57.56-client.txt)

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/all-the-mods-9

### Mod Pack Version (Optional)

9-0.3.0

### Extra Notes (Optional)

need help figuring this out not sure what it is 

### Crash Report

https://gist.github.com/Apex9920/037c18f6dda1fe4a6201dd3129e18941

**Comment by mezz** [comment]
Thanks for the report!
It looks like this item might be adding a `null` line to the tooltip:
```
-- Ingredient --
Details:
	Name: Blueprint Book
	Mod's Name: Silent Gear
	Registry Name: silentgear:blueprint_book
	Class Name: class net.minecraft.world.item.ItemStack
	toString Name: 1 blueprint_book
```

I have added some extra error handling to help prevent this from crashing. Please try out the latest version of JEI to see if it fixes the issue for you. Otherwise try removing `Silent Gear` and report the issue to them if it's only from their items.
