### ISSUE TITLE
[Crash]: FORGE - 1.20.1 - Crash when open JEI + R key

### ISSUE THREAD

**Issue by facundogirardi** [mezz/JustEnoughItems#3668]
### Steps to Reproduce the Crash

[latest.log](https://github.com/user-attachments/files/16517065/latest.log)

Game crash when i have the inventory open and press R key. tried the last 10 version with the same problem.

Thx! 

### Crash Report

https://github.com/user-attachments/files/16517065/latest.log

**Comment by mezz** [comment]
Thanks for the report!
Strangely, JEI doesn't appear in the stack trace. It looks like the screen's own keyboard handler is crashing when you press R, because it is trying to enter the text into a search box that doesn't exist.
Please try removing some mods to see which one might be causing this unusual behavior.

**Comment by facundogirardi** [comment]
Hello, i found the mod !! was https://www.curseforge.com/minecraft/mc-mods/brb, i removed it and now i have no problem.

Thx!!!

**Comment by mezz** [comment]
Great, thanks for reporting back with the solution!
