### ISSUE TITLE
[Other]: The server must have JEI installed message in singleplayer world 1.16.5

### ISSUE THREAD

**Issue by JentheH** [mezz/JustEnoughItems#3685]
### Other

I have jei-1.16.5-7.8.0.1009.jar installed in a modpack. Since a few days I keep getting the message that the server must have JEI  insatalled but its on a singleplayer world that hasn't even been opened to lan. Last week it worked but since then i keep getting this message.
[latest log.txt](https://github.com/user-attachments/files/16597646/latest.log.txt)
![Server must have jei installed](https://github.com/user-attachments/assets/bcc71631-f927-455b-9531-293e53525b16)

**Comment by mezz** [comment]
Thanks for the report!

It seems like another mod is conflicting with JEI or causing an issue here.
Please try to see if this bug happens with JEI alone, and then try removing mods to figure out which one is causing a problem.

If you find that there is only one other mod causing an issue, please report it to them and link back here.
Otherwise if the issue happens with JEI or one other mod, I can help debug or find the right place to report to.

**Comment by JentheH** [comment]
Hi,
After testing i found out that the issue only starts when pixelmon is added to the mod list. After testing different pixelmon versions, I found out that the problem only appears with the latest version of pixelmon (Pixelmon-1.16.5-9.1.12-universal.jar).
I put 2 pictures to show that it only affects the 9.1.12 version.
![With pixelmon 1 16 5-9 1 11](https://github.com/user-attachments/assets/ee3c58cd-b902-4cf9-a424-17285613bf9e)
![With pixelmon 1 16 5-9 1 12](https://github.com/user-attachments/assets/568f2d3f-ce0a-4a29-9bef-8db381a9cfa2)

**Comment by mezz** [comment]
Ok thanks!
Can you please report this to Pixelmon and link back here in case they need assistance?

**Comment by rafal11ck** [comment]
Since link is not provided but I found this
https://pixelmonmod.com/tracker.php?p=2&t=22036

Also I have same problem with it saying it has to be installed even thought it has. It's server client setup not single player as in opening post.

Edit: I also use "Tom's simple storage mod" and it's crafting terminal works. but vanilla crafting table does not.
