### ISSUE TITLE
[Crash]: Client at startup

### ISSUE THREAD

**Issue by VsUK** [mezz/JustEnoughItems#3705]
### Steps to Reproduce the Crash

I've been using jei-1.20.1-forge-15.3.0.1 but going through updating mods to latest  versions for 1.20.1. So I installed jei-1.20.1-forge-15.12.3.55 & it just crashes the client at start up. I remove & put the old version back & it loads up just fine. 

However, the version before .55 jei-1.20.1-forge-15.12.3.54 works fine. The issue is clearly with the .55.

### Crash Report

https://gist.github.com/VsUK/c31a464bdb23baf1247e11441c9c72d6

**Comment by Klouver-github** [comment]
Latest JEI for 1.20.1 is incompatible with Neoforge

**Comment by Xplodin** [comment]
> Latest JEI for 1.20.1 is incompatible with Neoforge

neoforge isnt what they are using

**Comment by VsUK** [comment]
> Latest JEI for 1.20.1 is incompatible with Neoforge

Sometimes I think people don't read posts.

**Comment by Klouver-github** [comment]
I did read, I was putting my 2 cents in

**Comment by mezz** [comment]
Thanks for the report!
I am not sure why JEI seems to be involved, it is not in the stack trace at all.

The issue comes from here:
`Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field vanillaKeyMapping was not located in the target class net.minecraft.client.KeyMapping. Using refmap mixins.connectormod.refmap.json`

Please report this to the `connectormod` and link back here in case they need assistance.
