### ISSUE TITLE
[Crash]: 1.20.1 Neoforge incompatibility

### ISSUE THREAD

**Issue by mxnmnm** [mezz/JustEnoughItems#3715]
### Steps to Reproduce the Crash

Using neoforge on 1.20.1 with jei versions beyond 15.12.3.54 causes crashes due to the version restrictions added in 15.12.3.55+

### Crash Report

https://gist.github.com/mxnmnm/f8d0941561d2146affac16c3720d300b

**Comment by mezz** [comment]
Thanks for the report!
JEI works with Forge on 1.20.1, please use NeoForge with 1.21.1.
The latest version of JEI requires features in Forge that are not in NeoForge on 1.20.1.
If you need this latest version on 1.20.1, you will need to request NeoForge to include the recent changes from Forge.

**Comment by AnonTheMouse** [comment]
There are NeoForge only mods for 1.20.1. This is not a viable solution. Don't be a dick.

**Comment by mezz** [comment]
Why would there be NeoForge only mods for 1.20.1?
As another workaround, you can also use an older version of JEI.

Re-read my message and please explain how it is "being a dick" other than the fact that you don't like the situation. Actually no, I don't mean that, don't explain. I'm generally happy to help but definitely not going to go out of my way to help you if you're being very rude. Check your own tone and try again.

**Comment by AnonTheMouse** [comment]
Don't ask me why. I didn't make them. They still exist, though.

As to the way in which your reply was being a dick, that would be, "If you need this latest version on 1.20.1, you will need to request NeoForge to include the recent changes from Forge." If there are features NeoForge needs to implement, then as the mod-maker who needs those features, would requesting them not be _your_ job?

**Comment by mezz** [comment]
When this issue came up, I asked the NeoForge developers what the right solution was. 
Unexpectedly, they told me to just use Forge on 1.20.1.

Here's the overall situation:
I (and most mods) only support Forge and Fabric on 1.20.1 because that's what existed at the start.
NeoForge released versions that are compatible with Forge on 1.20.1, so players can use NeoForge in place of it. This was to get people to try it out, but really NeoForge is "starting" in earnest on 1.21. I am not sure how much support they offer on 1.20.1 any more.
I support NeoForge as my main environment on 1.21, along with Forge and Fabric.

If you want NeoForge support on 1.20.1, it's their claim that they are compatible and I am not really involved. You can kindly ask them to update in order to maintain compatibility for Forge, and maybe they will give you a different answer than they gave me.
