### ISSUE TITLE
[Bug]: Neoforge 1.21.1 Some Items in creative menu are not being added to JEI

### ISSUE THREAD

**Issue by Saereth** [mezz/JustEnoughItems#3723]
### Steps to Reproduce the Bug

Install a new instance of Neoforge 21.1.31
add JEI 19.14.2.146
add some of SuperMartijn642's mods and dependencies such as trashcans, entangled, item collectors mods

The mod adds the items to the creative tab but they never show up in JEI. 

### Expected Behavior

I would expect the items to show up in JEi

### Actual Behavior

They only show in the creative tab

### Extra Notes (Optional)

I originally opened an issue with SuperMartijn642 here: https://github.com/SuperMartijn642/TrashCans/issues/46
but as this was suspected to be a JEI issue or unexpected behavior I've opened it here for followup. If I can provide any more logs or testing let me know and I'm glad to help. Thanks!

**Comment by mezz** [comment]
Thanks for the report!
SuperMartijn642's explanation was clear and this should be fixed in the next release of JEI (available shortly).

**Comment by mezz** [comment]
The previous fix wasn't working. 
This actually turned out to be a different issue entirely!

@SuperMartijn642 adds his items to the creative tab using `TabVisibility.PARENT_TAB_ONLY` ([see here](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/blob/7d0d911135c759a1077b3d072c981b6830d955a7/src/main/java/com/supermartijn642/core/CoreLib.java#L63)) and JEI was only looking for items included in the search tab. I have updated JEI to look in both places.

This has been fixed in JEI `19.17.0.195`
