### ISSUE TITLE
[Bug]: la Superposicion del jei esta desactivada ¿Como se activa?

### ISSUE THREAD

**Issue by AxOart06** [mezz/JustEnoughItems#3740]
### Steps to Reproduce the Bug

**Cree un servidor en aternos y cuando entre al servidor y abri el inventario no me salia la barra del jei (la superposicion) y en la llave inglesa me salia esto *La superposicion del JEI esta desactivada para activarla pulse key.keyboard.o* PD: no se como se hace para activar eso busque tutoriales y no me sale nada de nada** 

### Expected Behavior

**Cree un servidor en aternos y cuando entre al servidor y abri el inventario no me salia la barra del jei (la superposicion) y en la llave inglesa me salia esto *La superposicion del JEI esta desactivada para activarla pulse key.keyboard.o* PD: no se como se hace para activar eso busque tutoriales y no me sale nada de nada** 

### Actual Behavior

**Cree un servidor en aternos y cuando entre al servidor y abri el inventario no me salia la barra del jei (la superposicion) y en la llave inglesa me salia esto *La superposicion del JEI esta desactivada para activarla pulse key.keyboard.o* PD: no se como se hace para activar eso busque tutoriales y no me sale nada de nada** 

### Extra Notes (Optional)

Cree un servidor en aternos y cuando entre al servidor y abri el inventario no me salia la barra del jei (la superposicion) y en la llave inglesa me salia esto *La superposicion del JEI esta desactivada para activarla pulse key.keyboard.o* PD: no se como se hace para activar eso busque tutoriales y no me sale nada de nada

**Comment by mezz** [comment]
Thanks for the report!

It seems like another mod is conflicting with JEI or causing an issue here.
Please try to see if this bug happens with JEI alone, and then try removing mods to figure out which one is causing a problem.

If you find that there is only one other mod causing an issue, please report it to them and link back here.
Otherwise if you still can't figure it out, please paste your new crash log and client logs here, and I can help debug or find the right place to report to.

**Comment by AxOart06** [comment]
Gracias por la ayuda y el tiempo y lo pude resolver era una tonteria pero
de todas maneras gracias :)
