### ISSUE TITLE
[Crash]: Hovering over items from some mods crashes my game

### ISSUE THREAD

**Issue by Jase013** [mezz/JustEnoughItems#3752]
### Steps to Reproduce the Crash

Opening the search bar and typing in item name and hovering over it.

### Mod Pack Version (Optional)

1.20.1

### Crash Report

https://gist.github.com/Jase013/a14acb446d292aa83de7daa83ac0e967

**Comment by highestinthespb** [comment]
try to delete the mod "Just Enough Guns"

**Comment by mezz** [comment]
Thanks for the report!
This crash is definitely coming from "Just Enough Guns", I agree.

I have added some extra protections in JEI that should protect it from completely crashing, here https://github.com/mezz/JustEnoughItems/commit/7b1ebdebb9076ed59407cec726e0b48a59e61fc9
That means the next version of JEI should show a tooltip error for this item instead of crashing the game.

**Comment by Jase013** [comment]
Yea I ended up taking out the mod for now hopefully you can make a fix for it and if not thats alright

**Comment by mezz** [comment]
Sounds good. Please try out the latest version of JEI, it should prevent the game from completely crashing.
