### ISSUE TITLE
[Bug]: Neither blacklist file functioning

### ISSUE THREAD

**Issue by twenty41** [mezz/JustEnoughItems#3755]
Minecraft 1.21
Fabric 0.16.5
jei-1.21.1-fabric-19.17.0.193

### Steps to Reproduce the Bug

Add items to blacklist.cfg or blacklist.json, open JEI, they're still there

### Expected Behavior

Items not visible after blacklisting

### Actual Behavior

Items are visible after blacklisting.

### Mod Pack URL (Optional)

[Curseforge pack import](https://i.bloomworldwi.de/oEAccg) - link is not an instant download

### Mod Pack Version (Optional)

Not applicable, custom in-dev modpack for friends

### Extra Notes (Optional)

Maybe I'm not formatting the .json file correctly? I don't see instructions for that, I just copied over the .cfg list inside the brackets.

Perhaps this is a dupe of #3714 but it's still happening for me on the latest JEI, `jei-1.21.1-fabric-19.17.0.193.jar`
Can not check prior versions as this is the only version compatible with Fabric 0.16.5. 
I know this only happened in the past few days since I've updated to latest Fabric/updated all my mods but I know that's not very specific

### latest.log

[latest.log](https://github.com/user-attachments/files/16956253/latest.log)

**Comment by twenty41** [comment]
Downgrading to `19.8.2.99` fixes this. 

The latest version for 1.21.1, `19.17.0.193`, is compatible with 1.21 in that it launches and mostly works, but the blacklist specifically does not

**Comment by mezz** [comment]
Hello,
The blacklist json file is not meant to be edited directly, it is a new format.
Please use the in-game "edit mode", which can be enabled by setting a key binding for it in the controls settings.
I have just implemented key bindings on fabric, so make sure to get the latest version of JEI in order to try it out (`19.17.0.196`+).

The edit mode will let you hide items easily by ctrl-clicking them, and it will write the items to the blacklist file for you.

**Comment by twenty41** [comment]
Thank you fixed
