### ISSUE TITLE
[Bug]: Quark Icons are not displayed

### ISSUE THREAD

**Issue by MrHimera** [mezz/JustEnoughItems#3770]
### Steps to Reproduce the Bug

Hover over an item (weapon, armor, etc.) in the JEI list

### Expected Behavior

When hovering over an item in JEI, icons for the item's stats should appear in the tooltip at the top.

### Actual Behavior

When you hover over an item in JEI, in the place where the item's stats icons should be shown, there is nothing in the tooltip at the top (but the rest of the information in the tooltip is in place).

### Extra Notes (Optional)

Forge 1.20.1 47.3.0
JEI 15.19.0.89
Zeta 1.0-24
Quark 4.0-460

**Comment by mezz** [comment]
Thanks for the report!
This was terribly confusing to figure out.
I tried updating Quark and Zeta myself here: 
* https://github.com/VazkiiMods/Quark/pull/5045

but the issue turned out to be with how Quark hacks the ItemStack tooltip and how JEI handles ItemStack.
I have added a fix that resolves the problem on JEI's side.
