### ISSUE TITLE
NBT Variants show recipe for each 

### ISSUE THREAD

**Issue by Dijkstra1-zz** [mezz/JustEnoughItems#380]
Some mods have items where the only different is NBT data like botania flower, and when I look up the recipe, it shows me recipes for every single flower which means I have to look through several pages, of recipes before finding the item I want, would be possible just get the recipes relating to item with that exact NBT data, it not just the botania flower, the recipes for the extra utils machines do it and that in the crafting table, another example, is Mekanism tanks recipes. Do not hold me, to it being down NBT data that is just the most logic thing I can think is causing it.

P.S.
Tanks for fixing looking up fluid crafting was bugging me a lot.

**Comment by mezz** [comment]
The mod (Botania) needs to give information to JEI about how to interpret its flower's NBT. They can do it by using the `ISubtypeRegistry`. Please report to them and link back here, I can help out if they need anything.

I was able to do this automatically for tanks by using the fluid capabilities, but there is no way for JEI to automatically understand other NBT, since it is often used for a variety of reasons and not just subtypes.

**Comment by Dijkstra1-zz** [comment]
I understand NBT is usually used for for stuff contains x mb of x liquid or has 200 RF stored in it.

**Comment by mezz** [comment]
Please report to Botania and link back here, I can help out if they need anything.
https://github.com/williewillus/Botania/issues
