### ISSUE TITLE
[Other]: JEI advanced tooltip search not working 1.18.2(forge)

### ISSUE THREAD

**Issue by TheHighRatCouncil** [mezz/JustEnoughItems#3800]
### Other

When I go to use the advanced tooltip search, they do not work. In the search bar it displays as a misspelled search instead of a tooltip search with "^[color]" for example not working. I do have the 'config' mod installed if that has anything to do with it. I cant find a solution to this issue

**Comment by mezz** [comment]
Thanks for the report!

Please try to see if this bug happens with JEI alone, and then try removing mods to figure out which one is causing a problem.

If you find that there is only one other mod causing an issue, please report it to them and link back here.
Otherwise if the problem is only from JEI or you still can't figure it out, I can help debug or find the right place to report to.

**Comment by TheHighRatCouncil** [comment]
This is solely JEI causing the problem. I've tested it by itself and the issue persists. I can use the @[mod] feature but that's as far as it's willing to work. I can't tell if the advanced search feature is enabled or not as with the config mod, it doesnt let client-side configuration work in more advanced features. I attempted to find the config file to check if it's enabled as some other people had this same issue with an older version of the 1.18.2 mod(Went searching to further troubleshoot). I was unable to locate the right file to check it.

**Comment by mezz** [comment]
The JEI client config is located in the `/config/jei/jei-client.ini` file.
The relevant config values in the file are 
* `TooltipSearchMode` which should be set to `ENABLED` or `REQUIRE_PREFIX`
* `SearchAdvancedTooltips` which should be set to `true`

**Comment by TheHighRatCouncil** [comment]
Fixed. The only thing enabled was the mod search function. Everything had to be enabled in the file. Thank you!!!
