### ISSUE TITLE
[1.10.2]JEI crash when sending pages of item list

### ISSUE THREAD

**Issue by a1wass** [mezz/JustEnoughItems#399]
I'm japanese,sorry about poor english.
When I was seaching TCon's item, suddenly MC has crashed.
Then I tried to see all page of item list, it crashed as of earlier.
I have no idea for this issue, help me...

Here is the crash report.
https://gist.github.com/a1wass/6ab5f7481b3c97458171f9ec383ba6ba

**Comment by mezz** [comment]
Thank you for the report!
I can see that it is not caused by JEI alone. Some item is rendering badly, causing the crash. From the crash report, I do not know which item is causing the crash.

Please backup your world and try removing mods until you stop crashing. 
Let me know what you find and I can help you report to the right place.

**Comment by a1wass** [comment]
Thank you for response!
I found that
EnderIO-1.10.2-3.0.1.81_beta
extrautils2-1.10.2-alpha-1.0.1
industrialcraft-2-2.6.40-ex110
cause this problem.
I will try another version.

**Comment by a1wass** [comment]
I completely discover the problem.
this crush is caused by optifine so i removed it.

**Comment by mezz** [comment]
Ok, thank you for the solution.
