### ISSUE TITLE
Update ru_RU.lang

### ISSUE THREAD

**Issue by kellixon** [mezz/JustEnoughItems#430]
Updated Russian Language for version JEI 3.9.5.257.
http://pastebin.com/M3APs2kr
*added translation 3 new lines

**Comment by mezz** [comment]
Thanks!
In order to add this change, please go here and edit the file directly: https://github.com/mezz/JustEnoughItems/blob/1.10/src/main/resources/assets/jei/lang/ru_RU.lang

![edit-this-file](https://cloud.githubusercontent.com/assets/916092/18610989/a5625a76-7ce0-11e6-8058-9230bd048082.jpg)

From there you will make a Pull Request so I can see the changes and accept them.

**Comment by mezz** [comment]
PR is here: https://github.com/mezz/JustEnoughItems/pull/435
