### ISSUE TITLE
[Suggestion] Extreme Console Spam

### ISSUE THREAD

**Issue by MysticAura** [mezz/JustEnoughItems#433]
MC 1.10.2
Forge 2068
JEI Version(s): This has seemingly been every version for 1.10.2 for the last long while

My log files have been insane. The largest hitting 4.5 gigs, which just shouldn't happen. Is there any way you could add the broken stack npe messages to a debug mode, instead of default logging behavior? I realize devs have to fix their npe's however this is an extreme situation when log files are becoming harmful due to extreme size. I'm directing this here, since each is prefixed by [JEI]. I know that JEI isn't causing the errors, but merely reporting them to the log.

I'd appreciate any feedback you can provide. Thanks

**Comment by mezz** [comment]
Thanks for the report!
Do you have a pack I can try out that demonstrates the issue well?
I may be able to reduce the log greatly if I detect and suppress duplicate crashes, but I'll need to test to know that it works well.

**Comment by MysticAura** [comment]
I asked TLove (I'm making the pack for him) and he's cool with me sharing it with you. Keep in mind it's still in development. Is there an email I can send you the link in? Being closed beta, I shouldn't let everyone who see's the issue, have the pack. I could just have Blu or TLove relay it to you.

**Comment by mezz** [comment]
Got it, thanks!

**Comment by mezz** [comment]
Found three issues that multiply together to make the crazy spam you saw:
1. With color search enabled, JEI makes a lot more log spam. Fixed by suppressing all those logs, it's not a big deal if JEI can't figure out what color an item is.
2. When java is running out of memory (it does with this pack and 4GB given to Java) JEI will delete the ItemList's base cache to save memory, and load it again when a search is done. This causes the log spam to happen all over again. Fixed by making sure the ItemList's base cache is never deleted. Java will just have to reclaim memory space somewhere else, the performance cost and spam from recreating the cache over and over is terrible.
3. The MoreOverlays mod creates its own ItemList, which basically doubles all the above JEI log spam. I added a new feature to the JEI API so they don't need to do that, and I made a PR to update MoreOverlays: https://github.com/feldim2425/MoreOverlays/pull/15

After fixing all this in my dev environment, I only see 1 stack trace error message from JEI. Much better than 4.5 gigs of logs haha

The JEI fixes are in version 3.9.7. MoreOverlays will come later, but it's not as big a deal now that the other log spam is eliminated.
