### ISSUE TITLE
Mod not compatible with lastest Forge build

### ISSUE THREAD

**Issue by Kryyss** [mezz/JustEnoughItems#436]
When attempting to run Minecraft with JEI installed, it reports that I need Forge version 12.18.1.2053 or higher. Since I'm running Forge 12.18.1.2092 it appears that your mod has a compatibility issue.

[never mind, my launcher wasn't using the newest build. my mistake. sorry]

**Comment by jnm2** [comment]
Followup question before I open an issue on this. Currently the recommended version is 3.12.3.292, but that requires a newer-than-recommended Minecraft Forge 12.18.1.2053 (.2011 is recommended).
Is this intentional? I'd prefer to stick with the release/recommended version of stuff because I have multiple mods I like to use.

**Comment by TehNut** [comment]
Yes, it is intended. JEI sets it's required Forge version to the minimum Forge with the features it requires.

**Comment by mezz** [comment]
I make sure to only update the required Forge version when it's absolutely necessary, so the latest JEI truly will not run with a Forge version lower than 12.18.1.2053.

I also keep up with the latest Forge so that I am always prepared when things change. I help contribute there sometimes, for features JEI needs. Many other mods do this as well.

The last time I changed the required Forge version was JEI 3.8.1, if you use JEI 3.8.0 then you can use much older Forge versions. You may find that many mods require a higher JEI version though. Your best option is probably to use the latest Forge, the recommended version is much too conservative in my opinion.

**Comment by jnm2** [comment]
Gotcha. It would be cool if new JEI releases had a minimum and a recommended forge version listed. Is the bleeding edge going to be better than any other point, all mods considered, or should I try to stick with a particular in-between forge prerelease?

**Comment by KnightMiner** [comment]
Normally Forge has a recommended build. Since it tends to be a bit old, just start there, and just keep increasing the build number as a mod requires a later Forge version.

Checking the changelogs also helps, as if you are having an issue with something breaking you can check the changelog for the last build where that changed.
