### ISSUE TITLE
screen render crash [BUG]

### ISSUE THREAD

**Issue by DanHolli** [mezz/JustEnoughItems#448]
when changing pages the game does a hard shutdown and gives the log below but no crash headers
[crash from log](https://gist.github.com/DanHolli123/f84d490ab7f0c74f18d47b9eaa031444)
using the current stable version: jei_1.10.2-3.10.0.261
Optifine isn't installed because of my previous issue

**Comment by mezz** [comment]
I reported this to Actually Additions here: https://github.com/Ellpeck/ActuallyAdditions/issues/245
This is caused by a 3rd mod that has a bad version of the RF API.
He recommends removing mods besides ActuallyAdditions and JEI, until the crash goes away.
I suspect valkyrielib or ProgressiveAutomation, try removing those one at a time.

**Comment by mezz** [comment]
Any update @DanHolli123 ?

**Comment by HenryLoenwind** [comment]
btw, if you add Ender IO to the mix you'll get a listing from which mod the RF classes are loaded on crashing
