### ISSUE TITLE
[Help] Recipe Wrappers

### ISSUE THREAD

**Issue by ThexXTURBOXx** [mezz/JustEnoughItems#462]
Hello mezz,

sorry, but this is not a bug (I have no other idea how to contact you):
I want to show [my custom IRecipes](https://github.com/ThexXTURBOXx/Reforged/tree/master/java/org/silvercatcher/reforged/items/recipes) in JEI.
In my Integration mod, I have [this](https://github.com/ThexXTURBOXx/Reforged-Integration/tree/master/java/org/thexxturboxx/rfintegration/jei).
Why doesn't it work?
The boomerangs now show me ALL recipes, which exist in the whole game and the Nest of Bees shows me none.

Thanks in advance
ThexXTURBOXx (Nico)

**Comment by GirafiStudios** [comment]
The best place to get support regarding JEI would probably be on the IRC channel. It is #JEI on irc.esper.net :)

Just as a side note - it would probably be a good idea to update JEI to latest version in your dev workspace, since it had a big refractor in version 3.11.0.269, which will break what you have currently.

**Comment by ThexXTURBOXx** [comment]
Ah ok, thanks :) I will go straight to there ^^

To your side note: I can't update it, because my mod is still running on 1.8/1.8.9 unfortunately :/ I am working on a 1.10-version, but updating is a pain :( So much things broke

**Comment by ThexXTURBOXx** [comment]
I close this as I know the IRC now :) Thanks again ^^
