### ISSUE TITLE
[1.10.2] [Possible Bug] Cheating in Items Doesn't Work in Survival on Servers

### ISSUE THREAD

**Issue by SnowShock35** [mezz/JustEnoughItems#468]
Hello,

I believe I've found an issue with JEI for Minecraft 1.10.2, here's the details. . . 
### Important Information
- Minecraft 1.10.2
- Minecraft Forge 12.18.1.2094
- Just Enough Items (JEI) 3.12.0.282
### Issue Description

When on a server **as an operator in _cheat mode_** you're unable to spawn items in when you're in survival. 

I know this definitely worked a couple versions ago. Did you change this behavior? Or is this a legitimate bug. If so. . . well I guess I found a bug.
### Issue Media

http://gfycat.com/AridNeedyBear

**Comment by shadowfacts** [comment]
~~You need to be in JEI cheat mode no matter what your gamemode is to cheat items in. From your gfy, you're in JEI normal mode when you try to cheat items in from survival.~~

Edit: Ay, missed the last two seconds _sigh_

**Comment by SnowShock35** [comment]
@shadowfacts Before jumping to conclusions, maybe you should watch the entire GIF. . . 😉

**Comment by DMIL421** [comment]
Having the same behavior. You can use cheat mode in creative, but not in survival.

**Comment by FireBall1725** [comment]
@SnowShock35 if you didn't cheat it would probably be fine Kappa

**Comment by DMIL421** [comment]
In our case, we're playing on a testing server where we just did a server wipe because of a major change in worldgen. Some players would like to get some of the stuff back to continue testing without starting fresh, which is where JEI cheat items mode is extremely useful. As I said, it works fine when in creative mode, but that forces the player to keep swapping between creative and survival mode, which can lead to other problems if the player isn't careful.

If the change was intended, I'm not here to argue about it, but rather to report that it is happening whereas it was not happening before.

**Comment by mezz** [comment]
Confirmed, the permissions check crashes on the server silently.

**Comment by SnowShock35** [comment]
Thanks Mezz ❤️
