### ISSUE TITLE
Duplicate entry crash on server join [jei_1.10.2-3.12.5.301]

### ISSUE THREAD

**Issue by TripOptic** [mezz/JustEnoughItems#501]
Title speaks for itself.

https://gist.github.com/TripOptic/650f3521ecefc06b625506aef4f92303

No FEI installed

**Comment by mezz** [comment]
Thanks for the report!
Can you paste the full client log to gist? I need some more information to see what's going wrong.

**Comment by TripOptic** [comment]
Here is my latest client log. 
https://gist.github.com/TripOptic/55e641edc7749d13e01e1a0a81fa5732

**Comment by mezz** [comment]
Ah thanks I see now. IC2 and zmaster587.advancedRocketry have a conflict, they are both using the same recipe category key for their ElectrolyzerCategory. 

They should make their category keys more unique, like "ic2.electrolyzer" and "zmaster587.advancedRocketry.electrolyzer" instead of something like plain "electrolyzer".

I see you already reported here, thanks: https://github.com/zmaster587/AdvancedRocketry/issues/215

You can report to IC2 here: http://bt.industrial-craft.net/
