### ISSUE TITLE
Waffle recipe is too salty

### ISSUE THREAD

**Issue by AtomicBlom** [mezz/JustEnoughItems#503]
I've been following the following recipe I got from JEI (no idea how)
- 2 cups all-purpose flour 
- 1 teaspoon salt 
- 4 teaspoons baking powder 
- 2 tablespoons white sugar 
- 2 eggs 
- 1 1/2 cups warm milk 
- 1/3 cup butter, melted 
- 1 teaspoon vanilla extract
1. In a large bowl, mix together flour, salt, baking powder and sugar; set aside. Preheat waffle iron to desired temperature.
2. In a separate bowl, beat the eggs. Stir in the milk, butter and vanilla. Pour the milk mixture into the flour mixture; beat until blended.
3. Ladle the batter into a preheated waffle iron. Cook the waffles until golden and crisp. Serve immediately.

Every time I've tried the waffle block comes out too salty.

FEI is not installed.
Using Forge 12.18.1.2095
Other Mods:
Shear Madness, cooking edition.

**Comment by mezz** [comment]
Thanks for the report!
Sorry but it seems like you have the wrong recipe. I recommend using the recipes from @MatrexsVigil, since she is widely known to be completely dedicated to creating the most delicious recipes in Minecraft.

![2016-10-05_04 25 08](https://cloud.githubusercontent.com/assets/916092/19111341/f157e7da-8ab3-11e6-918b-9aa02178591b.png)

I think the key is to use a Tofegg instead of a real egg, which can help with the perceived saltiness.
![2016-10-05_04 25 26](https://cloud.githubusercontent.com/assets/916092/19111342/f1698e7c-8ab3-11e6-866c-8d21da3c98cc.png)

The butter in the recipe already includes enough salt in my opinion, there's no need to add more.
![2016-10-05_04 25 41](https://cloud.githubusercontent.com/assets/916092/19111338/eee37b36-8ab3-11e6-902d-2865acb942d7.png)

Hope that helps!
