### ISSUE TITLE
Invisible JEI/Constant tooltips with Harvest Festival NPCs

### ISSUE THREAD

**Issue by joshiejack** [mezz/JustEnoughItems#508]
Starting from it looks like build 252. (And up to the latest). With my mod Harvest Festival if you hover over an item in jei, close the inventory and then talk to one of my npcs, then the jei tooltip will still render. On top of that, clicking outside of the area to where a jei item would normally be it will either cheat that in or show the recipe for it.

**I have a feeling this has to be something I'm doing, but I'm not entirely sure what. So if so let me know what I'm doing wrong, as I'm rather confused :P.** 

![Attack of the Jaded bug](http://i.imgur.com/MeoN6Is.gif)

**Comment by mezz** [comment]
Thanks for the report!
Hah okay I'll take a look. This has something to do with the events for opening and closing guis, but the exact cause is not obvious to me without trying it myself.

**Comment by mezz** [comment]
Ok this was a bit difficult to test because item rendering from Harvest Festival crashes in my dev environment.

Here's the logic for JEI:
Active next to any `Gui` that is a `GuiContainer`.
Renders the item list on `GuiScreenEvent.BackgroundDrawnEvent`.

Your `GuiBaseContainer` is a `GuiContainer` but does not fire the background drawn event, so JEI is active but not drawn.

**Comment by mezz** [comment]
I see 3 solutions:

If you want JEI drawn (probably not):
- fire the `GuiScreenEvent.BackgroundDrawnEvent`

If you don't want JEI drawn:
- implement `Gui` instead of `GuiContainer`, as far as I can tell you are not using it as a container
- I can try to detect this situation where the background is not drawn, and disable JEI for this gui

**Comment by joshiejack** [comment]
Ahhh ok. silly me.Thanks for taking a look. Only bit was using it for was when container was closed. Guess i can just extend Gui and manually set the container or duplicate/call the code static when closing the gui.

As for the item renderig in dev sorry, was naughty and added myself a hook for rendering my npcs/animals items, in the way like banners do, so would have needed to load the transformer.

**Comment by joshiejack** [comment]
Ok I just changed everything over from GuiContainer to GuiScreen (copying the parts from GuiContainer I was using :P). Thanks for the help mezz.

https://github.com/PenguinSquad/Harvest-Festival/commit/67c5794b95cc580568d49bd717ac62c7a05d0a8e
