### ISSUE TITLE
JEI still registers clicks/hovers when GUI elements are drawn over it

### ISSUE THREAD

**Issue by thetaCriterion** [mezz/JustEnoughItems#519]
![2016-10-13_00 38 41](https://cloud.githubusercontent.com/assets/22810439/19341336/e0c841ce-90e1-11e6-9c18-1f2e07d684ba.png)
![2016-10-13_00 42 40](https://cloud.githubusercontent.com/assets/22810439/19341337/e0cdb14a-90e1-11e6-91bb-338d0c1e0d2d.png)

Tested with the latest version. Clicking the item in the first image will cause JEI to save/load inventory; clicking the button in the second image will bring up the recipe for the item underneath.

**Comment by mezz** [comment]
Thanks for the report!

JEI does not have the save/load inventory function. Another mod like NEI or FEI is adding that. You should report to them about the save/load problem.

Please report this issue to Inventory Tweaks and link them back here. 
https://github.com/Inventory-Tweaks/inventory-tweaks/issues

When Inventory Tweaks "uses" a click, they should cancel the gui event for clicks, so that JEI never receives it: 
`GuiScreenEvent.MouseInputEvent.Pre`
There is no other way for JEI to know that something that can be clicked is drawn over it.

**Comment by thetaCriterion** [comment]
You're right-- I spaced about the save/load buttons. Looks like they're actually added by [Just Enough Buttons](https://mods.curse.com/mc-mods/minecraft/248747-just-enough-buttons). So these are two separate issues. Apologies for the confusion! I'll let the right people know.

**Comment by mezz** [comment]
Cool, I hadn't seen that mod before, it looks like a good one actually. 
Added it to the ["NEI Features in 1.9+"](https://docs.google.com/spreadsheets/d/1NEWZjKvWB-SibY1BXc1zoYkK7AhjMMBZess9wMy--6w/edit#gid=0) chart.

Here's their issue tracker: https://github.com/UniversalLP/JustEnoughButtons/issues

**Comment by mezz** [comment]
Fixed with a PR on their side: https://github.com/Inventory-Tweaks/inventory-tweaks/pull/399
