### ISSUE TITLE
Can't connect to server, JEI taking > 30 seconds to load on login

### ISSUE THREAD

**Issue by nloah** [mezz/JustEnoughItems#551]
I saw some stuff about JEI supposedly not doing this anymore, but even on version 335 it still does. I'm in HermitPack version 1.1. The server shows me as having loaded into the world, but my skin's second layer doesn't show up and the log still shows JEI trying to do... stuff. 

Here's the info from when my client connects: https://gist.github.com/nloah/e4a89b964939c48f5d897ea472a81aba

Recipe Registry and Item Filter seem to be taking waaaay too long. It also takes the same amount of time when starting my client, I noticed. I'd assume there's something in HermitPack that is taking forever to load?

**Comment by nloah** [comment]
Saw this line: 
[23:43:53] [Netty Client IO #3/INFO] [JEI]: Registered  plugin: li.cil.oc.integration.jei.ModPluginOpenComputers in 30622 ms

30 seconds to register opencomputers doesn't seem good. I don't recall it doing that before.

**Comment by TehNut** [comment]
#538

**Comment by nloah** [comment]
Hmm, will test without Optifine and report back soon.

**Comment by nloah** [comment]
Can confirm it is not Optifine. Removed from the pack, still same error. Here's an updated log: https://gist.github.com/nloah/c76a26819eb7c7706a0b3efd91e8a351

**Comment by mezz** [comment]
This is an issue with CraftTweaker right now, it's being worked on by @jaredlll08
https://github.com/jaredlll08/CraftTweaker/issues/69

JEI by itself will load earlier, so there is no server disconnect issue. 
However, other mods that restart JEI on startup can cause issues.

**Comment by b0bst3r** [comment]
As discussed in IRC with Mezz and player it seems there's mods which cause JEI to reload, in my case it's being reloaded 3 times with a lot of logged information in the client console.  Had to revert to JEI build 362 for now.

**Comment by Saereth** [comment]
This issue exists with crafting harmonics as well, both will try to entirely reload immediately, if you have both in your pack... oh boy.

edited; meant crafting harmonics, craftweaker was already discussed.

**Comment by jaredlll08** [comment]
yea, it is getting fixed, @Saereth the version you running still doing good?

**Comment by Saereth** [comment]
For most of us it is, but we did have one guy today that has some connectivity issues. We're removing crafting harmonics though and I believe that'll clear it up for him.

**Comment by jaredlll08** [comment]
ok cool, may also just be connection, since if everyone else is running it fine, then there shouldn't be a problem.
@mezz I believe I fixed the issue with CraftTweaker and JEI :P

**Comment by b0bst3r** [comment]
I've found running a resourcepack is enough to push a client into not being able to connect to a server, specifically a HD RP like Sphax.  I've been running a few tests with Player and he has worked out a resolution for this issue.

**Comment by b0bst3r** [comment]
With jei_1.10.2-3.13.3.374 & CraftTweaker-1.10.2-3.0.15 the condition is actually a lot worse, no longer do I actually connect to the game and can see the world before getting disconnected, I never actually connect and go straight from Loading world to disconnected.

**Comment by jaredlll08** [comment]
Uh, I had a few people telling me this was good, may I ask what your ping
is to the server?

**Comment by mezz** [comment]
@b0bst3r can you upload a client log to gist and link it here?

**Comment by b0bst3r** [comment]
I don't have any complete logs I've been scouring through them since I posted the above.... no idea why I don't, so I will have to repeat this to get you complete ones.  Looks like MMC doesn't log to file is you clear the client console (never knew that).

This http://pastebin.ubuntu.com/23490257/ is the only thing I have when I cleared out the console to log a new attempt.  I pulled the timings from it 

[00:50:24] [Client thread/INFO]: Built    recipe registry in 1642 ms
[00:50:24] [Client thread/INFO]: Building item filter...
[00:50:37] [Client thread/INFO]: Built    item filter in 12419 ms
[00:50:37] [Client thread/INFO]: Finished Starting JEI in 15914 ms
[00:50:40] [Client thread/INFO]: Built    recipe registry in 1716 ms
[00:50:40] [Client thread/INFO]: Building item filter...
[00:50:52] [Client thread/INFO]: Built    item filter in 12235 ms
[00:50:52] [Client thread/INFO]: Finished Starting JEI in 15657 ms

The bottom of this log went into a crash loop before stopping but I don't think thats related as it's all future task errors.

I will repeat the attempts and get you proper logs and also try and figure out why I don't get any fml-client logs.

Edit - my ping to the server is 93ms and I can and always have connected fine with build 362 (JEI), I can't use any after that version unless I run with -Dfml.readTimeout=120 flag on both server and client.

**Comment by Desoru** [comment]
Same Issue

My Log: https://dl.dropboxusercontent.com/u/263786228/fml-client-1.log

**Comment by mezz** [comment]
Working with jared now to solve this soon. 
Future versions of JEI will never fully reload.

**Comment by mezz** [comment]
Fixed with CraftTweaker-1.10.2-3.0.17 and jei_1.10.2-3.14.2.398

**Comment by cyberpunkbln** [comment]
Hello,
knows anybody if the bug/are fixed? Its hard to find informations, why this bug/problem is very special and hard to find. I use the jenkins build jei_1.11.2-4.3.1.259 and is not solved. Other Mods like SilentGems causes very high load times, too.
thx

**Comment by mezz** [comment]
JEI for 1.11.2 should have no delay when connecting to a remote server.
If your loading times are long (progress bars, before you choose a world or select a server), you may be experiencing a different bug that was fixed in the latest Forge: https://github.com/mezz/JustEnoughItems/issues/746
