### ISSUE TITLE
[Suggestion] Hide all recipes from a certain "crafting mechanic"

### ISSUE THREAD

**Issue by 016Nojr** [mezz/JustEnoughItems#645]
I think this would be a nice feature having a option in the config to add the name of the block that does the crafting table and hide all recipes that has to be done through that block or item.

For example, take the recycler from IC2. Shows that everything can be made into scrap.

**Comment by mezz** [comment]
Thanks for the suggestion!

This actually gets asked a lot,  but it's *always* about the IC2 recycler.
They plan to make it so that the recycler only shows up when you look up scrap, or the recycler itself, instead of for everything. They just haven't had time to implement it I think.

If you can, please report this to the IC2 issue tracker so that we can keep track of any progress on it.
http://bt.industrial-craft.net/my_view_page.php

**Comment by 016Nojr** [comment]
http://bt.industrial-craft.net/view.php?id=2048
