### ISSUE TITLE
Exact searching

### ISSUE THREAD

**Issue by U1F984** [mezz/JustEnoughItems#650]
It would be great to have exact searching instead of searching for each word individually. I quite liked the way NEI handled this, using exact matching by default and supporting or via |.

Alternatively one could introduce opt-in exact searching using "", for example to search for "Fertility: 4" as currently one would need to look through every search result to find what *actually* has Fertility 4 and not just Fertility or 4.

Thanks for your time to look at this suggestion and making this great mod!

**Comment by mezz** [comment]
Thanks for the suggestion!
Quotes makes sense, that's how most search engines do it.

**Comment by abdullamu** [comment]
well i dont want to open new issue, but it would be nice to be able to search like the way nei by typing the mod name and it will bring everything from that mod and related items, i understand theres @ but i have to write the very exact name of the mod to get something if theres space or no it matters!,
 this is bad for people who cant remember the name of the mods so i have to study every mod name exactly with the spaces dots underscores which is quite annoying since i just left 1.7 to get into 1.10 and i dont know the names of the mods, its even bad for non fluent English speaking people e.g thermal dynamics i always had problem with the name missing one letter or word so i just type dynamics and brings up everything from that mod so easy and convenient than open browser which ganna slow everything down or try to look for my phone to see the name.

 Than here starts the second problem i forget which mods i have s̶o̶m̶e̶t̶i̶m̶e̶s̶ most times since the modpack im playing currently contain 170 mods, really you want me to remember all of those! . sometimes i look at the nei panel for mods and check their items and pick something to start messing up with or item than i dont know its name.

and i tried to use nei addon but i like to have the search bar on the right and i like how fast JEI in search coming from NEI 1.7 ohh boy not used to the sonic speed JEI provide but these are really necessary stuff to help people interact with the mods easily and without hassle of trying to remember. 

 thank you and i hope you take it into consideration and we see it soon so i can start properly my 1.10

**Comment by KnightMiner** [comment]
It would also be nice to have this to search preceeding whitespace. In NEI I would often search " ore" to get a list of all ores (and not blocks with words like more)

**Comment by AEnterprise** [comment]
could the exact searching also include wildcards? if for example you want all things like "improved * chestplate" where the materal name is the * (diamond/iron/gold/...)

**Comment by mezz** [comment]
For ores you can use the oreDictionary search prefix `$`, so `$ore`.
For finding "improved * chestplate" just type `improved chestplate`, it will be almost exactly the same.

**Comment by AEnterprise** [comment]
alright, thanks for the info :)

**Comment by Barhandar** [comment]
I also would like search to not ignore whitespace. When I search for, say, " axe" I want to _not_ see "pickaxe" in the output. When I search for `"@chisel "`, I do not want to see things from Chisels & Bits. When I search " plate", I do not want to see armor in the output.

And no, "use oredict search prefix" is not a replacement for any of these, nor will it actually show the correct output. Not everything is registered in OD.

P.S. Occam's Razor: making filter respect whitespace is less entities than making the quotes non-literal. And an improvement would be "make JEI filtering work exactly as NEI's Extended (which is default in it) filter mode", or "allow choosing between current filter and full-on RegEx".

**Comment by mezz** [comment]
I'll be adding the quotes feature soon, my previous reply was to show workarounds.
 
Regex will not be supported by default, there is another issue about it here: https://github.com/mezz/JustEnoughItems/issues/63

**Comment by SoniEx2** [comment]
Can we get anchors or something?

Maybe `[[<search>]]`?

(Regex can do that natively, but we don't have regex. TL;DR: Most use cases can be solved with regex.)
