### ISSUE TITLE
JEI Unresponsive

### ISSUE THREAD

**Issue by tacogerbil** [mezz/JustEnoughItems#654]
I'm using JEI JEI@3.13.6.387.  Forge 12.18.2.2151, MC 1.10.2

I was trying to clear off JEI momentarily so I could use a gui button that was being obscured by the JEI interface.  I typed in the letter o and a tilde.. Items in the list went away, I was able to press the gui button I needed.... but now JEI will not allow me to erase those characters from the search bar.  I've used the config to relocate it, changed modes.. you name it.  I am not allowed to delete it nor press the config button by the search bar (the wrench).   
![image](https://cloud.githubusercontent.com/assets/12961907/20929682/b8a91344-bb7f-11e6-9f91-8c964670839c.png)

**Comment by mezz** [comment]
Thanks for the report!
This sounds exactly like what another player was describing to me earlier, they made an issue here: 
https://github.com/mezz/JustEnoughItems/issues/649

It looks like a bad mod interaction.
Can you help them narrow down which mod is not working well with JEI there so that I can help fix it?
