### ISSUE TITLE
[enhancement] Add a hook to allow JEI to read the player.dat file

### ISSUE THREAD

**Issue by dsmall3303** [mezz/JustEnoughItems#662]
Hopefully this wouldn't require a coremod to do, but it's something that I think would be interesting for a few mod ideas I have kicking around that would only show certain items in JEI if they have a certain thing enabled (basically opt-in silliness, since I know some people don't like to even see it in the game). If hiding recipes isn't possible, then maybe allow the showing of an alternate screen (something like "you need X before you can learn about this") would be cool.

**Comment by mezz** [comment]
You can add recipes to JEI any time, so do accomplish you might just avoid adding the recipes at first and then add them as they're unlocked.
For the Thaumcraft plugin in 1.8.9 I just drew a red X over the crafting arrow when something was not researched, it was easier to manage things that way because it turned out to be a lot of work to track which recipes were available. It was also less confusing to players who were looking for specific recipes and thought that they were missing entirely.

**Comment by dsmall3303** [comment]
Ah, I was unaware that was the case. That makes things a ton easier!
