### ISSUE TITLE
[enhancement] You should absorb NoMoreRecipeConflict.

### ISSUE THREAD

**Issue by MentalMouse** [mezz/JustEnoughItems#674]
The mod [NoMoreRecipeConflict](https://mods.curse.com/mc-mods/minecraft/238123-stimmedcow-nomorerecipeconflict) is licensed as public domain.  It really _ought_ to be merged into Forge, but failing or pending that, it would be an excellent idea for you to absorb its functionality into JEI.

**Comment by mezz** [comment]
Thanks for the suggestion!
It's a good mod, but it works fine as it is. I don't see any reason for JEI to have this functionality, I try to keep it very light on extra features.

**Comment by MentalMouse** [comment]
Reasons:

- JEI and NMRC are the two must-have mods for managing mod items and recipes.  "Tastes great together!"
- Gives your mod a useful response to "I can see the recipe for X, but why does it produce Y instead?"  And you're already manipulating the crafting GUI for your "fill in ingredients" feature.
- Combining them means that people only need to download one mod (the better-known one) in order to have all their mods' recipes "just work".  (deleted comment about NMRC not updating, as they just did)

**Comment by mezz** [comment]
There are a lot of things that would be convenient to have in JEI, but it's against the design philosophy to add them.

[Here's a list of all NEI's features and where they ended up in 1.10+](https://docs.google.com/spreadsheets/d/1NEWZjKvWB-SibY1BXc1zoYkK7AhjMMBZess9wMy--6w/edit#gid=0).

As you can see, JEI covers a small subset of those feature. It is very focused on a specific area.
I can polish, improve, and update the features I am focused on much more effectively this way.
If I add lots of other features the mod will become bloated and harder to maintain.

Additionally, anything added to JEI will "lock out" other mods from adding their own implementations, because every pack has JEI included.
I do not want to claim a monopoly on certain features the way NEI did.

**Comment by AEnterprise** [comment]
maybe not having the mod in JEI but he brings a valid point: if 2 mods add the same recipe it usually gives confusion

could it be an option for JEI to add an marker when it displays such recipe? it doesn't fix the problem but the user is notified about the conflict so they know where the problem lies when trying to craft it

**Comment by mezz** [comment]
Unfortunately recipe conflicts are very inefficient to detect. 
When you place some items in the crafting table, it's easy to check if multiple recipes match. 
However doing the reverse of that at loading time is very hard, you have to find all the input combinations that conflict.

It would be possible to create an addon mod for JEI that uses its API to detect most recipe conflicts, and it would be useful for pack makers. I think it would be too slow to have it running every time you start the game, so I wouldn't want to add it to JEI directly or have it running when the game loads.

**Comment by AEnterprise** [comment]
ok no problem, just an idea i had

**Comment by MentalMouse** [comment]
Well, I still think the recipe-choosing option would be a natural fit with what JEI already does. 

But it's your mod, and your choice for what the mod should do.
