### ISSUE TITLE
Recipe Searching for items with non-matching NBT / Metadata

### ISSUE THREAD

**Issue by oitsjustjose** [mezz/JustEnoughItems#69]
This bug is a smaller one, but I do want to note it. I'm not sure if resolving it will cause JEI to no longer be light and un-intensive, but hopefully it can be worked around.

If an item in my inventory (tools / pouches / etc.) has NBT Data / Metadata (such as normal tool damage), hitting the recipe key shows no recipe. It's basically searching **very** strictly, which isn't wrong, but like I said, I don't know if there's a lightweight workaround.

**Comment by mezz** [comment]
It should be possible (and simple) to add special meta handling for damaged tools.

NBT is trickier. In the advanced config settings, you can add NBT for JEI to ignore. By default, it has some of the NBT tags added by vanilla Minecraft for tile entity data. I can't ignore all NBT because items can use it to differentiate sub-items, like Bees.

**Comment by mezz** [comment]
There is now a way to add ignored NBT tags for specific items.
Still looking at tool meta.
