### ISSUE TITLE
Crash when search or deleting search words

### ISSUE THREAD

**Issue by Vmechanic** [mezz/JustEnoughItems#706]
I have a problem or bug with JEI. when I try to use JEI search bar I try to type or backspace a work it will crash.
I don't  know it might be my mods that are causing this problem.
Here is pastebin of my crash report: [http://pastebin.com/Yjbf8BLw]

**Comment by mezz** [comment]
Thanks for the report!
This is not actually from JEI, it is from an item rendering. 
It could be from any mod but Optifine has cause an issue like this in the past, try removing it.

**Comment by Vmechanic** [comment]
It works now. Thank you

**Comment by Zarepheth** [comment]
In reference to issue #707 removing Optifine enables JEI to work without crashing the game. All other mods remaining as they were.

However, I don't like this configuration because I suffer significant problems with Lag... Any idea if there is a specific set of Optifine settings I can adjust to avoid the error while still using both Optifine and JEI?

**Comment by mezz** [comment]
Please report the issue to Optifine and link back to this issue.
https://github.com/sp614x/optifine/issues
They tend to be pretty quick to fix crashes like this.

**Comment by Zarepheth** [comment]
Thanks for pointing me to Optifine's Issues log. I couldn't find it on their main website.

**Comment by Zarepheth** [comment]
Apparently, newer versions of Forge do not play well with Optifine. Both are trying to access and modify the same private data structures in the Vanilla Minecraft code... You can read about it on Optifine issue 438.

**Comment by mezz** [comment]
It looks like this issue has been recently closed https://github.com/sp614x/optifine/issues/438
