### ISSUE TITLE
[1.11.2] LittleTiles issue

### ISSUE THREAD

**Issue by CreativeMD** [mezz/JustEnoughItems#718]
Hey,
i'm the author of LittleTiles and there seems to be a weird issue. The game crashes once it tries to render some of my items or blocks (more likely blocks). One of my block should never be rendered in inventory (remove it from the creative inventory), so the question is does JEI change anything about it?

I have no idea what exactly is causing it and i can't get any information out of the crash log itself. Maybe you can help out?
https://gist.github.com/CreativeMD/883fc17511df68cff971f8c6ba3e97b4

**Comment by mezz** [comment]
Thanks for the report!
There are a few things going on here:
1. JEI gets items and blocks from their respective registries, in addition to the creative tabs.
2. Your item has no model, and you have the new Forge that shows text on missing models.
3. Optifine crashes with Forge's text on missing models (#714), it has been fixed in Optifine preview B7 for 1.11.2.

You can fix the crash by updating Optifine, and you can hide the items/blocks that have missing models from JEI by using the blacklist from the API: https://github.com/mezz/JustEnoughItems/wiki/Hiding-Ingredients

**Comment by CreativeMD** [comment]
Thank you very much for this good and fast response. I thought this gonna be a lot more complicated, but I won't complain :D
