### ISSUE TITLE
Ticking memory connection when running both JEI and Slug's Class Picker

### ISSUE THREAD

**Issue by Winddbourne** [mezz/JustEnoughItems#725]
This crash happens when you load up a mod pack with both mods active and try to either create a new world or enter one that has already been created.  I have also e-mailed Slug about the crash but he hasn't been on in over a week and doesn't appear to have a github.

The original crash actually happened in a mod pack I'm working on with nearly 100 files and I actually had to recreate the pack one file at a time to find out where the conflict was. This file is from another test mod pack with just the two mods installed for the sake of simplicity. You have enough on your plate as a programmer without having to worry about pack issues and hundreds of files interacting. lol

Here's hoping you isolate the problem and provide a fix.  :)

https://gist.github.com/Winddbourne/f8724b835b10a60e1b15a95465711fe4

**Comment by mezz** [comment]
Thanks for the report!
Seems like you narrowed it down well, but the crash is most likely on their side and I'm not sure how JEI is affecting it. 
Hopefully they can get back to you soon.

**Comment by pau101** [comment]
Checked out this report since it sounded interesting and discovered quite a funny cause, so I've got the interaction mystery solved @mezz:

Class Picker is horribly subscribed to the top level Forge `PlayerEvent` where it increments a counter each call and when it reaches 100 it sets a boolean "ingame" to true. If the player is an EntityPlayerMP and "ingame" is true it performs logic for sending the player a message to pick a class. When JEI starts the `PlayerEvent` hook gets called with `PlayerEvent.ItemTooltipEvent` hundreds of times from different components of JEI initialization resulting in "ingame" being true. Then when the player joins the server a `PlayerEvent.LoadFromFile` event occurs causing Class Picker to try to send a message to the player before the player's connection is nonnull.

The solution is for this part of Class Picker logic to be rewritten. @Winddbourne it would be helpful if you could forward what I've said to Slug.

**Comment by mezz** [comment]
Yikes okay. Thanks for looking into it.

For that purpose, I recommend subscribing to server `PlayerEvent.PlayerLoggedInEvent` and then send a packet to the client to display the message. It is the earliest point you can detect that the player is in the world and should be perfectly reliable.

**Comment by Winddbourne** [comment]
Thank you! I was wondering what was going on. I briefly had the two working
together this morning; but that was during the time when the NEI wasn't
loading up and showing properly.
