### ISSUE TITLE
[Oddity] Weird console spam

### ISSUE THREAD

**Issue by MysticAura** [mezz/JustEnoughItems#737]
MC: 1.10.2
Forge: 2185
JEI Versions: jei_1.10.2-3.14.5.406&407

When I was testing out the pack and reading through the console on launch, I noticed this odd spam. Then a pattern became apparent so I looked closer. It is spelling out blocks 1 letter at a time.  Thought you may be interested. 

[Console Spam](http://pastebin.com/772v5SJC)

**Comment by mezz** [comment]
Thanks for the report!
Someone just told me about this on Discord, it seems to be caused by the Natural Pledge mod.
Somehow they are feeding oreDictionary names into JEI one letter at a time? I have no idea why or how, but it seemed to go away when that mod was removed.
If you remove that mod and the issue goes away, please report to them here:
https://github.com/yrsegal/NaturalPledge/issues

**Comment by MysticAura** [comment]
Thanks mezz, I'll do that :)
