### ISSUE TITLE
[1.10.2] [3.14.6.412] Not showing machine recipes for IE

### ISSUE THREAD

**Issue by TheBritishBrotherhood** [mezz/JustEnoughItems#747]
Hello.

Im not sure if this is a fault of yours or ImmersiveEnginering but there are no recipes showing for machines.

Coal coke, steel etc doesn't show the recipes within the blast furnace and coke oven etc.

If i use an older JEI [3.14.3.403] the recipes work again.

I hope this is enough information.

**Comment by mezz** [comment]
Thanks for the report!
There was a recent bug in ImmersiveEnginering that caused it to break other mod's recipes in JEI. I had to put a new check into JEI that prevents the bug and it breaks ImmersiveEnginering's recipes instead.
They are working on an update and it will be fixed in their next version.
