### ISSUE TITLE
4.3.2 not backwards compatible (Mekanism)

### ISSUE THREAD

**Issue by tomelfring** [mezz/JustEnoughItems#822]
There's currently an issue with JEI 4.3.x and Mekanism 1.11.
All recipes aren't showing and the log is quite obvious with what's wrong, but I don't know how to solve it.

Can you point me in the right direction?

Mekanism issue: https://github.com/aidancbrady/Mekanism/issues/4325
Log: https://gist.github.com/thommy101/833a45670461a39bed96b0109257c99e

**Comment by mezz** [comment]
Thanks for the report!
You say it's not backwards compatible, which JEI version does Mekanism work correctly with?
If it works fine for some JEI version on 1.11.2 then this is a JEI problem. 
If Mekanism only works with JEI on 1.10 then this is a Mekanism problem.

**Comment by mezz** [comment]
From the issue you linked, it seems to work with jei_1.11.2-4.2.10.248 so this is probably a JEI problem.
I'll look into it.

**Comment by mezz** [comment]
I looked into it more and Mekanism is using a JEI internal class, `BrokenCraftingRecipeException`.
The location of this class has changed, so Mekanism's integration broke.

I recommend removing the try/catch from `mekanism.client.jei.crafting.ShapedMekanismRecipeWrapper#getIngredients` since any crash there should already be handled by JEI.

Since Mekanism does not update very frequently, it's incredibly important that it avoids importing any JEI internal classes. If there are any imports of `mezz.jei.` that aren't ` mezz.jei.api.` they can break.

**Comment by tomelfring** [comment]
Thank you for your time and explanation!
