### ISSUE TITLE
Drawing Order Issues

### ISSUE THREAD

**Issue by ColinGBos** [mezz/JustEnoughItems#86]
In a gui that I'm working on, I have a couple of drawHoveringText calls from drawContainerForeGroundLayer that aren't ItemStack displays (which are drawn last, properly). These get drawn under the JEI display, is there some order I can call the elements of drawScreen to change this?
![2016-01-05_10 30 59](https://cloud.githubusercontent.com/assets/5392006/12119233/753e22f6-b398-11e5-89e6-db772aa26fba.png)

**Comment by mezz** [comment]
This is an unfortunate issue that I've looked at pretty closely.

The problem is that the black background, the container background, and tooltips are drawn one after the other with no chance of drawing something in between.

My options are to draw behind that (behind the black), or in front of it (and block tooltips).
I think NEI had this same issue.

I will have to poke Forge and see if anything can be done.

**Comment by Prospector** [comment]
Is it out of the question to try to wrap the icons around tooltips? I feel
like that would be very hard to do...

**Comment by TehNut** [comment]
That would also be super annoying from a player perspective.

**Comment by mezz** [comment]
Talked to fry and I'll need to add an event hook for it.

**Comment by buttilda** [comment]
I usually draw my tooltips like this:

```
@Override
public void drawScreen(int mouseX, int mouseY, float partialTickTime) {
    super.drawScreen(mouseX, mouseY, partialTickTime):

    // tooltips go here
}
```

And I never had any problems with them looking weird with other mods. It worked with NEI, but I haven't tested it with JEI yet.

**Comment by mezz** [comment]
PR accepted! Now that we have a Gui drawBackground() hook in Forge, guis can draw their tooltips normally (like vanilla) and JEI will just work. Yay. Fix incoming.

**Comment by ColinGBos** [comment]
\o/
