### ISSUE TITLE
Newest JEI Crashes w/ Chisels & Bits Mod

### ISSUE THREAD

**Issue by WenXin20** [mezz/JustEnoughItems#89]
1.8 JEI v2.14.0.139 crashes with Chisels & Bits Mod with the NoClassDefFoundError: mezz/jei/api/JEIManager

**Comment by mezz** [comment]
Thanks for the report!

They have outdated JEI integration. 
AlgorithmX2 is not updating Chisels and Bits for 1.8 any more, only 1.8.8+.
The latest 1.8.9 Chisels and Bits works fine with JEI.

You can either update to 1.8.8+ or continue using 1.8 JEI v1.13.

Since 1.8 mods are quickly moving to 1.8.9, this shouldn't be a problem for very long.
