### ISSUE TITLE
Immersive Engineering shaders cause large FPS drop

### ISSUE THREAD

**Issue by sparky8251** [mezz/JustEnoughItems#904]
I am not sure if JEI or Immersive is ultimately at fault but since I was able to narrow it down so specifically...

RR4 pack, 1.10.2, NO optifine, NO resource pack.

When I search @immersive in JEI my FPS drops 60%+ from 35 to single digits.

If I check @immersive pages with less shaders this FPS drop is less extreme but still present.

If I just search "shaders" so it pulls up the IE shaders, I get the same large FPS drop.

FPS drops also occur with Forestry cans when looking further.

I notice this happens in a different form with Tinkers. I get massive framerate lag but my FPS value from F3 doesnt seem to drop. Namely the pages with Tinkers tools items. More of the tools specifically the worse the issue gets.

I am using IE 58 and JEI 418 (slightly modified the RR pack since it occurred on the previous releases as well and i wanted to test if it was fixed).

Anything else I can provide? I can likely make a video demonstrating these issues as well if you so desire.

**Comment by darthvader45** [comment]
I have had this issue as well with IE 0.11.59 installed with the latest release JEI for 1.11.2.

**Comment by mezz** [comment]
Thanks for the report!
These are known issues and it comes down to the fact that these items use custom rendering which JEI cannot safely optimize. Since their rendering is slightly slow and JEI displays a lot of them, it can decrease FPS.
I think you should check the issue trackers for those mods, since you should be able to see similar FPS drops from having an inventory full of these items and JEI disabled.

**Comment by darthvader45** [comment]
No problem, mezz.  Will do.
